Repository google/blockly, pull requests merged in 2019-10, with the labels that each got.

#3154 Get rid of unnecessary nulls in block dragger, insertion marker manag…
  core/block_dragger.js
  core/gesture.js
  core/insertion_marker_manager.js
Labels: type: cleanup

#3155 Make trashcan setOpen package and update a few annotations.
  core/block_dragger.js
  core/bubble_dragger.js
  core/trashcan.js
  core/workspace_svg.js
Labels: type: cleanup

#3168 Remove call to setText in playground
  tests/playground.html
Labels: type: cleanup

#3203 Initialize drag delta to (0,0) and update annotation.
  core/gesture.js
Labels: type: cleanup

#3214 bringToFront optimization for large workspaces
  core/block_svg.js
Labels: component: performance

#3252 Fix blocks tests
  tests/blocks/index.html
Labels: component: tests

#3201 More field dispose
  core/blockly.js
  core/components/component.js
  core/field.js
  core/field_angle.js
  core/field_colour.js
  core/field_dropdown.js
  core/field_image.js
  core/field_multilineinput.js
  core/field_textinput.js
  core/field_variable.js
Labels: component: performance

#3211 Fix 55 warnings related to flyouts.
  core/blockly.js
  core/dropdowndiv.js
  core/flyout_base.js
  core/gesture.js
  core/inject.js
  core/mutator.js
  core/scrollbar.js
  core/toolbox.js
  core/trashcan.js
  core/workspace.js
  core/workspace_drag_surface_svg.js
  core/workspace_dragger.js
  core/workspace_svg.js
Labels: type: cleanup

#3267 Fix #1714
  core/xml.js
Labels: type: cleanup

#3271 Fix jsdoc. @return instead of @returns
  core/field_textinput.js
  core/renderers/measurables/rows.js
  core/renderers/zelos/measurables/rows.js
  demos/custom-fields/pitch/field_pitch.js
Labels: type: cleanup

#3270 Fix 11 warnings related to number of arguments passed.
  blocks/procedures.js
  core/block_svg.js
  core/blockly.js
  core/connection.js
  core/generator.js
  core/insertion_marker_manager.js
  core/variable_map.js
  core/workspace.js
Labels: type: cleanup

#3273 Fix 14 warnings related to workspace svg
  core/options.js
  core/workspace.js
  core/workspace_svg.js
Labels: type: cleanup

#3276 Fix 11 warnings related to block_svg
  core/block_svg.js
  core/comment.js
  core/field.js
  core/gesture.js
  core/keyboard_nav/navigation.js
  core/workspace_svg.js
Labels: type: cleanup

#3277 Fix compiler warnings related to XML
  core/block_svg.js
  core/utils/xml.js
  core/xml.js
Labels: type: cleanup

#3293 Fix 6 warnings related to generators.
  core/generator.js
Labels: type: cleanup

#3303 Suppress workspace comment compiler errors.
  core/contextmenu.js
  core/workspace_svg.js
  core/xml.js
Labels: type: cleanup

#3309 Fix warnings related to insertion markers.
  core/block_svg.js
  core/insertion_marker_manager.js
  core/rendered_connection.js
Labels: type: cleanup

#3307 Fix warnings related to gestures and drag.
  core/block_dragger.js
  core/block_svg.js
  core/bubble.js
  core/gesture.js
  core/touch_gesture.js
  core/workspace_comment_svg.js
  core/workspace_svg.js
Labels: type: cleanup

#3278 Fix 11 warnings related to variables and variable_model.
  core/block.js
  core/variable_map.js
  core/variables.js
  core/variables_dynamic.js
  core/workspace.js
Labels: type: cleanup

#3294 Fix 8 warnings related to utils.
  core/keyboard_nav/cursor.js
  core/ui_menu_utils.js
  core/utils.js
  core/utils/colour.js
Labels: type: cleanup

#3310 Fix scrollbar warnings.
  core/scrollbar.js
Labels: type: cleanup

#3304 Fix compiler warnings in procedures
  core/names.js
  core/procedures.js
Labels: type: cleanup

#3306 Fix warnings related to connections.
  blocks/logic.js
  core/block.js
  core/block_dragger.js
  core/block_svg.js
  core/connection.js
  core/connection_db.js
  core/insertion_marker_manager.js
  core/keyboard_nav/navigation.js
  core/rendered_connection.js
  tests/mocha/connection_db_test.js
  tests/mocha/connection_test.js
Labels: type: cleanup

#3326 [zelos] Draw a notch after a statement input
  core/renderers/common/constants.js
  core/renderers/common/info.js
  core/renderers/zelos/constants.js
  core/renderers/zelos/drawer.js
Labels: component: rendering

#3311 Move right corner support to common rendering.
  core/renderers/common/constants.js
  core/renderers/common/drawer.js
  core/renderers/common/info.js
  core/renderers/measurables/rows.js
  core/renderers/zelos/constants.js
  core/renderers/zelos/drawer.js
  core/renderers/zelos/info.js
  core/renderers/zelos/measurables/rows.js
Labels: component: rendering

#3331 Add langfiles build task in gulp
  gulpfile.js
  package.json
Labels: component: build process

#3000 Using a HTML canvas for computing the text width
  core/field.js
  core/field_dropdown.js
  core/field_multilineinput.js
  core/field_textinput.js
  core/utils/dom.js
Labels: component: performance

#3336 Resolve all type issues with disposal
  core/block.js
  core/block_svg.js
  core/bubble_dragger.js
  core/flyout_base.js
  core/grid.js
  core/input.js
  core/trashcan.js
  core/workspace_dragger.js
  core/workspace_svg.js
Labels: type: cleanup

#3335 Resolve remaining compiler warnings with visibility issues
  core/block.js
  core/block_dragger.js
  core/block_svg.js
  core/blockly.js
  core/contextmenu.js
  core/gesture.js
  core/touch.js
  core/workspace.js
  core/workspace_comment_svg.js
Labels: type: cleanup

#3337 Fix dummy input alignment. Fix for #3330
  core/renderers/common/info.js
  core/renderers/geras/info.js
  core/renderers/measurables/inputs.js
Labels: component: rendering

#3324 [Zelos] Fix dynamic connection shape size
  core/renderers/geras/measurables/inputs.js
  core/renderers/measurables/connections.js
  core/renderers/measurables/inputs.js
  core/renderers/measurables/rows.js
  core/renderers/zelos/constants.js
  core/renderers/zelos/drawer.js
  core/renderers/zelos/info.js
Labels: component: rendering

#3334 Resolve remaining compiler type warnings
  core/block.js
  core/block_drag_surface.js
  core/block_svg.js
  core/blockly.js
  core/contextmenu.js
  core/events.js
  core/extensions.js
  core/grid.js
  core/keyboard_nav/ast_node.js
  core/workspace.js
  core/workspace_audio.js
  core/workspace_svg.js
Labels: type: cleanup

#3308 Fix warnings related to icons and bubbles
  core/bubble.js
  core/comment.js
  core/icon.js
  core/mutator.js
  core/warning.js
Labels: type: cleanup

#3333 Remove @deprecated annotation on Blockly.bindEvent_
  core/blockly.js
  core/components/tree/treecontrol.js
  core/flyout_base.js
  core/inject.js
Labels: type: cleanup

#3342 Dummy input right alignment
  core/renderers/common/constants.js
  core/renderers/common/info.js
  core/renderers/geras/info.js
  core/renderers/thrasos/info.js
  tests/blocks/test_blocks.js
  tests/playground.html
Labels: component: rendering
