Repository google/blockly, pull requests merged in 2019-08, with the labels that each got.

#2865 Cleanup of last fortnight’s commits.
  core/block_svg.js
  core/comment.js
  core/components/component.js
  core/components/menu/menuitem.js
  core/components/tree/basenode.js
  core/components/tree/treecontrol.js
  core/css.js
  core/dropdowndiv.js
  core/field_colour.js
  core/field_label.js
  core/field_label_serializable.js
  core/field_registry.js
  core/field_textinput.js
  core/keyboard_nav/action.js
  core/keyboard_nav/cursor_svg.js
  core/keyboard_nav/key_map.js
  core/renderers/block_rendering_rewrite/block_render_draw.js
  core/renderers/block_rendering_rewrite/block_render_draw_debug.js
  core/renderers/block_rendering_rewrite/block_render_draw_highlight.js
  core/renderers/block_rendering_rewrite/block_render_info.js
  core/renderers/block_rendering_rewrite/block_rendering.js
  core/renderers/block_rendering_rewrite/block_rendering_constants.js
  core/renderers/block_rendering_rewrite/highlight_constants.js
  core/toolbox.js
  core/utils/aria.js
  core/utils/idgenerator.js
  core/utils/keycodes.js
  core/utils/style.js
  core/zoom_controls.js
Labels: type: cleanup

#2855 Field colour + Blockly actions
  core/field_colour.js
Labels: type: accessibility

#2861 Cleanup closure typings
  core/ui_menu_utils.js
  typings/blockly.d.ts
  typings/parts/goog-closure.d.ts
Labels: type: cleanup

#2853 Field angle keyboard navigation
  core/field_angle.js
  core/field_textinput.js
Labels: type: accessibility

#2893 Reorder package.json.
  package.json
Labels: type: cleanup

#2895 Add local build tasks to gulp
  gulpfile.js
  package.json
Labels: component: build process
