Repository google/blockly, pull requests merged in 2020-02, with the labels that each got.

#3685 [zelos] Set a maximum width for dynamic connection shapes.
  core/renderers/common/info.js
  core/renderers/zelos/constants.js
  core/renderers/zelos/drawer.js
  core/renderers/zelos/info.js
  core/renderers/zelos/measurables/rows.js
Labels: component: rendering

#3686 Zelos adjust top / bottom row padding based on
  core/renderers/zelos/constants.js
  core/renderers/zelos/info.js
Labels: component: rendering

#3691 Update gulpfile to use exports instead of gulp.task syntax
  gulpfile.js
  package.json
Labels: component: build process, type: cleanup

#3702 Support ES6 classes in renderer initialization
  core/renderers/common/block_rendering.js
Labels: component: rendering

#3693 Break gulpfile into multiple subfiles
  .eslintignore
  gulpfile.js
  scripts/gulpfiles/build_tasks.js
  scripts/gulpfiles/git_tasks.js
  scripts/gulpfiles/package_tasks.js
  scripts/gulpfiles/typings.js
  tests/scripts/check_metadata.sh
Labels: component: build process, type: cleanup

#3703 [zelos] Fix centered textinputs
  core/block.js
  core/renderers/zelos/info.js
  core/renderers/zelos/measurables/rows.js
Labels: component: rendering

#3714 Use flex to compute measure font metrics
  core/utils/dom.js
Labels: component: rendering

#3715 Configure zelos selected glow properties in theme
  core/renderers/zelos/constants.js
  core/theme/highcontrast.js
Labels: component: rendering, component: themes
