Repository google/blockly, pull requests merged in 2020-07, with the labels that each got.

#3996 Advanced compilation gulp script to replace the shell script.
  .gitignore
  gulpfile.js
  package.json
  scripts/gulpfiles/build_tasks.js
Labels: component: build process

#4016 Fix field dropdown with images
  core/menuitem.js
Labels: type: bug, type: regression

#4029 Remove some old deprecated functions
  core/css.js
  core/variables.js
  core/workspace.js
  core/workspace_svg.js
Labels: api_change
