Repository google/blockly, pull requests merged in 2021-06, with the labels that each got.

#4870 Use String() over toLocaleString when possible
  core/field_number.js
  demos/code/msg/en.js
Labels: component: performance

#4904 Remove extra space in generator error message.
  core/generator.js
Labels: component: generators

#4915 Remove return value from Field dropdownCreate_
  core/field_angle.js
  core/field_colour.js
  core/field_dropdown.js
  tests/mocha/field_colour_test.js
Labels: type: cleanup

#4951 Remove deprecated build.py script
  appengine/.gcloudignore
  build.py
  core/blockly.js
  msg/messages.js
Labels: component: build process, type: cleanup
