Repository google/blockly, pull requests merged in 2021-11, with the labels that each got.

#5649 fix(zelos): typo
  core/renderers/zelos/info.js
Labels: cla: yes

#5660 chore: Normalize ++x to x++.
  core/block.js
  core/extensions.js
  core/field_dropdown.js
  core/input.js
  core/utils.js
  generators/dart/logic.js
  generators/javascript/logic.js
  generators/lua/logic.js
  generators/php/logic.js
  generators/python/logic.js
Labels: low priority, type: cleanup, cla: yes, PR: chore

#5664 chore: Update dependabot labelling config
  .github/dependabot.yml
Labels: cla: yes, PR: chore

#5669 fix: Don't crash when unable to post comment to PR
  .github/workflows/check_clang_format.yml
Labels: cla: yes, PR: chore

#5670 chore: Create separate report_clang_format workflow in master branch
  .github/workflows/report_clang_format.yml
Labels: cla: yes, PR: chore

#5671 chore: Remove spurious extra `on` clause in report_clang_format.yml
  .github/workflows/report_clang_format.yml
Labels: cla: yes, PR: chore

#5673 chore: More spelunking in GitHub Action data
  .github/workflows/report_clang_format.yml
Labels: cla: yes, PR: chore

#5655 docs: Fix a few typos
  core/contextmenu_items.js
  core/insertion_marker_manager.js
  core/toolbox/collapsible_category.js
  demos/blockfactory/workspacefactory/wfactory_controller.js
  demos/blockfactory/workspacefactory/wfactory_view.js
  tests/mocha/field_colour_test.js
Labels: cla: yes

#5661 chore: update javascript block generators to const and let
  generators/javascript/colour.js
  generators/javascript/lists.js
  generators/javascript/logic.js
  generators/javascript/loops.js
  generators/javascript/math.js
  generators/javascript/procedures.js
  generators/javascript/text.js
  generators/javascript/variables.js
  tests/deps.mocha.js
Labels: cla: yes

#5663 chore: update php block generators to const and let
  generators/php/colour.js
  generators/php/lists.js
  generators/php/logic.js
  generators/php/loops.js
  generators/php/math.js
  generators/php/procedures.js
  generators/php/text.js
  generators/php/variables.js
  tests/deps.mocha.js
Labels: cla: yes

#5662 chore: update lua block generators to const and let
  generators/lua/colour.js
  generators/lua/lists.js
  generators/lua/logic.js
  generators/lua/loops.js
  generators/lua/math.js
  generators/lua/procedures.js
  generators/lua/text.js
  generators/lua/variables.js
  tests/deps.mocha.js
Labels: cla: yes

#5680 fix: isPrime block should cast str as num
  generators/javascript/math.js
  tests/generators/golden/generated.js
Labels: component: generators, cla: yes, PR: fix

#5681 fix: bad order of checks for setting flyout visibility
  core/toolbox/toolbox.js
  tests/mocha/insertion_marker_test.js
  tests/mocha/toolbox_test.js
Labels: cla: yes

#5677 chore: applies fixes to clang format
  .github/workflows/check_clang_format.yml
  package-lock.json
  package.json
  scripts/gulpfiles/build_tasks.js
Labels: cla: yes

#5682 chore: apply prefer-const rule fixes in mocha tests
  package-lock.json
  tests/mocha/astnode_test.js
  tests/mocha/block_json_test.js
  tests/mocha/block_test.js
  tests/mocha/comment_test.js
  tests/mocha/connection_checker_test.js
  tests/mocha/connection_db_test.js
  tests/mocha/connection_test.js
  tests/mocha/contextmenu_items_test.js
  tests/mocha/cursor_test.js
  tests/mocha/dropdowndiv_test.js
  tests/mocha/event_test.js
  tests/mocha/extensions_test.js
  tests/mocha/field_angle_test.js
  tests/mocha/field_checkbox_test.js
  tests/mocha/field_colour_test.js
  tests/mocha/field_dropdown_test.js
  tests/mocha/field_image_test.js
  tests/mocha/field_label_serializable_test.js
  tests/mocha/field_label_test.js
  tests/mocha/field_multilineinput_test.js
  tests/mocha/field_number_test.js
  tests/mocha/field_registry_test.js
  tests/mocha/field_test.js
  tests/mocha/field_textinput_test.js
  tests/mocha/field_variable_test.js
  tests/mocha/flyout_test.js
  tests/mocha/generator_test.js
  tests/mocha/gesture_test.js
  tests/mocha/input_test.js
  tests/mocha/insertion_marker_test.js
  tests/mocha/jso_deserialization_test.js
  tests/mocha/jso_serialization_test.js
  tests/mocha/json_test.js
  tests/mocha/keydown_test.js
  tests/mocha/logic_ternary_test.js
  tests/mocha/metrics_test.js
  tests/mocha/mutator_test.js
  tests/mocha/names_test.js
  tests/mocha/procedures_test.js
  tests/mocha/registry_test.js
  tests/mocha/serializer_test.js
  tests/mocha/shortcut_registry_test.js
  tests/mocha/test_helpers.js
  tests/mocha/theme_test.js
  tests/mocha/toolbox_helper.js
  tests/mocha/toolbox_test.js
  tests/mocha/tooltip_test.js
  tests/mocha/trashcan_test.js
  tests/mocha/utils_test.js
  tests/mocha/variable_map_test.js
  tests/mocha/variable_model_test.js
  tests/mocha/variables_test.js
  tests/mocha/widget_div_test.js
  tests/mocha/workspace_comment_test.js
  tests/mocha/workspace_helpers.js
  tests/mocha/workspace_svg_test.js
  tests/mocha/xml_test.js
Labels: cla: yes

#5683 chore: remove references to JSON extraction
  blocks/colour.js
  blocks/lists.js
  blocks/logic.js
  blocks/loops.js
  blocks/math.js
  blocks/text.js
  blocks/variables.js
  blocks/variables_dynamic.js
Labels: cla: yes

#5675 chore: revert github action
  .github/workflows/report_clang_format.yml
Labels: cla: yes

#5690 fix: Don't try to set text fields to null on cancel
  core/field_textinput.js
Labels: component: fields, cla: yes, PR: fix

#5692 fix: Don't try to set text fields to null on cancel (for master)
  blockly_compressed.js
  blockly_compressed.js.map
  core/field_textinput.js
  msg/json/qqq.json
Labels: component: fields, cla: yes, PR: fix

#5676 chore: fix more lint
  blocks/logic.js
  blocks/procedures.js
  blocks/text.js
  blocks/variables.js
  blocks/variables_dynamic.js
  core/block.js
  core/block_svg.js
  core/connection.js
  core/connection_checker.js
  core/css.js
  core/dropdowndiv.js
  core/extensions.js
  core/field.js
  core/field_multilineinput.js
  core/insertion_marker_manager.js
  core/interfaces/i_registrable_field.js
  core/keyboard_nav/ast_node.js
  core/mutator.js
  core/procedures.js
  core/rendered_connection.js
  core/renderers/common/constants.js
  core/renderers/common/marker_svg.js
  core/renderers/zelos/constants.js
  core/serialization/workspaces.js
  core/theme/classic.js
  core/theme/zelos.js
  core/utils.js
  core/variable_map.js
  core/variables_dynamic.js
  tests/playgrounds/screenshot.js
Labels: cla: yes

#5679 chore: add command to launch mocha tests
  package.json
Labels: cla: yes

#5698 chore: update `deps.js`, `deps.mocha.js`
  tests/deps.js
  tests/deps.mocha.js
Labels: cla: yes

#5703 fix: Quote Msg prop name to survive compile
  blocks/variables.js
  blocks/variables_dynamic.js
Labels: component: variables, cla: yes, PR: fix

#5705 chore: fix dependabot labels
  .github/dependabot.yml
Labels: cla: yes

#5706 chore: Move functions from utils
  core/block.js
  core/block_drag_surface.js
  core/block_svg.js
  core/bubble_dragger.js
  core/contextmenu.js
  core/extensions.js
  core/field.js
  core/field_dropdown.js
  core/field_image.js
  core/field_label.js
  core/field_label_serializable.js
  core/field_multilineinput.js
  core/field_textinput.js
  core/field_variable.js
  core/flyout_button.js
  core/icon.js
  core/rendered_connection.js
  core/renderers/common/constants.js
  core/scrollbar.js
  core/toolbox/category.js
  core/utils.js
  core/utils/parsing.js
  core/utils/svg_math.js
  core/workspace_comment_svg.js
  core/workspace_drag_surface_svg.js
  core/workspace_svg.js
  scripts/migration/renamings.js
  tests/deps.js
  tests/deps.mocha.js
  tests/mocha/utils_test.js
Labels: cla: yes

#5714 chore: move remaining functions out of utils.js
  core/block.js
  core/block_svg.js
  core/common.js
  core/component_manager.js
  core/extensions.js
  core/flyout_base.js
  core/theme_manager.js
  core/utils.js
  core/utils/array.js
  core/variable_map.js
  core/workspace.js
  core/workspace_svg.js
  scripts/migration/renamings.js
  tests/deps.js
  tests/deps.mocha.js
Labels: cla: yes

#5715 refactor: Update uncompiled-mode dependency loading for playground, tests
  blocks/lists.js
  scripts/gulpfiles/build_tasks.js
  tests/deps.js
  tests/deps.mocha.js
  tests/generators/index.html
  tests/mocha/index.html
  tests/playground.html
Labels: component: build process, cla: yes, PR: chore

#5709 chore: fix or ignore remaining lint
  .eslintrc.json
  blocks/lists.js
  blocks/math.js
  blocks/procedures.js
  blocks/text.js
  core/blockly.js
  core/comment.js
  core/contextmenu.js
  core/extensions.js
  core/flyout_base.js
  core/interfaces/i_serializer.js
  core/rendered_connection.js
  core/serialization/blocks.js
  core/serialization/variables.js
  core/trashcan.js
  core/workspace_comment_svg.js
  tests/mocha/.eslintrc.json
Labels: cla: yes

#5699 chore: move remaining function definitions out of blockly.js
  core/blockly.js
  core/common.js
  core/utils/string.js
  core/utils/svg_math.js
  core/workspace_svg.js
  scripts/migration/renamings.js
  tests/deps.js
Labels: cla: yes

#5717 chore: enable eslint-config-google
  .eslintrc.json
  core/common.js
  package-lock.json
  package.json
  scripts/migration/renamings.js
Labels: cla: yes

#5719 chore: Record renamings for named exports
  scripts/migration/renamings.js
Labels: cla: yes

#5728 chore: make Blockly.common.setSelected package and update docs
  core/common.js
Labels: cla: yes

#5730 chore: moves the public loop mixin into its own file
  blocks/loops.js
  core/blockly.js
  core/loop_mixin.js
  externs/block-externs.js
  externs/generator-externs.js
  generators/dart/loops.js
  generators/javascript/loops.js
  generators/lua/loops.js
  generators/php/loops.js
  generators/python/loops.js
  scripts/migration/renamings.js
  tests/deps.js
Labels: cla: yes

#5702 Enable the creation of concurrent, but not connected, output and previous connectors
  core/block.js
  core/connection.js
  core/connection_checker.js
  core/events/events_block_move.js
  core/keyboard_nav/ast_node.js
  tests/mocha/connection_checker_test.js
Labels: cla: yes

#5727 fix: Stop throwing error when PointerEvent.pageX is 0.
  core/touch_gesture.js
Labels: component: touch, cla: yes

#5742 refactor: Rename `ALIGN` to `Align` and move from `constants.js` to `input.js`
  core/block.js
  core/blockly.js
  core/constants.js
  core/input.js
  core/renderers/common/info.js
  core/renderers/zelos/info.js
  scripts/migration/renamings.js
  tests/deps.js
  tests/mocha/block_json_test.js
Labels: cla: yes, PR: chore

#5738 Migrate `blocks/colour.js` to goog.module syntax
  blocks/colour.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: cla: yes, PR: chore

#5745 chore(build): Update compiler & linter input language to ES2020
  .eslintrc.json
  scripts/gulpfiles/build_tasks.js
  tests/node/.eslintrc.json
Labels: component: build process, cla: yes, PR: chore

#5736 refactor: Migrate `blocks/procedures.js` to goog.module syntax
  blocks/procedures.js
  tests/deps.js
Labels: component: library blocks, cla: yes, PR: chore

#5746 refactor: Migrate `blocks/lists.js` to `goog.module` syntax
  blocks/lists.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: component: library blocks, cla: yes, PR: chore

#5744 chore: fix missing requires in generators
  generators/dart.js
  generators/dart/loops.js
  generators/dart/variables_dynamic.js
  generators/javascript.js
  generators/javascript/loops.js
  generators/lua.js
  generators/lua/loops.js
  generators/php.js
  generators/php/lists.js
  generators/php/loops.js
  generators/php/procedures.js
  generators/python.js
  generators/python/lists.js
  generators/python/loops.js
  generators/python/procedures.js
  generators/python/text.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: cla: yes

#5743 feat: clarify variable and procedure constants
  core/blockly.js
  core/generator.js
  core/internal_constants.js
  core/names.js
  core/procedures.js
  core/variables.js
  core/variables_dynamic.js
  core/workspace_svg.js
  tests/deps.js
Labels: cla: yes

#5748 refactor: Migrate `blocks/logic.js` to `goog.module` syntax
  blocks/logic.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: component: library blocks, cla: yes, PR: chore

#5739 fix: Prevent error when maxTrashcanContents is 0
  core/interfaces/i_positionable.js
  core/trashcan.js
  core/zoom_controls.js
Labels: cla: yes, PR: fix

#5749 refactor: migrate `generators/dart.js` to `goog.module` syntax
  generators/dart.js
  tests/deps.js
Labels: cla: yes

#5740 chore: revert #5730
  blocks/loops.js
  core/blockly.js
  core/loop_mixin.js
  generators/dart/loops.js
  generators/javascript/loops.js
  generators/lua/loops.js
  generators/php/loops.js
  generators/python/loops.js
  scripts/gulpfiles/chunks.json
  scripts/migration/renamings.js
  tests/deps.js
Labels: cla: yes

#5750 refactor: convert some js block generators to goog.module
  generators/javascript/text.js
  generators/javascript/variables.js
  generators/javascript/variables_dynamic.js
  tests/deps.js
Labels: cla: yes

#5755 refactor: Migrate `blocks/loops.js` to `goog.module` syntax
  blocks/loops.js
  generators/dart/loops.js
  generators/javascript/loops.js
  generators/lua/loops.js
  generators/php/loops.js
  generators/python/loops.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: component: library blocks, cla: yes, PR: chore
