Repository google/blockly, pull requests merged in 2021-08, with the labels that each got.

#5278 Update build artifact sizes in check_metadata.sh
  tests/scripts/check_metadata.sh
Labels: type: cleanup

#5282 Migrate core/events/events_marker_move.js to goog.module syntax
  core/events/events_marker_move.js
  tests/deps.js
Labels: type: cleanup

#5280 Migrate core/events/events_toolbox_item_select.js to goog.module syntax
  core/events/events_toolbox_item_select.js
  tests/deps.js
Labels: type: cleanup

#5284 Migrate core/events/events_click.js to goog.module syntax
  core/events/events_click.js
  tests/deps.js
Labels: type: cleanup

#5275 Migrate core/events/events_viewport.js to goog.module syntax
  core/events/events_viewport.js
  tests/deps.js
Labels: type: cleanup

#5176 Migrate core/menuitem.js to goog.module syntax
  core/menuitem.js
  tests/deps.js
Labels: cla: yes, type: cleanup

#5293 Migrate core/renderers/geras/constants.js to goog.module syntax
  core/renderers/geras/constants.js
  tests/deps.js
Labels: cla: yes, type: cleanup

#5281 Migrate core/events/events_selected.js to goog.module syntax
  core/events/events_selected.js
  tests/deps.js
Labels: cla: yes, type: cleanup

#5294 Remove require destructuring
  core/block_drag_surface.js
  core/comment.js
  core/connection_checker.js
  core/delete_area.js
  core/extensions.js
  core/field.js
  core/field_checkbox.js
  core/field_colour.js
  core/field_dropdown.js
  core/field_image.js
  core/field_label.js
  core/field_label_serializable.js
  core/field_multilineinput.js
  core/field_number.js
  core/field_textinput.js
  core/field_variable.js
  core/flyout_base.js
  core/flyout_button.js
  core/flyout_horizontal.js
  core/flyout_vertical.js
  core/icon.js
  core/interfaces/i_flyout.js
  core/interfaces/i_metrics_manager.js
  core/interfaces/i_positionable.js
  core/interfaces/i_selectable_toolbox_item.js
  core/interfaces/i_toolbox.js
  core/keyboard_nav/basic_cursor.js
  core/keyboard_nav/cursor.js
  core/keyboard_nav/tab_navigate_cursor.js
  core/renderers/common/info.js
  core/utils/toolbox.js
Labels: cla: yes, type: cleanup

#5242 Migrate core/toolbox/separator.js to goog.module syntax
  core/toolbox/separator.js
  tests/deps.js
Labels: cla: yes, type: cleanup

#5263 Migrate core/workspace_drag_surface_svg.js to goog.module syntax
  core/workspace_drag_surface_svg.js
  tests/deps.js
Labels: cla: yes, type: cleanup

#5277 Migrate core/events/events_trashcan_open.js to goog.module syntax
  core/events/events_trashcan_open.js
  tests/deps.js
Labels: cla: yes, type: cleanup

#5285 Migrate core/events/events_bubble_open.js to goog.module syntax
  core/events/events_bubble_open.js
  tests/deps.js
Labels: type: cleanup

#5290 Add supressPrefixSuffix to if/else block
  blocks/logic.js
  blocks/loops.js
  core/block.js
Labels: cla: yes

#5304 Migrate core/renderers/geras/highlighter.js to goog.module syntax
  core/renderers/geras/highlighter.js
  tests/deps.js
Labels: cla: yes, type: cleanup

#5305 Migrate core/renderers/geras/info.js to goog.module syntax
  core/renderers/geras/info.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5262 More cleanup of blockly.js
  core/block_dragger.js
  core/block_svg.js
  core/blockly.js
  core/common.js
  core/connection_checker.js
  core/dropdowndiv.js
  core/inject.js
  core/tooltip.js
  core/widgetdiv.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5303 Migrate core/renderers/geras/highlight_constants.js to goog.module syntax
  core/renderers/geras/highlight_constants.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5315 fix: update tag module workflow to add labels instead of setting one label
  .github/workflows/tag_module_cleanup.yml
Labels: type: cleanup, cla: yes

#5318 Revert "fix: update tag module workflow to add labels instead of setting one label"
  .github/workflows/tag_module_cleanup.yml
Labels: cla: yes

#5309 Migrate core/renderers/measurables/types.js to goog.module syntax
  core/renderers/measurables/types.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5295 Remove extra output from generator and mocha tests (#5196)
  tests/generators/run_generators_in_browser.js
  tests/mocha/run_mocha_tests_in_browser.js
  tests/scripts/run_generators.sh
Labels: type: cleanup, cla: yes

#5077 feat: upgrade fields to use new JSO hooks
  core/field_angle.js
  core/field_checkbox.js
  core/field_colour.js
  core/field_dropdown.js
  core/field_label_serializable.js
  core/field_multilineinput.js
  core/field_number.js
  core/field_textinput.js
  core/field_variable.js
  tests/mocha/field_angle_test.js
  tests/mocha/field_checkbox_test.js
  tests/mocha/field_colour_test.js
  tests/mocha/field_dropdown_test.js
  tests/mocha/field_label_serializable_test.js
  tests/mocha/field_multilineinput_test.js
  tests/mocha/field_number_test.js
  tests/mocha/field_textinput_test.js
  tests/mocha/field_variable_test.js
  tests/mocha/serializer_test.js
Labels: cla: yes

#5120 feat: add serialization of child blocks
  core/serialization/blocks.js
  tests/deps.js
  tests/mocha/jso_serialization_test.js
Labels: cla: yes

#5131 feat: add JSO serialization and deserialization of variables
  core/requires.js
  core/serialization/variables.js
  tests/deps.js
  tests/mocha/jso_serialization_test.js
Labels: cla: yes

#5132 feat: add top level `save` and `load` functions for JSO serialization
  core/requires.js
  core/serialization/blocks.js
  core/serialization/serialization.js
  core/serialization/workspaces.js
  tests/deps.js
  tests/mocha/serializer_test.js
Labels: cla: yes

#5137 feat: add deserialization of JSO block state
  core/serialization/blocks.js
  tests/mocha/serializer_test.js
Labels: cla: yes

#5322 Migrate core/block.js to goog.module syntax
  core/block.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5324 Add labels instead of setting in github action
  .github/workflows/tag_module_cleanup.yml
Labels: type: cleanup, cla: yes

#5323 Migrate core/block_svg.js to goog.module syntax
  core/block_svg.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5306 Migrate core/renderers/geras/path_object.js to goog.module syntax
  core/renderers/geras/path_object.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5149 Migrate core/contextmenu_registry.js to goog.module syntax
  core/contextmenu_registry.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5334 Migrate core/workspace_svg.js to goog.module syntax
  core/workspace_svg.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5340 Update optional requires
  core/extensions.js
  core/flyout_base.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5339 Add missing eslint disable line for required interface
  core/workspace.js
Labels: type: cleanup, cla: yes

#5166 feat: add initialization of blocks and event firing
  core/serialization/blocks.js
  tests/mocha/index.html
  tests/mocha/jso_deserialization_test.js
  tests/mocha/jso_serialization_test.js
  tests/playground.html
Labels: cla: yes

#5344 Fix issue that prevented Mocha and generator tests from running on certain configurations
  tests/generators/run_generators_in_browser.js
  tests/mocha/run_mocha_tests_in_browser.js
Labels: cla: yes

#5333 Update script to use python3 command
  appengine/add_timestamps.py
  scripts/gulpfiles/build_tasks.js
  scripts/i18n/common.py
  scripts/i18n/create_messages.py
  scripts/i18n/dedup_json.py
  scripts/i18n/js_to_json.py
  scripts/i18n/tests.py
Labels: cla: yes

#5308 Migrate core/renderers/measurables/base.js to goog.module syntax
  core/renderers/measurables/base.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5300 Migrate core/renderers/geras/drawer.js to goog.module syntax
  core/renderers/geras/drawer.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5307 Migrate core/renderers/geras/renderer.js to goog.module syntax
  core/renderers/geras/renderer.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5279 Migrate core/events/events_theme_change.js to goog.module syntax
  core/events/events_theme_change.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5286 Migrate core/events/events_block_drag.js to goog.module syntax
  core/events/events_block_drag.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5343 Use `goog.requireType` when importing interfaces (etc.)
  core/block.js
  core/block_dragger.js
  core/block_svg.js
  core/bubble.js
  core/connection.js
  core/connection_checker.js
  core/connection_db.js
  core/delete_area.js
  core/drag_target.js
  core/field.js
  core/flyout_base.js
  core/gesture.js
  core/input.js
  core/interfaces/i_ast_node_location_svg.js
  core/interfaces/i_ast_node_location_with_block.js
  core/interfaces/i_autohideable.js
  core/interfaces/i_bubble.js
  core/interfaces/i_collapsible_toolbox_item.js
  core/interfaces/i_delete_area.js
  core/interfaces/i_drag_target.js
  core/interfaces/i_draggable.js
  core/interfaces/i_flyout.js
  core/interfaces/i_positionable.js
  core/interfaces/i_selectable_toolbox_item.js
  core/interfaces/i_toolbox.js
  core/metrics_manager.js
  core/renderers/common/drawer.js
  core/renderers/common/info.js
  core/renderers/common/path_object.js
  core/renderers/common/renderer.js
  core/toolbox/category.js
  core/toolbox/collapsible_category.js
  core/toolbox/toolbox.js
  core/toolbox/toolbox_item.js
  core/trashcan.js
  core/workspace.js
  core/workspace_comment_svg.js
  core/workspace_svg.js
  core/zoom_controls.js
  scripts/gulpfiles/build_tasks.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5265 Migrate core/procedures.js to goog.module syntax
  core/procedures.js
  tests/deps.js
Labels: type: cleanup, api_change, cla: yes

#5234 Migrate core/bubble.js to goog.module syntax
  core/bubble.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5067 Migrate core/utils/aria.js to goog.module.
  core/utils/aria.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5321 Migrate core/variables.js to goog.module syntax
  core/variables.js
  tests/deps.js
  tests/mocha/field_variable_test.js
Labels: type: cleanup, cla: yes

#5359 Quiet the typings script unless you tell it to be verbose.
  scripts/gulpfiles/typings.js
Labels: cla: yes

#5059 Migrate core/utils/string.js to goog.module syntax
  core/utils/string.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5362 Quiet the typings script unless you tell it to be verbose.
  scripts/gulpfiles/typings.js
Labels: type: cleanup, cla: yes

#5369 Fix blocks with no next connections overlapping statement input in Zelos
  core/renderers/zelos/info.js
Labels: cla: yes

#5365 Migrate core/renderers/minimalist/renderer.js to goog.module syntax
  core/renderers/minimalist/renderer.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5363 Migrate core/renderers/minimalist/constants.js to goog.module syntax
  core/renderers/minimalist/constants.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5364 Migrate core/renderers/minimalist/info.js to goog.module syntax
  core/renderers/minimalist/info.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5331 Migrate core/widgetdiv.js to goog.module syntax
  core/contextmenu.js
  core/field_multilineinput.js
  core/field_textinput.js
  core/widgetdiv.js
  demos/custom-fields/pitch/field_pitch.js
  tests/deps.js
  tests/mocha/field_textinput_test.js
  tests/mocha/test_helpers.js
  tests/mocha/widget_div_test.js
Labels: type: cleanup, cla: yes

#5381 Migrate core/renderers/measurables/row_elements.js to goog.module syntax
  core/renderers/measurables/field.js
  core/renderers/measurables/hat.js
  core/renderers/measurables/icon.js
  core/renderers/measurables/in_row_spacer.js
  core/renderers/measurables/jagged_edge.js
  core/renderers/measurables/round_corner.js
  core/renderers/measurables/row_elements.js
  core/renderers/measurables/square_corner.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5200 Add throwing exceptions during deserialization
  core/connection.js
  core/serialization/blocks.js
  core/serialization/exceptions.js
  tests/deps.js
  tests/mocha/jso_deserialization_test.js
  tests/mocha/test_helpers.js
Labels: cla: yes

#5216 feat: add serialization and deserialization of comments
  core/serialization/blocks.js
  tests/mocha/jso_serialization_test.js
  tests/mocha/serializer_test.js
Labels: cla: yes

#5246 Add serializing shadows as JSOs for the JSO system
  core/connection.js
  core/rendered_connection.js
  core/serialization/blocks.js
  tests/mocha/connection_test.js
  tests/mocha/jso_deserialization_test.js
  tests/mocha/jso_serialization_test.js
Labels: cla: yes

#5394 Migrate core/utils/global.js to goog.module syntax
  core/utils/global.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5378 fix: insertion markers and change events to work with JSO hooks
  core/events/block_events.js
  core/field.js
  core/insertion_marker_manager.js
  core/mutator.js
  tests/mocha/.eslintrc.json
  tests/mocha/block_change_event_test.js
  tests/mocha/index.html
  tests/mocha/mutator_test.js
  tests/mocha/test_helpers.js
Labels: cla: yes

#5276 feat: adds hooks for serializing plugins
  core/interfaces/i_serializer.js
  core/registry.js
  core/requires.js
  core/serialization/blocks.js
  core/serialization/priorities.js
  core/serialization/registry.js
  core/serialization/variables.js
  core/serialization/workspaces.js
  tests/deps.js
  tests/mocha/jso_deserialization_test.js
  tests/mocha/jso_serialization_test.js
  tests/mocha/registry_test.js
Labels: cla: yes

#5356 fix: remove some attributes from the JSO system
  core/serialization/blocks.js
  tests/mocha/jso_serialization_test.js
  tests/mocha/serializer_test.js
Labels: cla: yes

#5330 feat: add throwing errors for bad shadows
  core/connection.js
  tests/mocha/connection_test.js
Labels: cla: yes

#5405 fix: redo disconnect from shadow bug
  core/connection.js
  core/serialization/blocks.js
  tests/mocha/block_change_event_test.js
  tests/mocha/block_create_event_test.js
  tests/mocha/index.html
Labels: cla: yes

#5207 Migrate dropdown to goog.module syntax
  core/dropdowndiv.js
  tests/deps.js
  tests/mocha/dropdowndiv_test.js
Labels: type: cleanup, cla: yes
