Repository google/blockly, pull requests merged in 2021-07, with the labels that each got.

#5008 Local http server for testing in uncompiled mode
  package-lock.json
  package.json
  tests/playground.html
  tests/playgrounds/advanced_playground.html
Labels: component: devtools, type: internal

#4968 Build in a temporary directory
  .gitignore
  gulpfile.js
  msg/messages.js
  package.json
  scripts/gulpfiles/appengine_tasks.js
  scripts/gulpfiles/build_tasks.js
  scripts/gulpfiles/config.js
  scripts/gulpfiles/git_tasks.js
  scripts/gulpfiles/package_tasks.js
  scripts/gulpfiles/release_tasks.js
  scripts/gulpfiles/typings.js
  tests/run_all_tests.sh
  tests/scripts/check_metadata.sh
  tests/scripts/compile_typings.sh
Labels: component: build process

#5022 Remove undesirable \n from sv.json
  msg/json/sv.json
Labels: component: i18n

#5038 Update package-lock.json to lockfileVersion 2
  package-lock.json
Labels: type: cleanup

#5019 Preparation for goog.module transition: base.js, deps.js
  .eslintignore
  .eslintrc.json
  blockly_uncompressed.js
  blocks/procedures.js
  closure/goog/base.js
  core/contextmenu_items.js
  core/renderers/geras/info.js
  core/renderers/thrasos/info.js
  gulpfile.js
  package.json
  scripts/gulpfiles/build_tasks.js
  tests/deps.js
Labels: component: build process, type: cleanup

#5046 Configure eslint and Closure Compiler to accept ES6
  .eslintrc.json
  scripts/gulpfiles/build_tasks.js
Labels: type: cleanup

#5058 Pull Request template for goog.module PRs
  .github/PULL_REQUEST_TEMPLATE/goog_module.md
Labels: type: internal

#5064 Migrate core/utils/metrics.js to goog.module syntax
  core/utils/metrics.js
  tests/deps.js
Labels: type: cleanup

#5078 Migrate core/connection_types.js to goog.module syntax
  core/connection_types.js
  tests/deps.js
Labels: type: cleanup

#5079 Migrate core/block_animations.js to goog.module syntax
  core/block_animations.js
  tests/deps.js
Labels: type: cleanup

#5047 Migrate core/utils/coordinate.js to goog.module syntax
  core/utils/coordinate.js
  tests/deps.js
Labels: type: cleanup

#5090 Migrate core/interfaces/i_component.js to goog.module syntax
  core/interfaces/i_component.js
  tests/deps.js
Labels: type: cleanup

#5094 Migrate core/interfaces/i_deletable.js to goog.module
  core/interfaces/i_deletable.js
  tests/deps.js
Labels: type: cleanup

#5083 Migrate core/renderers/common/drawer.js to goog.module syntax
  core/renderers/common/drawer.js
  tests/deps.js
Labels: type: cleanup

#5086 Auto-tag and add milestones for cleanup PRs
  .github/workflows/tag_module_cleanup.yml
Labels: type: cleanup

#5104 Migrate core/interfaces/i_movable.js to goog.module
  core/interfaces/i_movable.js
  tests/deps.js
Labels: type: cleanup

#5110 Migrate core/interfaces/i_styleable.js to goog.module
  core/interfaces/i_styleable.js
  tests/deps.js
Labels: type: cleanup

#5106 Migrate core/connection_checker.js to goog.module
  core/connection_checker.js
  tests/deps.js
Labels: type: cleanup

#5081 Migrate core/bubble_dragger.js to goog.module syntax
  core/bubble_dragger.js
  tests/deps.js
Labels: type: cleanup

#5118 Always have npm start serve the repository root
  package.json
Labels: component: devtools, type: bug

#5060 Migrate core/utils/style.js to goog.module syntax
  core/utils/style.js
  tests/deps.js
Labels: type: cleanup

#5109 Migrate core/interfaces/i_selectable.js to goog.module syntax
  core/interfaces/i_selectable.js
  tests/deps.js
Labels: type: cleanup

#5092 Migrate core/interfaces/i_contextmenu.js to goog.module syntax
  core/interfaces/i_contextmenu.js
  tests/deps.js
Labels: type: cleanup

#5121 Migrate core/connection_db.js to goog.module syntax
  core/connection_db.js
  tests/deps.js
Labels: type: cleanup

#5098 Migrate core/comment.js to goog.module syntax
  core/comment.js
  tests/deps.js
Labels: type: cleanup

#5102 Migrate core/connection.js to goog.module syntax
  core/connection.js
  tests/deps.js
Labels: type: cleanup

#5052 Add JSO hooks for blocks and fields.
  core/block.js
  core/extensions.js
  core/field.js
  tests/mocha/extensions_test.js
Labels: api_change

#5076 Migrate core/utils/toolbox.js to goog.module syntax
  core/utils/toolbox.js
  tests/deps.js
  tests/mocha/workspace_svg_test.js
Labels: type: cleanup

#5138 Add script for partially automating goog.module conversion steps
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5108 Migrate core/interfaces/i_registrable.js to goog.module
  core/interfaces/i_registrable.js
  tests/deps.js
Labels: type: cleanup

#5143 Fix edge cases for convert-script
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5107 Migrate core/renderers/common/info.js to goog.module syntax
  core/renderers/common/info.js
  tests/deps.js
Labels: type: cleanup

#5151 Migrate core/drag_target.js to goog.module syntax
  core/drag_target.js
  tests/deps.js
Labels: type: cleanup

#5154 Migrate core/field.js to goog.module syntax
  core/field.js
  tests/deps.js
Labels: type: cleanup

#5147 Migrate core/field_checkbox.js to goog.module syntax
  core/field_checkbox.js
  tests/deps.js
Labels: type: cleanup

#5140 Make constants.js have no side effects
  core/block_svg.js
  core/blockly.js
  core/connection_checker.js
  core/constants.js
  core/contextmenu.js
  core/field_variable.js
  core/flyout_horizontal.js
  core/generator.js
  core/gesture.js
  core/input.js
  core/insertion_marker_manager.js
  core/internal_constants.js
  core/keyboard_nav/ast_node.js
  core/mutator.js
  core/names.js
  core/procedures.js
  core/rendered_connection.js
  core/renderers/common/constants.js
  core/renderers/common/debugger.js
  core/renderers/common/marker_svg.js
  core/renderers/common/renderer.js
  core/renderers/geras/info.js
  core/renderers/zelos/constants.js
  core/renderers/zelos/info.js
  core/renderers/zelos/renderer.js
  core/touch.js
  core/trashcan.js
  core/utils.js
  core/variables.js
  core/workspace_audio.js
  core/workspace_svg.js
  core/xml.js
  core/zoom_controls.js
  tests/deps.js
Labels: type: cleanup

#5157 Remove need for require instead of requireType for Block in ASTNode
  core/keyboard_nav/ast_node.js
Labels: type: cleanup

#5152 Fix double execution in Code demo
  demos/code/code.js
Labels: component: demos, type: bug

#5159 Migrate core/field_colour.js to goog.module syntax
  core/field_colour.js
  tests/deps.js
Labels: type: cleanup

#5145 Migrate core/field_number.js to goog.module syntax
  core/field_number.js
  tests/deps.js
Labels: type: cleanup

#5148 Update goog.module-migrated files to fix style issues
  core/block_animations.js
  core/block_drag_surface.js
  core/bubble_dragger.js
  core/comment.js
  core/component_manager.js
  core/connection.js
  core/connection_checker.js
  core/connection_db.js
  core/css.js
  core/extensions.js
  core/interfaces/i_ast_node_location_svg.js
  core/interfaces/i_ast_node_location_with_block.js
  core/interfaces/i_autohideable.js
  core/interfaces/i_block_dragger.js
  core/interfaces/i_bounded_element.js
  core/interfaces/i_bubble.js
  core/interfaces/i_connection_checker.js
  core/interfaces/i_copyable.js
  core/interfaces/i_delete_area.js
  core/interfaces/i_drag_target.js
  core/interfaces/i_draggable.js
  core/interfaces/i_flyout.js
  core/interfaces/i_keyboard_accessible.js
  core/interfaces/i_positionable.js
  core/interfaces/i_toolbox.js
  core/renderers/common/drawer.js
  core/utils/colour.js
  core/utils/deprecation.js
  core/utils/idgenerator.js
  core/utils/math.js
  core/utils/object.js
  core/utils/style.js
  core/utils/svg_paths.js
  core/utils/toolbox.js
Labels: type: cleanup

#5162 Migrate core/field_dropdown.js to goog.module syntax
  core/field_dropdown.js
  tests/deps.js
Labels: type: cleanup

#5168 Convert files script cleanup
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5175 Fix bug in convert-file script with processing arguments
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5169 Prompt before destructuring properties for a require
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5150 Migrate core/delete_area.js to goog.module syntax
  core/delete_area.js
  tests/deps.js
Labels: type: cleanup

#5178 Migrate core/field_variable.js to goog.module syntax
  core/field_variable.js
  tests/deps.js
Labels: type: cleanup

#5172 Migrate core/field_registry.js to goog.module syntax
  core/field_registry.js
  tests/deps.js
Labels: type: cleanup

#5174 Migrate core/menu.js to goog.module syntax
  core/menu.js
  tests/deps.js
Labels: type: cleanup

#5192 Migrate core/generator.js to goog.module syntax
  core/generator.js
  tests/deps.js
Labels: type: cleanup

#5171 Migrate core/block_dragger.js to goog.module syntax
  core/block_dragger.js
  tests/deps.js
Labels: type: cleanup

#5190 Migrate core/flyout_horizontal.js to goog.module syntax
  core/flyout_horizontal.js
  tests/deps.js
Labels: type: cleanup

#5193 Migrate core/grid.js to goog.module syntax
  core/grid.js
  tests/deps.js
Labels: type: cleanup

#5194 Migrate core/icon.js to goog.module syntax
  core/icon.js
  tests/deps.js
Labels: type: cleanup

#5202 Remove deconstructing properties and update logic
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5195 Migrate core/input.js to goog.module syntax
  core/input.js
  tests/deps.js
Labels: type: cleanup

#5177 Migrate core/field_textinput.js to goog.module syntax
  core/field_textinput.js
  tests/deps.js
Labels: type: cleanup

#5191 Migrate core/flyout_vertical.js to goog.module syntax
  core/flyout_vertical.js
  tests/deps.js
Labels: type: cleanup

#5180 Migrate core/flyout_base.js to goog.module syntax
  core/flyout_base.js
  tests/deps.js
Labels: type: cleanup

#5204 Migrate core/renderers/common/constants.js to goog.module syntax
  core/renderers/common/constants.js
  tests/deps.js
Labels: type: cleanup

#5206 Apply fixes for convert-file script
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5201 Migrate core/marker_manager.js to goog.module syntax
  core/marker_manager.js
  tests/deps.js
Labels: type: cleanup

#5197 Migrate core/utils/size.js to goog.module syntax
  core/utils/size.js
  tests/deps.js
Labels: type: cleanup

#5221 Migrate core/theme_manager.js to goog.module syntax
  core/theme_manager.js
  tests/deps.js
Labels: type: cleanup

#5223 Add comment to top of convert-file script for reference to syntax used
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5203 Migrate core/mutator.js to goog.module syntax
  core/mutator.js
  tests/deps.js
Labels: type: cleanup

#5218 Migrate core/rendered_connection.js to goog.module syntax
  core/rendered_connection.js
  tests/deps.js
Labels: type: cleanup

#5232 Migrate core/renderers/common/path_object.js to goog.module syntax
  core/renderers/common/path_object.js
  tests/deps.js
Labels: type: cleanup

#5235 Fix lint
  core/field_variable.js
  core/gesture.js
  core/zoom_controls.js
  tests/deps.js
Labels: type: cleanup

#5123 Migrate core/keyboard_nav/marker.js to goog.module syntax
  core/keyboard_nav/marker.js
  tests/deps.js
Labels: type: cleanup

#5239 Fix usage instructions for convert-file.sh
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5241 Add handling for converting modules that are not leaf nodes
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5217 Migrate core/registry.js to goog.module syntax
  core/registry.js
  tests/deps.js
Labels: type: cleanup

#5075 Migrate core/utils/dom.js to goog.module syntax
  core/utils/dom.js
  tests/deps.js
Labels: type: cleanup

#5251 Add regex lookarounds to check for require overlaps
  scripts/goog_module/convert-file.sh
Labels: type: cleanup

#5236 Migrate core/toolbox/collapsible_category.js to goog.module syntax
  core/toolbox/collapsible_category.js
  tests/deps.js
Labels: type: cleanup

#5182 Migrate core/flyout_button.js to goog.module syntax
  core/flyout_button.js
  tests/deps.js
Labels: type: cleanup

#5248 Migrate core/variable_model.js to goog.module syntax
  core/variable_model.js
  tests/deps.js
Labels: type: cleanup

#5220 Migrate core/theme.js to goog.module syntax
  core/theme.js
  tests/deps.js
Labels: type: cleanup

#5256 Fix eslint warning in core/utils/dom.js
  core/utils/dom.js
  tests/deps.js
Labels: type: cleanup

#5237 Move clipboard functions to a separate namespace
  core/blockly.js
  core/clipboard.js
  core/contextmenu_items.js
  core/shortcut_items.js
  tests/deps.js
  tests/mocha/contextmenu_items_test.js
  tests/mocha/keydown_test.js
Labels: type: cleanup

#5244 Move main workspace to a new file, common.js
  core/blockly.js
  core/common.js
  core/dropdowndiv.js
  core/generator.js
  core/gesture.js
  core/inject.js
  core/widgetdiv.js
  core/workspace_svg.js
  tests/deps.js
Labels: type: cleanup

#5247 Migrate core/variable_map.js to goog.module syntax
  core/variable_map.js
  tests/deps.js
Labels: type: cleanup

#5261 Migrate core/variables_dynamic.js to goog.module syntax
  core/variables_dynamic.js
  tests/deps.js
Labels: type: cleanup

#5257 Migrate core/trashcan.js to goog.module syntax
  core/trashcan.js
  tests/deps.js
Labels: type: cleanup

#5264 Add missing eslint disable to core/renderers/common/i_path_object.js
  core/renderers/common/i_path_object.js
Labels: type: cleanup

#5252 Migrate core/scrollbar.js to goog.module syntax
  core/scrollbar.js
  core/scrollbar_pair.js
  tests/deps.js
Labels: type: cleanup

#5266 Remove extra eslint disable from core/gesture.js
  core/gesture.js
Labels: type: cleanup
