Repository google/blockly, pull requests merged in 2021-09, with the labels that each got.

#5419 Allow command key zoom on mac devices
  core/workspace_svg.js
Labels: cla: yes

#5392 feat: add support for defining toolboxes using pure json
  core/flyout_base.js
  core/serialization/blocks.js
  core/utils/toolbox.js
  core/workspace_svg.js
  tests/deps.js
  tests/mocha/.eslintrc.json
  tests/mocha/flyout_test.js
  tests/mocha/index.html
  tests/mocha/toolbox_helper.js
  tests/mocha/toolbox_test.js
  tests/playground.html
Labels: api_change, cla: yes

#5426 Create `scripts/migration/renamings.js` to collect information about renamed API entries
  scripts/migration/renamings.js
Labels: type: documentation, type: cleanup, cla: yes

#5420 Use Blockly.utils.arrayRemove
  core/component_manager.js
  core/theme_manager.js
  core/utils.js
  core/variable_map.js
  core/workspace.js
Labels: type: cleanup, cla: yes

#5424 fix: serializing edited shadows
  core/serialization/blocks.js
  tests/mocha/jso_serialization_test.js
Labels: cla: yes

#5427 fix: add missing requires for `Blockly.util.object` and `Blockly.util.Size`
  core/flyout_base.js
  core/renderers/common/constants.js
  core/toolbox/toolbox.js
  core/trashcan.js
  core/zoom_controls.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5421 fix: cereal backwards compatibility
  core/field.js
  core/field_angle.js
  core/field_checkbox.js
  core/field_colour.js
  core/field_dropdown.js
  core/field_label_serializable.js
  core/field_multilineinput.js
  core/field_number.js
  core/field_textinput.js
  core/field_variable.js
  core/serialization/blocks.js
  tests/mocha/field_test.js
  tests/mocha/jso_deserialization_test.js
  tests/mocha/jso_serialization_test.js
Labels: cla: yes

#5423 fix: copy paste with json system
  core/block_svg.js
  core/blockly.js
  core/interfaces/i_copyable.js
  core/workspace_comment_svg.js
  core/workspace_svg.js
Labels: cla: yes

#5422 fix: dragging blocks from the flyout that only have XML hooks
  core/flyout_base.js
  core/serialization/blocks.js
  tests/playground.html
Labels: cla: yes

#5435 Migrate core/utils/useragent.js to goog.module syntax
  core/utils/useragent.js
  tests/deps.js
Labels: type: cleanup

#5442 Note behavior of centerOnBlock when block is part of a stack in the JSDoc
  core/workspace_svg.js
Labels: cla: yes

#5433 fix: loading blocks in RTL
  core/serialization/blocks.js
Labels: cla: yes

#5441 Rename `Blockly.utils.IdGenerator` to `idGenerator` and move `Blockly.utils.genUid` to there
  core/block.js
  core/contextmenu_items.js
  core/events/events.js
  core/field_colour.js
  core/flyout_base.js
  core/menuitem.js
  core/options.js
  core/toolbox/toolbox_item.js
  core/utils.js
  core/utils/idgenerator.js
  core/variable_map.js
  core/variable_model.js
  core/workspace.js
  core/workspace_comment.js
  package.json
  scripts/migration/renamings.js
  tests/deps.js
  tests/mocha/test_helpers.js
  tests/mocha/utils_test.js
Labels: type: cleanup, cla: yes

#5446 Migrate core/utils.js to goog.module syntax
  core/rendered_connection.js
  core/toolbox/category.js
  core/toolbox/toolbox.js
  core/utils.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5430 maxInstance fix
  core/workspace.js
Labels: cla: yes

#5222 Migrate core/tooltip.js to goog.module syntax
  core/tooltip.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5425 fix: create and delete events, and the trashcan
  core/events/block_events.js
  core/trashcan.js
  tests/mocha/event_test.js
  tests/mocha/jso_deserialization_test.js
  tests/mocha/test_helpers.js
  tests/mocha/trashcan_test.js
Labels: cla: yes

#5449 Migrate core/touch_gesture.js to goog.module syntax
  core/touch_gesture.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5444 fix: update code demo to include JSON
  demos/code/code.js
  demos/code/index.html
  demos/code/msg/ar.js
  demos/code/msg/be-tarask.js
  demos/code/msg/br.js
  demos/code/msg/ca.js
  demos/code/msg/cs.js
  demos/code/msg/da.js
  demos/code/msg/de.js
  demos/code/msg/el.js
  demos/code/msg/en.js
  demos/code/msg/es.js
  demos/code/msg/et.js
  demos/code/msg/fa.js
  demos/code/msg/fr.js
  demos/code/msg/he.js
  demos/code/msg/hrx.js
  demos/code/msg/hu.js
  demos/code/msg/ia.js
  demos/code/msg/is.js
  demos/code/msg/it.js
  demos/code/msg/ja.js
  demos/code/msg/kab.js
  demos/code/msg/ko.js
  demos/code/msg/mk.js
  demos/code/msg/ms.js
  demos/code/msg/nb.js
  demos/code/msg/nl.js
  demos/code/msg/oc.js
  demos/code/msg/pl.js
  demos/code/msg/pms.js
  demos/code/msg/pt-br.js
  demos/code/msg/ro.js
  demos/code/msg/ru.js
  demos/code/msg/sc.js
  demos/code/msg/sk.js
  demos/code/msg/sr.js
  demos/code/msg/sv.js
  demos/code/msg/ta.js
  demos/code/msg/th.js
  demos/code/msg/tlh.js
  demos/code/msg/tr.js
  demos/code/msg/uk.js
  demos/code/msg/vi.js
  demos/code/msg/zh-hans.js
  demos/code/msg/zh-hant.js
Labels: cla: yes

#5434 fix: dragging variables from flyout
  core/block.js
  core/field.js
  core/field_variable.js
  core/flyout_base.js
  core/serialization/blocks.js
  tests/mocha/field_variable_test.js
  tests/mocha/jso_serialization_test.js
Labels: cla: yes

#5448 Migrate core/msg.js to goog.module syntax
  core/msg.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5398 fix: project cereal cleanup
  core/block_svg.js
  core/connection.js
  core/events/block_events.js
  core/flyout_base.js
  core/interfaces/i_serializer.js
  core/registry.js
  core/serialization/blocks.js
  core/serialization/exceptions.js
  core/serialization/variables.js
  core/utils/toolbox.js
  core/workspace_svg.js
  tests/mocha/block_create_event_test.js
  tests/mocha/connection_test.js
  tests/mocha/field_variable_test.js
  tests/mocha/jso_deserialization_test.js
Labels: cla: yes

#5452 Revert inadvertently reverted change to `test/deps.js`
  tests/deps.js
Labels: type: cleanup, cla: yes

#5451 Migrate `core/global.js` to named exports
  core/browser_events.js
  core/msg.js
  core/touch.js
  core/utils.js
  core/utils/global.js
  core/utils/useragent.js
  core/workspace_audio.js
  generators/javascript.js
  scripts/migration/renamings.js
  scripts/package/node/core.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5459 Migrate core/utils/xml.js to goog.module syntax
  core/utils/xml.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5457 Move alert/confirm/prompt to a new file, dialog.js
  core/blockly.js
  core/contextmenu_items.js
  core/dialog.js
  core/field_textinput.js
  core/variable_map.js
  core/variables.js
  demos/code/code.js
  demos/custom-dialogs/custom-dialog.js
  demos/custom-fields/pitch/field_pitch.js
  tests/deps.js
  tests/mocha/contextmenu_items_test.js
  tests/mocha/workspace_test.js
Labels: type: cleanup, cla: yes

#5453 Move bump objects function into a separate module
  core/block_dragger.js
  core/bump_objects.js
  core/inject.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5461 Don't monkey-patch `Blocky.utils.xml.document` in node module
  core/utils/xml.js
  scripts/migration/renamings.js
  scripts/package/node/core.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5462 Migrate Blockly.hueToHex to Blockly.utils.colour.hueToHex
  core/blockly.js
  core/toolbox/category.js
  core/utils/colour.js
  demos/blockfactory/workspacefactory/wfactory_controller.js
  demos/blockfactory/workspacefactory/wfactory_init.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5456 Migrate core/inject.js to goog_module syntax
  core/bump_objects.js
  core/inject.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5467 test: Changes mocha tests to use node_modules instead of unpkg
  tests/mocha/index.html
Labels: type: cleanup, cla: yes

#5471 fix: adds a fix for npm install failing
  .github/workflows/build.yml
  package-lock.json
Labels: type: cleanup, cla: yes

#5460 Migrate hideChaff() from Blockly to WorkspaceSvg
  core/blockly.js
  core/bubble.js
  core/flyout_base.js
  core/gesture.js
  core/inject.js
  core/interfaces/i_autohideable.js
  core/scrollbar.js
  core/shortcut_items.js
  core/theme_manager.js
  core/toolbox/toolbox.js
  core/trashcan.js
  core/workspace_comment_svg.js
  core/workspace_svg.js
  demos/blockfactory/app_controller.js
  demos/blockfactory/factory.js
  demos/blockfactory_old/factory.js
  demos/custom-fields/turtle/index.html
  tests/deps.js
  tests/mocha/keydown_test.js
  tests/mocha/toolbox_test.js
Labels: type: cleanup, cla: yes

#5474 Remove unused require of `Blockly` in `Blockly.ToolboxCategory`
  core/toolbox/category.js
  tests/deps.js
Labels: type: cleanup, cla: yes

#5465 Re-export `Blockly.utils.*` submodules from `Blockly.utils`
  core/utils.js
  core/utils/aria.js
  core/utils/colour.js
  core/utils/coordinate.js
  core/utils/deprecation.js
  core/utils/dom.js
  core/utils/global.js
  core/utils/idgenerator.js
  core/utils/keycodes.js
  core/utils/math.js
  core/utils/metrics.js
  core/utils/object.js
  core/utils/rect.js
  core/utils/size.js
  core/utils/string.js
  core/utils/style.js
  core/utils/svg.js
  core/utils/svg_paths.js
  core/utils/toolbox.js
  core/utils/useragent.js
  core/utils/xml.js
  package-lock.json
  package.json
  tests/deps.js
  tests/scripts/check_metadata.sh
Labels: type: cleanup, cla: yes

#5475 Note Blockly.alert/confirm/prompt/hueToHex/hideChaff migrations in renamings.js
  scripts/migration/renamings.js
Labels: type: cleanup, cla: yes

#5476 refactor: Migrate Blockly.onKeyDown out of blockly.js
  core/blockly.js
  core/inject.js
  tests/deps.js
  tests/deps.mocha.js
  tests/mocha/keydown_test.js
  tests/mocha/shortcut_registry_test.js
  tests/mocha/test_helpers.js
Labels: type: cleanup, cla: yes

#5480 refactor: remove unused Blockly.onContextMenu_
  core/blockly.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5483 refactor: move Blockly.deleteBlock out of blockly.js
  core/block_svg.js
  core/blockly.js
  core/contextmenu_items.js
  core/shortcut_items.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5485 refactor: Move Blockly.svgResize to Blockly.common
  core/blockly.js
  core/common.js
  core/inject.js
  core/toolbox/toolbox.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5454 chore: sets polyfill flag to true
  scripts/gulpfiles/build_tasks.js
Labels: type: cleanup, cla: yes

#5488 Clean up get/set accessor definitions
  core/contextmenu.js
  core/generator.js
  scripts/migration/renamings.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5489 Migrate selected from Blockly to Blockly.common
  core/block.js
  core/block_svg.js
  core/blockly.js
  core/common.js
  core/gesture.js
  core/insertion_marker_manager.js
  core/rendered_connection.js
  core/shortcut_items.js
  core/workspace_comment_svg.js
  core/workspace_dragger.js
  demos/blockfactory/workspacefactory/wfactory_controller.js
  demos/blockfactory/workspacefactory/wfactory_init.js
  scripts/migration/renamings.js
  tests/deps.js
  tests/deps.mocha.js
  tests/mocha/keydown_test.js
  tests/mocha/run_mocha_tests_in_browser.js
Labels: type: cleanup, cla: yes

#5496 chore: remove support for node 10
  .github/workflows/build.yml
Labels: cla: yes

#5494 Migrate core/blockly.js to goog.module syntax
  core/blockly.js
  tests/deps.js
  tests/deps.mocha.js
  tests/mocha/contextmenu_items_test.js
  tests/mocha/field_textinput_test.js
  tests/mocha/workspace_helpers.js
Labels: type: cleanup, cla: yes

#5464 Move browser event utils from utils.js to browser_events.js
  core/browser_events.js
  core/bubble.js
  core/contextmenu.js
  core/flyout_horizontal.js
  core/flyout_vertical.js
  core/gesture.js
  core/icon.js
  core/inject.js
  core/scrollbar.js
  core/toolbox/toolbox.js
  core/touch_gesture.js
  core/utils.js
  core/workspace_comment_svg.js
  core/workspace_svg.js
  scripts/migration/renamings.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5498 chore: disables caching when running the playground
  package.json
Labels: cla: yes

#5499 fix: Prevent request of (non-existent) closure/goog/deps.js
  blockly_uncompressed.js
Labels: type: bug, type: cleanup, cla: yes

#5479 Make several exported private fields/methods TEST_ONLY
  core/events/events.js
  core/extensions.js
  core/registry.js
  tests/mocha/block_test.js
  tests/mocha/extensions_test.js
  tests/mocha/field_registry_test.js
  tests/mocha/logic_ternary_test.js
  tests/mocha/test_helpers.js
  tests/mocha/theme_test.js
Labels: type: cleanup, cla: yes

#5510 fix: enable missingRequire in build_tasks
  core/common.js
  core/interfaces/i_selectable.js
  core/serialization/exceptions.js
  core/toolbox/category.js
  core/zoom_controls.js
  scripts/gulpfiles/build_tasks.js
Labels: type: cleanup, cla: yes

#5511 chore: Remove declareLegacyNamespace from block-related files
  core/block.js
  core/block_animations.js
  core/block_drag_surface.js
  core/block_dragger.js
  core/block_svg.js
  core/blockly.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5513 Remove legacy keyboard nav
  core/blockly.js
  core/keyboard_nav/ast_node.js
  core/keyboard_nav/basic_cursor.js
  core/keyboard_nav/cursor.js
  core/keyboard_nav/marker.js
  core/keyboard_nav/tab_navigate_cursor.js
  tests/mocha/astnode_test.js
  tests/mocha/cursor_test.js
  tests/mocha/event_test.js
Labels: type: cleanup, cla: yes

#5517 Keyboard nav names
  core/block.js
  core/block_svg.js
  core/blockly.js
  core/events/events_marker_move.js
  core/keyboard_nav/ast_node.js
  core/keyboard_nav/basic_cursor.js
  core/keyboard_nav/cursor.js
  core/keyboard_nav/marker.js
  core/keyboard_nav/tab_navigate_cursor.js
  core/marker_manager.js
  core/registry.js
  core/renderers/common/marker_svg.js
  core/renderers/common/renderer.js
  core/renderers/zelos/marker_svg.js
  core/renderers/zelos/renderer.js
  core/workspace_svg.js
  tests/deps.js
  tests/deps.mocha.js
  tests/mocha/astnode_test.js
  tests/mocha/cursor_test.js
  tests/mocha/event_test.js
Labels: type: cleanup, cla: yes

#5516 chore: update dev tools dev dependency
  package-lock.json
  package.json
Labels: type: cleanup, cla: yes

#5519 fix: JSDoc generation for modules without classes
  core/blockly.js
  core/css.js
  core/events/events.js
  core/extensions.js
  core/procedures.js
  core/serialization/priorities.js
  core/tooltip.js
  core/utils.js
  core/utils/aria.js
  core/utils/colour.js
  core/utils/deprecation.js
  core/utils/dom.js
  core/utils/idgenerator.js
  core/utils/keycodes.js
  core/utils/math.js
  core/utils/object.js
  core/utils/string.js
  core/utils/style.js
  core/utils/svg_paths.js
  core/utils/toolbox.js
  core/utils/useragent.js
  core/utils/xml.js
  core/variables.js
  core/widgetdiv.js
Labels: type: cleanup, cla: yes

#5495 fix: Updates the release task to build typings for msgs
  scripts/gulpfiles/release_tasks.js
Labels: cla: yes

#5521 Migrate core/field_angle.js to to goog.module syntax
  core/field_angle.js
  tests/deps.js
  tests/deps.mocha.js
  tests/mocha/test_helpers.js
Labels: type: cleanup, cla: yes

#5523 chore: Remove declareLegacyNamespace() from toolbox/* files
  core/blockly.js
  core/toolbox/category.js
  core/toolbox/collapsible_category.js
  core/toolbox/separator.js
  core/toolbox/toolbox.js
  core/toolbox/toolbox_item.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5522 chore: Remove declareLegacyNamespace() from field_* files
  core/blockly.js
  core/events/events_block_change.js
  core/field.js
  core/field_checkbox.js
  core/field_colour.js
  core/field_dropdown.js
  core/field_image.js
  core/field_label.js
  core/field_label_serializable.js
  core/field_multilineinput.js
  core/field_number.js
  core/field_registry.js
  core/field_textinput.js
  core/field_variable.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5524 chore: Remove declareLegacyNamespace() from Blockly.Themes files
  core/blockly.js
  core/theme/classic.js
  core/theme/themes.js
  core/theme/zelos.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5407 refactor: Rename Blockly.connectionTypes to Blockly.ConnectionType
  core/block.js
  core/block_svg.js
  core/blockly.js
  core/connection.js
  core/connection_checker.js
  core/connection_db.js
  core/connection_type.js
  core/events/events_block_move.js
  core/input_types.js
  core/insertion_marker_manager.js
  core/internal_constants.js
  core/keyboard_nav/ast_node.js
  core/rendered_connection.js
  core/renderers/common/constants.js
  core/renderers/common/debugger.js
  core/renderers/common/marker_svg.js
  core/renderers/common/renderer.js
  core/renderers/zelos/constants.js
  core/renderers/zelos/renderer.js
  scripts/migration/renamings.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5531 Fix typo in Blockly.serialization.blocks
  core/serialization/blocks.js
Labels: type: cleanup, cla: yes

#5526 chore: Remove declareLegacyNamespace() from files under interfaces/*
  core/blockly.js
  core/interfaces/i_ast_node_location.js
  core/interfaces/i_ast_node_location_svg.js
  core/interfaces/i_ast_node_location_with_block.js
  core/interfaces/i_autohideable.js
  core/interfaces/i_block_dragger.js
  core/interfaces/i_bounded_element.js
  core/interfaces/i_bubble.js
  core/interfaces/i_collapsible_toolbox_item.js
  core/interfaces/i_component.js
  core/interfaces/i_connection_checker.js
  core/interfaces/i_contextmenu.js
  core/interfaces/i_copyable.js
  core/interfaces/i_deletable.js
  core/interfaces/i_delete_area.js
  core/interfaces/i_drag_target.js
  core/interfaces/i_draggable.js
  core/interfaces/i_flyout.js
  core/interfaces/i_keyboard_accessible.js
  core/interfaces/i_metrics_manager.js
  core/interfaces/i_movable.js
  core/interfaces/i_positionable.js
  core/interfaces/i_registrable.js
  core/interfaces/i_registrable_field.js
  core/interfaces/i_selectable.js
  core/interfaces/i_selectable_toolbox_item.js
  core/interfaces/i_styleable.js
  core/interfaces/i_toolbox.js
  core/interfaces/i_toolbox_item.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5533 refactor: Migrate `Blockly.ConnectionType` to named exports
  core/block.js
  core/block_svg.js
  core/blockly.js
  core/connection.js
  core/connection_checker.js
  core/connection_db.js
  core/connection_type.js
  core/events/events_block_move.js
  core/input_types.js
  core/insertion_marker_manager.js
  core/internal_constants.js
  core/keyboard_nav/ast_node.js
  core/rendered_connection.js
  core/renderers/common/constants.js
  core/renderers/common/debugger.js
  core/renderers/common/marker_svg.js
  core/renderers/common/renderer.js
  core/renderers/zelos/constants.js
  core/renderers/zelos/renderer.js
  scripts/migration/renamings.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5534 Reexport `global.globalThis` this as `Blockly.utils.global`
  core/utils.js
  scripts/migration/renamings.js
  scripts/package/node/core.js
Labels: type: cleanup, cla: yes

#5515 refactor: Rename `Blockly.Blocks`, migrate to named exports
  blocks/colour.js
  blocks/lists.js
  blocks/logic.js
  blocks/loops.js
  blocks/math.js
  blocks/procedures.js
  blocks/text.js
  blocks/variables.js
  blocks/variables_dynamic.js
  core/block.js
  core/blockly.js
  core/blocks.js
  core/procedures.js
  core/variables.js
  core/variables_dynamic.js
  externs/block-externs.js
  scripts/migration/renamings.js
  tests/deps.js
  tests/deps.mocha.js
  tests/mocha/block_test.js
  tests/mocha/procedures_test.js
  tests/mocha/test_helpers.js
Labels: type: cleanup, cla: yes

#5529 Fix typo in alias
  core/widgetdiv.js
Labels: type: cleanup, cla: yes

#5536 fix: Add hack to copy accessors to global Blockly namespace object
  core/blockly.js
Labels: type: cleanup, cla: yes

#5548 fix: blocks dragged from RTL flyout being incorrectly positioned
  core/flyout_base.js
Labels: cla: yes

#5549 fix: infinite loop when using defineProperties
  core/events/events.js
  core/tooltip.js
  core/widgetdiv.js
  tests/deps.js
  tests/deps.mocha.js
Labels: cla: yes

#5559 Add missing @alias annotations
  core/blockly.js
Labels: cla: yes

#5551 Add JSDoc to theme classes.
  core/theme/classic.js
  core/theme/zelos.js
Labels: cla: yes

#5561 Add missing alias annotations
  core/interfaces/i_registrable_field.js
  core/positionable_helpers.js
Labels: cla: yes

#5567 JSDoc improvments for accessors, etc.
  core/blockly.js
  core/contextmenu.js
  core/events/events.js
  core/events/utils.js
  core/generator.js
  core/renderers/common/block_rendering.js
  core/renderers/common/debug.js
  core/tooltip.js
  core/widgetdiv.js
Labels: type: documentation, cla: yes

#5568 fix: Use `goog.require` instead of `goog.requireType` for interfaces when necessary
  core/block.js
  core/block_dragger.js
  core/block_svg.js
  core/bubble.js
  core/connection.js
  core/connection_checker.js
  core/delete_area.js
  core/drag_target.js
  core/field.js
  core/flyout_base.js
  core/interfaces/i_ast_node_location_svg.js
  core/interfaces/i_ast_node_location_with_block.js
  core/interfaces/i_autohideable.js
  core/interfaces/i_bubble.js
  core/interfaces/i_collapsible_toolbox_item.js
  core/interfaces/i_copyable.js
  core/interfaces/i_delete_area.js
  core/interfaces/i_drag_target.js
  core/interfaces/i_draggable.js
  core/interfaces/i_flyout.js
  core/interfaces/i_positionable.js
  core/interfaces/i_selectable.js
  core/interfaces/i_selectable_toolbox_item.js
  core/interfaces/i_toolbox.js
  core/metrics_manager.js
  core/renderers/common/path_object.js
  core/renderers/common/renderer.js
  core/toolbox/category.js
  core/toolbox/collapsible_category.js
  core/toolbox/toolbox.js
  core/toolbox/toolbox_item.js
  core/trashcan.js
  core/workspace.js
  core/workspace_comment_svg.js
  core/workspace_svg.js
  core/zoom_controls.js
  tests/deps.js
  tests/deps.mocha.js
Labels: type: cleanup, cla: yes

#5569 fix: Fix JS Spaghetti button.
  tests/playground.html
Labels: cla: yes

#5560 fix: RTL copy-paste and duplicate
  core/workspace_svg.js
Labels: cla: yes

#5571 fix: Fix Block Factory preview workspace
  demos/blockfactory/factory.js
Labels: type: bug, component: demos, cla: yes
