Repository google/blockly, pull requests merged in 2021-12, with the labels that each got.

#5751 fix: procedure callers now remove inputs properly
  blocks/procedures.js
Labels: cla: yes

#5754 refactor: convert generators/javascript/procedures.js to goog.module
  generators/javascript/procedures.js
  tests/deps.js
Labels: cla: yes

#5756 refactor: convert some js block generators to goog.module
  generators/javascript/colour.js
  generators/javascript/lists.js
  generators/javascript/logic.js
  generators/javascript/math.js
  tests/deps.js
Labels: cla: yes

#5758 refactor: convert generators/javascript/loops.js to goog.module
  generators/javascript/loops.js
  tests/deps.js
Labels: cla: yes

#5762 refactor: convert some block generators to goog.module
  generators/dart/colour.js
  generators/dart/lists.js
  generators/dart/logic.js
  generators/dart/loops.js
  generators/dart/math.js
  generators/dart/procedures.js
  generators/dart/text.js
  generators/dart/variables.js
  generators/dart/variables_dynamic.js
  generators/javascript.js
  tests/deps.js
Labels: cla: yes

#5765 refactor: Migrate `blocks/math.js` to `goog.module` syntax
  blocks/math.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: component: library blocks, cla: yes, PR: chore

#5769 refactor: convert some block generators to goog.module
  generators/lua/colour.js
  generators/lua/lists.js
  generators/lua/logic.js
  generators/lua/loops.js
  generators/lua/math.js
  generators/lua/procedures.js
  generators/lua/text.js
  generators/lua/variables.js
  generators/lua/variables_dynamic.js
  tests/deps.js
Labels: cla: yes, PR: chore

#5770 refactor: convert some block generators to goog.module
  generators/lua.js
  generators/php.js
  generators/php/colour.js
  generators/php/lists.js
  generators/php/logic.js
  generators/php/loops.js
  generators/php/math.js
  generators/php/procedures.js
  generators/php/text.js
  generators/php/variables.js
  generators/php/variables_dynamic.js
  tests/deps.js
Labels: cla: yes, PR: chore

#5771 refactor: convert python block generators to goog.module
  generators/dart.js
  generators/javascript.js
  generators/lua.js
  generators/php.js
  generators/python.js
  generators/python/colour.js
  generators/python/lists.js
  generators/python/logic.js
  generators/python/loops.js
  generators/python/math.js
  generators/python/procedures.js
  generators/python/text.js
  generators/python/variables.js
  generators/python/variables_dynamic.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: cla: yes, PR: chore

#5766 refactor: Migrate `blocks/text.js` to `goog.module` syntax
  blocks/text.js
  tests/deps.js
Labels: component: library blocks, cla: yes, PR: chore

#5767 chore: sets the compiled flag to true
  core/blockly.js
  scripts/gulpfiles/build_tasks.js
Labels: cla: yes

#5768 refactor: `core/msg.js`: use named export, remove `declareLegacyNamespace`
  blocks/lists.js
  blocks/logic.js
  blocks/loops.js
  blocks/procedures.js
  blocks/text.js
  core/block_svg.js
  core/blockly.js
  core/contextmenu.js
  core/contextmenu_items.js
  core/field_textinput.js
  core/field_variable.js
  core/inject.js
  core/msg.js
  core/names.js
  core/procedures.js
  core/utils/parsing.js
  core/variable_map.js
  core/variables.js
  core/variables_dynamic.js
  scripts/gulpfiles/chunks.json
  scripts/migration/renamings.js
  tests/deps.js
Labels: cla: yes, PR: chore

#5757 Remove declare legacy serialization
  core/blockly.js
  core/interfaces/i_serializer.js
  core/serialization/blocks.js
  core/serialization/exceptions.js
  core/serialization/priorities.js
  core/serialization/registry.js
  core/serialization/variables.js
  core/serialization/workspaces.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: cla: yes

#5772 feat: make checkAndDelete a public API
  core/block_svg.js
Labels: cla: yes

#5775 Fix advanced playground
  tests/playgrounds/advanced_playground.html
Labels: cla: yes

#5778 chore: updates the names for parsing
  core/utils.js
  core/utils/parsing.js
Labels: cla: yes

#5777 chore: Simplify NPM package wrappers, improve chunk wrapper generator
  scripts/gulpfiles/build_tasks.js
  scripts/gulpfiles/package_tasks.js
  scripts/package/blockly.js
  scripts/package/blocks.js
  scripts/package/browser/core.js
  scripts/package/browser/index.js
  scripts/package/dart.js
  scripts/package/index.js
  scripts/package/javascript.js
  scripts/package/lua.js
  scripts/package/node/core.js
  scripts/package/node/index.js
  scripts/package/php.js
  scripts/package/python.js
Labels: component: build process, cla: yes, PR: chore

#5713 deprecate!: removes deprecated connection functions
  core/connection.js
  core/rendered_connection.js
  tests/deps.js
  tests/mocha/connection_test.js
Labels: cla: yes

#5779 refactor: Migrate `blocks/variables_dynamic.js` to `goog.module` syntax
  blocks/variables_dynamic.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: component: library blocks, cla: yes, PR: chore

#5780 chore: Fix inadvertent block migration inconsistencies
  blocks/colour.js
  blocks/lists.js
  blocks/logic.js
  blocks/math.js
  blocks/procedures.js
  tests/deps.js
Labels: component: library blocks, cla: yes, PR: chore

#5781 fix(tests): Fix & reenable the advanced compilation test
  core/blockly.js
  tests/compile/main.js
  tests/compile/test_blocks.js
  tests/run_all_tests.sh
Labels: component: tests, cla: yes, PR: chore

#5782 chore(test): Add playground that uses compressed files
  tests/playgrounds/compressed.html
Labels: cla: yes

#5776 chore(deps): remove dependency on typescript-closure-tools
  gulpfile.js
  package-lock.json
  package.json
  scripts/gulpfiles/package_tasks.js
  scripts/gulpfiles/release_tasks.js
  scripts/gulpfiles/typings.js
  tests/run_all_tests.sh
Labels: PR: dependencies, cla: yes, PR: chore

#5785 chore(test): add version of multi_playground with compressed files
  tests/playgrounds/multi_compressed.html
Labels: cla: yes

#5718 chore: Remove `core/requires.js`
  blockly_uncompressed.js
  core/requires.js
  scripts/gulpfiles/build_tasks.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
Labels: cla: yes, PR: chore

#5792 release: merge master into develop
  .github/PULL_REQUEST_TEMPLATE/goog_module.md
  .github/dependabot.yml
  .github/release.yml
  blockly_compressed.js.map
  msg/json/qqq.json
Labels: PR: release

#5797 fix: multi-playground should use goog.require to get blocks
  tests/multi_playground.html
Labels: PR: fix

#5555 chore!: Add deprecation notices to values in blockly.js
  core/blockly.js
  core/common.js
  tests/deps.mocha.js
  tests/mocha/block_json_test.js
  tests/mocha/block_test.js
  tests/mocha/connection_checker_test.js
  tests/mocha/connection_db_test.js
  tests/mocha/procedures_test_helpers.js
  tests/mocha/toolbox_test.js
Labels: breaking change, cla: yes, PR: chore

#5806 release: rebuild for 7.20211209.0 release
  blockly_compressed.js
  blockly_compressed.js.map
  blocks_compressed.js
  blocks_compressed.js.map
  dart_compressed.js
  dart_compressed.js.map
  javascript_compressed.js
  javascript_compressed.js.map
  lua_compressed.js
  lua_compressed.js.map
  package-lock.json
  package.json
  php_compressed.js
  php_compressed.js.map
  python_compressed.js
  python_compressed.js.map
Labels: PR: release

#5809 release: Merge master into develop 7.20211209.0
  package-lock.json
Labels: PR: release

#5794 chore(deps): Remove dependency on `babel-eslint`; simplify eslintrc for mocha tests
  package-lock.json
  package.json
  tests/mocha/.eslintrc.json
Labels: component: build process, PR: chore

#5821 fix: re-expose HSV_VALUE and HSV_SATURATION as settable properties on Blockly
  core/blockly.js
  core/internal_constants.js
  core/utils/colour.js
  core/utils/parsing.js
Labels: type: regression, PR: fix

#5823 chore: update the dev-tools version
  package-lock.json
  package.json
Labels: PR: dependencies, PR: chore

#5827 chore: clean up issue templates and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/goog_module.md
Labels: PR: chore

#5722 fix: change getCandidate_ and showInsertionMarker_ to be more dynamic
  core/insertion_marker_manager.js
Labels: cla: yes
