Repository google/blockly, pull requests merged in 2021-04, with the labels that each got.

#4763 Update Flyout metrics and implement adjustable margin for scrollbars.
  core/flyout_base.js
  core/metrics_manager.js
  core/scrollbar.js
Labels: api_change

#4779 Remove compile.sh
  tests/compile/compile.sh
  tests/compile/index.html
  tests/run_all_tests.sh
Labels: api_change, component: tests, type: cleanup

#4780 Remove rules forbidding es6
  .eslintrc.json
  core/utils/object.js
  package.json
Labels: type: internal

#4676 Fix missing require - constructors
  core/blockly.js
  core/events/block_events.js
  core/mutator.js
  core/renderers/common/info.js
  core/toolbox/toolbox.js
  core/trashcan.js
  core/zoom_controls.js
Labels: type: cleanup

#4697 Remove dark theme in favour of @blockly/theme-dark
  blockly_uncompressed.js
  core/requires.js
  core/theme/dark.js
  core/theme/modern.js
  package.json
  scripts/gulpfiles/appengine_tasks.js
  tests/playgrounds/advanced_playground.html
Labels: api_change

#4793 Fix multiple strict require warnings
  core/block.js
  core/block_svg.js
  core/blockly.js
  core/browser_events.js
  core/bubble.js
  core/connection.js
  core/field.js
  core/field_angle.js
  core/field_dropdown.js
  core/field_multilineinput.js
  core/field_textinput.js
  core/flyout_base.js
  core/flyout_button.js
  core/flyout_horizontal.js
  core/flyout_vertical.js
  core/gesture.js
  core/inject.js
  core/interfaces/i_bubble.js
  core/toolbox/category.js
  core/toolbox/collapsible_category.js
  core/toolbox/separator.js
  core/toolbox/toolbox.js
  core/toolbox/toolbox_item.js
  core/trashcan.js
  core/workspace.js
  core/workspace_svg.js
Labels: type: cleanup
