Repository google/blockly, pull requests merged in 2021-10, with the labels that each got.

#5573 chore: rebuild for release
  blockly_compressed.js
  blockly_compressed.js.map
  blocks_compressed.js
  blocks_compressed.js.map
  dart_compressed.js.map
  javascript_compressed.js
  javascript_compressed.js.map
  lua_compressed.js
  lua_compressed.js.map
  package-lock.json
  package.json
  php_compressed.js
  php_compressed.js.map
  python_compressed.js.map
  typings/blockly.d.ts
Labels: cla: yes

#5589 chore: Run clang-format on core/*.js
  core/block.js
  core/block_dragger.js
  core/block_svg.js
  core/blockly.js
  core/comment.js
  core/connection.js
  core/contextmenu.js
  core/extensions.js
  core/field.js
  core/field_angle.js
  core/field_variable.js
  core/flyout_base.js
  core/gesture.js
  core/menu.js
  core/mutator.js
  core/procedures.js
  core/rendered_connection.js
  core/shortcut_items.js
  core/tooltip.js
  core/trashcan.js
  core/utils.js
  core/variable_map.js
  core/warning.js
  core/widgetdiv.js
  core/workspace_comment.js
  core/workspace_comment_svg.js
  core/workspace_svg.js
  core/xml.js
  core/zoom_controls.js
Labels: cla: yes

#5590 fix: Make update_metadata.sh work on macOS
  tests/scripts/update_metadata.sh
Labels: cla: yes

#5429 Fix options list being repeated when showEditor is programmatically called repeatedly
  core/field_dropdown.js
Labels: cla: yes

#5618 chore: update dependabot messages and labels
  .github/dependabot.yml
Labels: dependencies, cla: yes, chore

#5626 chore: replace var with const and let in blocks directory
  blocks/lists.js
  blocks/logic.js
  blocks/loops.js
  blocks/math.js
  blocks/procedures.js
  blocks/text.js
  blocks/variables.js
  blocks/variables_dynamic.js
Labels: cla: yes, PR: chore

#5650 chore: replace var with const and let in python block generators
  generators/python/colour.js
  generators/python/lists.js
  generators/python/logic.js
  generators/python/loops.js
  generators/python/math.js
  generators/python/procedures.js
  generators/python/text.js
  generators/python/variables.js
  tests/deps.mocha.js
Labels: cla: yes

#5647 chore: update language generators to const and let
  generators/javascript.js
  generators/lua.js
  generators/php.js
  generators/python.js
Labels: cla: yes, PR: chore

#5642 chore: adds initial action to assign reviewers
  .github/workflows/assign_reviewers.yml
  .github/workflows/check_clang_format.yml
  .github/workflows/scripts/assign_reviewers.js
Labels: cla: yes
