Repository google/blockly, pull requests merged in 2022-09, with the labels that each got.

#6361 fix: TS errors on dependent projects with certain tsconfig settings (#6360)
  core/block.ts
  core/field_registry.ts
  core/utils/toolbox.ts
Labels: component: TypeScript, PR: fix

#6425 fix: Deep copy options used by dropdown fields
  core/field_dropdown.ts
  tests/mocha/json_test.js
Labels: component: fields

#6422 chore: Re-remove `core/blockly.js`
  core/blockly.js
Labels: component: build process, PR: chore

#6432 chore(blocks): Convert sort block to use BKY messages.
  blocks/lists.js
Labels: component: library blocks, PR: chore

#6440 fix: Fix blocks with mutators.
  blocks/lists.js
  blocks/procedures.js
  blocks/text.js
  core/comment.ts
  core/extensions.ts
  core/icon.ts
  core/mutator.ts
  core/warning.ts
Labels: deprecation
