Repository google/blockly, pull requests merged in 2022-12, with the labels that each got.

#6666 feat: make `getWorkspace`, `getFlyout`, and `getToolbox` public
  core/flyout_base.ts
  core/workspace_svg.ts
Labels: PR: feature

#6674 feat: make the variable map return early for noops
  core/variable_map.ts
  core/variable_model.ts
  tests/mocha/variable_map_test.js
Labels: PR: feature

#6679 chore: stop linter from whining about no return
  core/variables.ts
Labels: PR: chore

#6667 docs: Add notice to use unpkg instead of demos.
  appengine/blockly_compressed.js
Labels: PR: docs

#6668 chore: procedure event serialization
  tests/mocha/event_procedure_change_return_test.js
  tests/mocha/event_procedure_create_test.js
  tests/mocha/event_procedure_delete_test.js
  tests/mocha/event_procedure_enable_test.js
  tests/mocha/event_procedure_parameter_create_test.js
  tests/mocha/event_procedure_parameter_delete_test.js
  tests/mocha/event_procedure_parameter_rename_test.js
  tests/mocha/event_procedure_rename_test.js
Labels: PR: chore

#6598 refactor: Migrate to PointerEvents
  core/block_dragger.ts
  core/block_svg.ts
  core/blockly.ts
  core/browser_events.ts
  core/bubble.ts
  core/bubble_dragger.ts
  core/comment.ts
  core/field.ts
  core/field_angle.ts
  core/field_colour.ts
  core/flyout_base.ts
  core/flyout_button.ts
  core/gesture.ts
  core/icon.ts
  core/inject.ts
  core/menu.ts
  core/mutator.ts
  core/scrollbar.ts
  core/toolbox/toolbox.ts
  core/tooltip.ts
  core/touch.ts
  core/touch_gesture.ts
  core/trashcan.ts
  core/workspace_comment_svg.ts
  core/workspace_svg.ts
  core/zoom_controls.ts
  scripts/migration/renamings.json5
  tests/mocha/toolbox_test.js
  tests/mocha/tooltip_test.js
  tests/mocha/touch_test.js
Labels: breaking change, deprecation, PR: refactor

#6678 feat: add destroy lifecycle hook to blocks
  core/block.ts
  tests/mocha/block_test.js
  tests/mocha/test_helpers/events.js
  tests/mocha/test_helpers/setup_teardown.js
Labels: PR: feature

#6677 chore: update release notes config and tagging
  .github/release.yml
  .github/workflows/conventional-label.yml
Labels: PR: chore

#6687 fix(appengine): Restore build products to previous location
  scripts/gulpfiles/appengine_tasks.js
Labels: PR: fix

#6669 feat: procedure event serialization
  core/events/events_procedure_base.ts
  core/events/events_procedure_change_return.ts
  core/events/events_procedure_create.ts
  core/events/events_procedure_delete.ts
  core/events/events_procedure_enable.ts
  core/events/events_procedure_parameter_base.ts
  core/events/events_procedure_parameter_create.ts
  core/events/events_procedure_parameter_delete.ts
  core/events/events_procedure_parameter_rename.ts
  core/events/events_procedure_rename.ts
  core/serialization/procedures.ts
  tests/mocha/event_procedure_change_return_test.js
  tests/mocha/event_procedure_create_test.js
  tests/mocha/event_procedure_delete_test.js
  tests/mocha/event_procedure_enable_test.js
  tests/mocha/event_procedure_parameter_create_test.js
  tests/mocha/event_procedure_parameter_delete_test.js
  tests/mocha/event_procedure_parameter_rename_test.js
  tests/mocha/event_procedure_rename_test.js
Labels: PR: feature

#6690 fix: set default field to any and fix validator function return type
  core/field.ts
Labels: PR: fix

#6688 fix: don't reopen dropdownDiv if it was already open
  core/dropdowndiv.ts
  core/gesture.ts
Labels: PR: fix

#6698 fix: Don't spellcheck number fields.
  core/field_number.ts
Labels: component: fields, PR: fix

#6703 fix(tests): Fix bootstrapping of generators in compressed mode
  tests/bootstrap.js
  tests/bootstrap_helper.js
Labels: component: tests, PR: fix

#6699 feat: Display a 'wait' cursor when opening trashcan
  core/trashcan.ts
Labels: PR: feature

#6705 chore: miscellaneous fixes to docs, style, and tests
  core/blocks.ts
  core/icon.ts
  scripts/gulpfiles/build_tasks.js
  tests/generators/webdriver.js
  tests/mocha/webdriver.js
Labels: component: tests, component: build process, PR: chore

#6704 chore: update typings docs
  typings/README.md
Labels: PR: chore, PR: docs

#6702 fix: not being able to set field values to empty
  core/field_input.ts
  tests/mocha/blocks/procedures_test.js
Labels: component: fields, PR: fix

#6709 chore: Rollup of 2022 Q4 updates from TranslateWiki
  msg/json/bs.json
  msg/json/de.json
  msg/json/diq.json
  msg/json/es.json
  msg/json/fr.json
  msg/json/he.json
  msg/json/hy.json
  msg/json/is.json
  msg/json/ja.json
  msg/json/ko.json
  msg/json/nb.json
  msg/json/oc.json
  msg/json/smn.json
  msg/json/zh-hant.json
Labels: PR: chore

#6710 chore(tests): Update metadata for 2022 Q4 release
  tests/scripts/check_metadata.sh
Labels: component: tests, PR: chore

#6670 chore(tests): procedure blocks
  core/mutator.ts
  tests/mocha/blocks/procedures_test.js
  tests/mocha/test_helpers/procedures.js
Labels: PR: chore
