Repository google/blockly, pull requests merged in 2022-04, with the labels that each got.

#6045 chore(demos): redirect some demos to gh-pages
  appengine/redirect.html
Labels: component: demos

#6042 feat: Add margin around zoomToFit
  core/workspace_svg.js
Labels: PR: feature

#6066 chore(demos): delete some duplicated demos
  demos/codelab/README.md
  demos/codelab/app-complete/index.html
  demos/codelab/app-complete/scripts/main.js
  demos/codelab/app-complete/scripts/music_maker.js
  demos/codelab/app-complete/scripts/sound_blocks.js
  demos/codelab/app-complete/sounds/c4.m4a
  demos/codelab/app-complete/sounds/c5.m4a
  demos/codelab/app-complete/sounds/d4.m4a
  demos/codelab/app-complete/sounds/e4.m4a
  demos/codelab/app-complete/sounds/f4.m4a
  demos/codelab/app-complete/sounds/g4.m4a
  demos/codelab/app-complete/styles/index.css
  demos/codelab/app/index.html
  demos/codelab/app/scripts/main.js
  demos/codelab/app/scripts/music_maker.js
  demos/codelab/app/sounds/c4.m4a
  demos/codelab/app/sounds/c5.m4a
  demos/codelab/app/sounds/d4.m4a
  demos/codelab/app/sounds/e4.m4a
  demos/codelab/app/sounds/f4.m4a
  demos/codelab/app/sounds/g4.m4a
  demos/codelab/app/styles/index.css
  demos/custom-dialogs/custom-dialog.js
  demos/custom-dialogs/icon.png
  demos/custom-dialogs/index.html
  demos/custom-fields/icon.png
  demos/custom-fields/index.html
  demos/custom-fields/pitch/blocks.js
  demos/custom-fields/pitch/field_pitch.js
  demos/custom-fields/pitch/index.html
  demos/custom-fields/pitch/media/notes.png
  demos/custom-fields/pitch/pitch.css
  demos/custom-fields/turtle/blocks.js
  demos/custom-fields/turtle/field_turtle.js
  demos/custom-fields/turtle/icon.png
  demos/custom-fields/turtle/index.html
  demos/custom-fields/turtle/media/crown.svg
  demos/custom-fields/turtle/media/fedora.svg
  demos/custom-fields/turtle/media/mask.svg
  demos/custom-fields/turtle/media/propeller.svg
  demos/custom-fields/turtle/media/stovepipe.svg
  demos/custom-fields/turtle/media/warning.svg
  demos/custom-fields/turtle/turtle.css
  demos/fixed/icon.png
  demos/fixed/index.html
  demos/generator/icon.png
  demos/generator/index.html
  demos/graph/icon.png
  demos/graph/index.html
  demos/index.html
  demos/interpreter/acorn_interpreter.js
  demos/interpreter/async-execution.html
  demos/interpreter/icon.png
  demos/interpreter/index.html
  demos/interpreter/step-execution.html
  demos/interpreter/wait_block.js
  demos/maxBlocks/icon.png
  demos/maxBlocks/index.html
Labels: type: cleanup, component: demos, PR: chore

#6092 fix: type error in uneditable bubbles
  core/browser_events.js
  core/bubble.js
Labels: PR: fix

#6099 fix: improve types in touch code
  core/gesture.js
  core/touch.js
  core/touch_gesture.js
Labels: component: TypeScript, PR: fix

#6102 fix: add compose and decompose to block
  core/block.js
  core/events/utils.js
Labels: component: TypeScript, PR: fix

#6104 fix: component id should be on the prototype
  core/delete_area.js
  core/drag_target.js
  core/interfaces/i_block_dragger.js
  core/interfaces/i_component.js
Labels: component: TypeScript, PR: fix

#6105 fix!: fix or silence type errors
  core/flyout_base.js
  core/gesture.js
  core/interfaces/i_flyout.js
  core/interfaces/i_toolbox_item.js
  core/keyboard_nav/ast_node.js
  core/renderers/common/i_path_object.js
  core/renderers/zelos/drawer.js
  core/renderers/zelos/info.js
  core/serialization/blocks.js
  core/shortcut_items.js
  core/toolbox/toolbox.js
  core/toolbox/toolbox_item.js
  core/tooltip.js
  core/workspace_svg.js
  tests/deps.js
Labels: component: TypeScript, PR: fix

#6118 chore: Make startsWith faster
  core/touch.js
  core/utils/parsing.js
  core/utils/string.js
  scripts/gulpfiles/chunks.json
  tests/deps.js
  tests/mocha/utils_test.js
  typings/blockly.d.ts
Labels: component: performance

#6128 fix: Increases the speed of deleting blocks
  core/block_animations.js
  core/block_drag_surface.js
  core/dropdowndiv.js
  core/workspace_drag_surface_svg.js
Labels: component: performance
