Repository google/blockly, pull requests merged in 2022-08, with the labels that each got.

#6302 refactor: remove AnyDuringMigration from the block drag surface
  core/block_drag_surface.ts
Labels: deprecation

#6326 chore(tests): remove unused run of typings
  package.json
  tests/run_all_tests.sh
Labels: type: cleanup, component: tests, PR: chore

#6335 chore(build)!: compile to ES2015 instead of ES5
  scripts/gulpfiles/build_tasks.js
Labels: component: build process, breaking change, PR: chore

#6222 chore(tests): Drop build/test support for node.js v12
  .github/workflows/build.yml
  scripts/gulpfiles/build_tasks.js
Labels: component: tests, component: build process, PR: chore

#6337 feat!: allow blocks to receive their own delete events
  blocks/procedures.js
  core/block.ts
  tests/mocha/block_delete_event_test.js
  tests/mocha/blocks/lists_test.js
  tests/mocha/blocks/logic_ternary_test.js
  tests/mocha/blocks/procedures_test.js
  tests/mocha/index.html
Labels: component: events, breaking change, PR: feature

#6352 fix(build): Fix sourcemaps
  scripts/gulpfiles/build_tasks.js
  tsconfig.json
Labels: component: build process, PR: fix

#6336 fix!: remove checks for IE and EdgeHTML in core
  core/comment.ts
  core/contextmenu.ts
  core/contextmenu_items.ts
  core/field.ts
  core/grid.ts
  core/renderers/common/constants.ts
  core/touch.ts
  core/utils/dom.ts
  core/utils/svg_math.ts
  core/utils/toolbox.ts
  core/utils/useragent.ts
  tests/mocha/contextmenu_items_test.js
Labels: component: browser, breaking change, PR: fix

#6355 fix!: remove unused or obsolete useragent checks
  core/utils/useragent.ts
Labels: component: browser, breaking change, PR: fix

#6350 chore(build): Only suppress expected warnings from closure-make-deps
  scripts/gulpfiles/build_tasks.js
Labels: component: build process, PR: chore

#6318 refactor: Remove uses of AnyDuringMigration from scrollbar.ts, workspace_svg.ts, contextmenu_registry.ts, and component_manager.ts
  core/clipboard.ts
  core/component_manager.ts
  core/contextmenu_registry.ts
  core/flyout_base.ts
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
  core/inject.ts
  core/options.ts
  core/scrollbar.ts
  core/utils/dom.ts
  core/workspace_svg.ts
Labels: component: TypeScript, PR: chore

#6356 fix(build): Have prepare task signal async completion
  scripts/gulpfiles/build_tasks.js
Labels: component: build process, PR: fix

#6362 chore(build): use inline sources in sourcemaps; don't package sources separately
  scripts/gulpfiles/build_tasks.js
  scripts/gulpfiles/package_tasks.js
Labels: component: build process, PR: chore

#6364 chore(tests): Remove IE11 / ES5-only support from `bootstrap.js`
  tests/bootstrap.js
Labels: component: tests, PR: chore

#6377 chore: remove AnyDuringMigration from dropdown and widget divs
  core/dropdowndiv.ts
  core/widgetdiv.ts
Labels: type: cleanup, component: TypeScript, PR: chore

#6380 refactor: Mark optional parameters as optional.
  core/events/events_bubble_open.ts
  core/flyout_metrics_manager.ts
  core/registry.ts
  core/renderers/common/renderer.ts
  core/renderers/geras/renderer.ts
Labels: type: cleanup, PR: chore

#6375 chore: remove underscores from private properties in grid.ts
  core/grid.ts
Labels: type: cleanup, PR: chore

#6385 refactor!: Removed backwards compatibility for getDeveloperVars().
  core/variables.ts
  tests/generators/unittest.js
Labels: type: cleanup, component: developer apis, breaking change

#6386 fix!: remove unused functions in style.ts
  core/utils/style.ts
Labels: type: cleanup, component: developer apis, breaking change, PR: fix

#6389 chore: remove IE support from CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: type: cleanup

#6390 chore: update pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: cleanup, PR: chore

#6396 fix: remove some IE-specific code in dom and style
  core/utils/dom.ts
  core/utils/style.ts
Labels: type: cleanup, PR: fix, deprecation

#6387 fix: deprecate functions in object.ts
  core/shortcut_registry.ts
  core/utils/deprecation.ts
  core/utils/object.ts
Labels: type: cleanup, component: developer apis, component: keyboard_nav, PR: fix, deprecation

#6399 fix: context menu not working
  core/menu.ts
Labels: PR: fix

#6400 fix: stop using `is3dSupported`
  core/block_svg.ts
  core/bubble_dragger.ts
  core/utils/svg_math.ts
  core/workspace_comment_svg.ts
  core/workspace_svg.ts
Labels: type: cleanup, PR: fix, deprecation
