Repository google/blockly, pull requests merged in 2022-10, with the labels that each got.

#6477 chore(tests): Update metadata for 2022 Q3 release
  tests/scripts/check_metadata.sh
Labels: component: tests, PR: chore

#6479 chore(build): Rebuild blockly for v9.0.0 release
  blockly_compressed.js
  blockly_compressed.js.map
  blocks_compressed.js
  blocks_compressed.js.map
  dart_compressed.js
  dart_compressed.js.map
  javascript_compressed.js
  javascript_compressed.js.map
  lua_compressed.js
  lua_compressed.js.map
  package-lock.json
  package.json
  php_compressed.js
  php_compressed.js.map
  python_compressed.js
  python_compressed.js.map
Labels: PR: chore

#6502 fix: Connections can be highlighted multiple times
  core/rendered_connection.ts
Labels: PR: fix

#6509 chore(deps): force update @blockly deps
  package-lock.json
  package.json
Labels: PR: chore

#6532 fix: move Theme to use a Partial type for BlockStyle
  core/field_angle.ts
  core/field_dropdown.ts
  core/field_textinput.ts
  core/renderers/common/constants.ts
  core/renderers/common/path_object.ts
  core/renderers/zelos/path_object.ts
  core/theme.ts
Labels: PR: fix

#6533 fix: fix block factory in manual mode
  demos/blockfactory/block_definition_extractor.js
  demos/blockfactory/factory.js
Labels: PR: fix

#6536 chore: remove underscores from private properties in workspace.ts
  core/workspace.ts
  tests/mocha/gesture_test.js
  tests/mocha/test_helpers/workspace.js
Labels: PR: chore

#6537 chore: remove underscores from some private properties and methods
  core/workspace_svg.ts
  core/zoom_controls.ts
  tests/mocha/gesture_test.js
Labels: type: cleanup

#6534 chore: Remove blockly factory use of utils.dom.add/removeClass
  blocks/procedures.js
  core/block_svg.ts
  core/shortcut_registry.ts
  demos/blockfactory/factory.js
  demos/blockfactory/standard_categories.js
  demos/blockfactory/workspacefactory/wfactory_controller.js
  demos/blockfactory/workspacefactory/wfactory_view.js
  tests/mocha/blocks/variables_test.js
  tests/mocha/shortcut_registry_test.js
Labels: PR: chore

#6538 fix: parent blocks not bumping neighbours
  core/block_svg.ts
  core/rendered_connection.ts
Labels: PR: fix

#6489 feat: add basic observable implementations of procedure interfaces
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_map.ts
  core/procedures/observable_procedure_model.ts
Labels: PR: feature

#6485 test: add shared procedures playground
  tests/playgrounds/shared_procedures.html
Labels: component: tests, PR: feature

#6544 fix: fix pinch to zoom
  core/touch.ts
  tests/mocha/index.html
  tests/mocha/touch_test.js
Labels: PR: fix

#6545 fix: Don't quote fromJson property.
  core/events/events_block_drag.ts
  core/events/events_bubble_open.ts
  core/field_registry.ts
  core/shortcut_items.ts
Labels: PR: fix

#6551 chore: clean up code in field_angle.ts
  core/field_angle.ts
Labels: type: cleanup, PR: chore

#6542 fix: make getSourceBlock nullable again
  core/field.ts
  core/field_angle.ts
  core/field_dropdown.ts
  core/field_multilineinput.ts
  core/field_textinput.ts
  core/field_variable.ts
  core/interfaces/i_ast_node_location_with_block.ts
  core/keyboard_nav/ast_node.ts
  core/procedures.ts
Labels: PR: fix

#6558 fix: Don't warn if field is acually 0 width
  core/field.ts
  core/utils/parsing.ts
Labels: PR: fix

#6559 chore: fix mutator blocks jumping
  core/block_animations.ts
Labels: PR: chore

#6562 chore: update procedure map tests to match the refactored API
  core/blockly.ts
  core/procedures.ts
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_map.ts
  core/procedures/observable_procedure_model.ts
  tests/mocha/procedure_map_test.js
Labels: PR: chore

#6573 release: v9.0.1
  blockly_compressed.js
  blockly_compressed.js.map
  core/block_animations.ts
  core/field.ts
  core/field_angle.ts
  core/field_dropdown.ts
  core/field_multilineinput.ts
  core/field_textinput.ts
  core/field_variable.ts
  core/interfaces/i_ast_node_location_with_block.ts
  core/keyboard_nav/ast_node.ts
  core/procedures.ts
  core/touch.ts
  package-lock.json
  package.json
  tests/mocha/index.html
  tests/mocha/touch_test.js
Labels: PR: release

#6550 chore: added type information to `core/field_dropdown.ts`
  core/blockly.ts
  core/field_dropdown.ts
  core/field_variable.ts
Labels: PR: chore

#6560 fix: feedback on procedure model implementations
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_map.ts
Labels: PR: fix

#6569 chore: update procedure map tests to match the refactored API
  core/blockly.ts
  core/procedures.ts
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_model.ts
  tests/mocha/procedure_map_test.js
Labels: PR: chore

#6570 feat: trigger updates to IProcedureBlock blocks
  core/interfaces/i_procedure_block.ts
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_map.ts
  core/procedures/observable_procedure_model.ts
  core/procedures/update_procedures.ts
  tests/mocha/procedure_map_test.js
Labels: PR: feature

#6574 chore: add tests for procedure serialization
  tests/mocha/jso_deserialization_test.js
  tests/mocha/jso_serialization_test.js
Labels: PR: chore

#6581 chore: Merge branch 'master' back into develop after v9.0.1 release
  package-lock.json
  package.json
  scripts/migration/renamings.json5
Labels: PR: chore

#6577 chore: start command uses tsc watch
  package-lock.json
  package.json
Labels: PR: chore

#6575 fix: refactors concrete implementations of the procedure data models
  core/interfaces/i_parameter_model.ts
  core/interfaces/i_procedure_map.ts
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_map.ts
  core/procedures/observable_procedure_model.ts
  core/workspace.ts
  tests/mocha/procedure_map_test.js
Labels: PR: fix

#6582 feat: add serialization of procedure models
  core/serialization.ts
  core/serialization/priorities.ts
  core/serialization/procedures.ts
  tests/mocha/jso_deserialization_test.js
  tests/mocha/jso_serialization_test.js
Labels: PR: feature

#6585 fix: Rename Generator to CodeGenerator
  .eslintrc.json
  .github/CONTRIBUTING.md
  .github/dependabot.yml
  .github/workflows/tag_module_cleanup.yml
  .github/workflows/update_metadata.yml
  closure/goog/base_minimal.js
  core/blockly.ts
  core/generator.ts
  demos/blockfactory/analytics.js
  demos/code/code.js
  demos/mobile/android/build.gradle
  demos/mobile/ios/Blockly WebView/ViewController.swift
  generators/dart.js
  generators/javascript.js
  generators/lua.js
  generators/php.js
  generators/python.js
  scripts/gulpfiles/build_tasks.js
  scripts/package/README.md
  scripts/package/templates/node.template
  scripts/package/templates/umd-msg.template
  scripts/package/templates/umd.template
  tests/bootstrap.js
  tests/generators/run_generators_in_browser.js
  tests/mocha/block_change_event_test.js
  tests/mocha/field_angle_test.js
  tests/mocha/field_checkbox_test.js
  tests/mocha/field_colour_test.js
  tests/mocha/field_dropdown_test.js
  tests/mocha/field_label_serializable_test.js
  tests/mocha/field_multilineinput_test.js
  tests/mocha/field_number_test.js
  tests/mocha/field_registry_test.js
  tests/mocha/field_test.js
  tests/mocha/field_variable_test.js
  tests/mocha/generator_test.js
  tests/mocha/jso_deserialization_test.js
  tests/mocha/jso_serialization_test.js
  tests/mocha/procedure_map_test.js
  tests/mocha/registry_test.js
  tests/mocha/run_mocha_tests_in_browser.js
  tests/mocha/test_helpers/code_generation.js
  tests/mocha/touch_test.js
  tests/mocha/widget_div_test.js
  tests/playground.html
  tests/scripts/setup_osx_env.sh
Labels: PR: fix

#6584 chore: remove underscores and clean up scrollbar.ts
  core/scrollbar.ts
Labels: PR: chore

#6588 fix(tests): generator tests on linux
  scripts/gulpfiles/test_tasks.js
Labels: PR: fix

#6583 chore: remove some underscores in icon-related classes
  core/comment.ts
  core/mutator.ts
  core/warning.ts
  tests/mocha/mutator_test.js
Labels: PR: chore
