Repository google/blockly, pull requests merged in 2022-11, with the labels that each got.

#6596 test: add tests for the insertion marker manager
  tests/mocha/index.html
  tests/mocha/insertion_marker_manager_test.js
  tests/mocha/test_helpers/block_definitions.js
Labels: component: tests

#6506 chore: add command to generate reference docs
  gulpfile.js
  package-lock.json
  package.json
  patches/@microsoft+api-documenter+7.19.24.patch
  scripts/gulpfiles/docs_tasks.js
Labels: PR: chore

#6610 chore: disable serialization of procedure data for point release
  core/serialization/procedures.ts
  tests/mocha/jso_serialization_test.js
Labels: PR: chore

#6602 chore: clean up insertion marker code
  core/block_dragger.ts
  core/insertion_marker_manager.ts
  tests/mocha/insertion_marker_manager_test.js
Labels: PR: chore

#6604 feat: add firing of procedure events.
  core/events/events.ts
  core/events/events_procedure_base.ts
  core/events/events_procedure_change_return.ts
  core/events/events_procedure_create.ts
  core/events/events_procedure_delete.ts
  core/events/events_procedure_enable.ts
  core/events/events_procedure_parameter_base.ts
  core/events/events_procedure_parameter_create.ts
  core/events/events_procedure_parameter_delete.ts
  core/events/events_procedure_parameter_rename.ts
  core/events/events_procedure_rename.ts
  core/events/utils.ts
  core/interfaces/i_observable.ts
  core/interfaces/i_parameter_model.ts
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_map.ts
  core/procedures/observable_procedure_model.ts
  tests/mocha/event_test.js
  tests/mocha/procedure_map_test.js
  tests/mocha/test_helpers/events.js
  tests/mocha/workspace_svg_test.js
Labels: PR: feature

#6603 chore: add validator and field value types
  core/block.ts
  core/blockly.ts
  core/dropdowndiv.ts
  core/field.ts
  core/field_angle.ts
  core/field_checkbox.ts
  core/field_colour.ts
  core/field_dropdown.ts
  core/field_image.ts
  core/field_input.ts
  core/field_label.ts
  core/field_label_serializable.ts
  core/field_multilineinput.ts
  core/field_number.ts
  core/field_registry.ts
  core/field_textinput.ts
  core/field_variable.ts
  core/input.ts
  core/interfaces/i_registrable_field.ts
Labels: PR: chore

#6612 chore: removes underscores in input
  core/input.ts
Labels: type: cleanup, PR: chore

#6613 chore: clean up field default values
  core/field.ts
  core/field_angle.ts
  core/field_checkbox.ts
  core/field_colour.ts
  core/field_image.ts
  core/field_label.ts
  core/field_number.ts
  core/field_textinput.ts
Labels: PR: chore

#6614 feat: refactor event serialization to use static fromJson method
  core/events/events_abstract.ts
  core/events/events_block_base.ts
  core/events/events_block_change.ts
  core/events/events_block_create.ts
  core/events/events_block_delete.ts
  core/events/events_block_drag.ts
  core/events/events_block_move.ts
  core/events/events_bubble_open.ts
  core/events/events_click.ts
  core/events/events_comment_base.ts
  core/events/events_comment_change.ts
  core/events/events_comment_create.ts
  core/events/events_comment_delete.ts
  core/events/events_comment_move.ts
  core/events/events_marker_move.ts
  core/events/events_selected.ts
  core/events/events_theme_change.ts
  core/events/events_toolbox_item_select.ts
  core/events/events_trashcan_open.ts
  core/events/events_var_base.ts
  core/events/events_var_create.ts
  core/events/events_var_delete.ts
  core/events/events_var_rename.ts
  core/events/events_viewport.ts
  core/events/utils.ts
  tests/mocha/event_block_change_test.js
  tests/mocha/event_block_create_test.js
  tests/mocha/event_block_delete_test.js
  tests/mocha/event_block_drag_test.js
  tests/mocha/event_block_move_test.js
  tests/mocha/event_bubble_open_test.js
  tests/mocha/event_click_test.js
  tests/mocha/event_comment_change_test.js
  tests/mocha/event_comment_create_test.js
  tests/mocha/event_comment_delete_test.js
  tests/mocha/event_comment_move_test.js
  tests/mocha/event_marker_move_test.js
  tests/mocha/event_selected_test.js
  tests/mocha/event_test.js
  tests/mocha/event_theme_change_test.js
  tests/mocha/event_toolbox_item_select_test.js
  tests/mocha/event_trashcan_open_test.js
  tests/mocha/event_var_create_test.js
  tests/mocha/event_var_delete_test.js
  tests/mocha/event_var_rename_test.js
  tests/mocha/event_viewport_test.js
  tests/mocha/index.html
  tests/mocha/mutator_test.js
Labels: PR: feature

#6616 chore: add 'fixes' to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: chore

#6599 fix(renamings): Small correction to renaming of `Blockly.utils.global`
  scripts/migration/renamings.json5
Labels: PR: fix

#6628 chore: add 'fixes' to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: chore

#6615 feat(test): Miscellaneous improvements to `test_tasks.js`
  gulpfile.js
  package-lock.json
  package.json
  scripts/gulpfiles/test_tasks.js
Labels: component: tests, PR: feature

#6635 docs(messages): Add a msg/json/README.md
  msg/json/README.md
Labels: PR: docs

#6634 fix: make mutator workspace public
  core/mutator.ts
Labels: PR: fix

#6627 chore(tests): test running procedure events
  core/events/events_abstract.ts
  tests/mocha/event_procedure_change_return_test.js
  tests/mocha/event_procedure_create_test.js
  tests/mocha/event_procedure_delete_test.js
  tests/mocha/event_procedure_enable_test.js
  tests/mocha/event_procedure_parameter_create_test.js
  tests/mocha/event_procedure_parameter_delete_test.js
  tests/mocha/event_procedure_parameter_rename_test.js
  tests/mocha/event_procedure_rename_test.js
  tests/mocha/index.html
  tests/mocha/procedure_map_test.js
  tests/mocha/test_helpers/events.js
Labels: PR: chore

#6636 chore(build): Re-delete tests/run_all_tests.sh
  tests/run_all_tests.sh
Labels: component: build process, PR: chore

#6625 feat: add option to disable modal inputs on mobile
  core/blockly_options.ts
  core/field_input.ts
  core/options.ts
  tests/mocha/field_textinput_test.js
Labels: PR: feature

#6657 fix: Add redirects to old demos.
  appengine/app.yaml
  appengine/redirect.html
Labels: PR: fix

#6637 fix(deps): update json schema validation
  package-lock.json
  package.json
  tests/migration/renamings.schema.json
  tests/migration/validate-renamings.js
Labels: PR: fix

#6655 fix: blocks not receiving their own delete events
  core/block.ts
  tests/mocha/event_block_delete_test.js
  tests/mocha/test_helpers/setup_teardown.js
Labels: PR: fix
