Repository google/blockly, pull requests merged in 2023-04, with the labels that each got.

#6918 fix: remove forced rerender from mutator
  core/mutator.ts
Labels: PR: fix

#6954 fix: disposing during dragging
  core/block_dragger.ts
Labels: PR: fix

#6959 chore: remove underscores from properties and methods in trashcan
  core/trashcan.ts
  tests/mocha/comment_deserialization_test.js
  tests/mocha/trashcan_test.js
Labels: PR: chore

#6960 chore: remove underscores from private properties and methods for flyout
  core/flyout_base.ts
  core/flyout_button.ts
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
  tests/mocha/flyout_test.js
Labels: PR: chore

#6970 refactor: Remove some more uses of AnyDuringMigration.
  core/blockly.ts
  core/inject.ts
  core/theme/classic.ts
Labels: PR: refactor

#6961 chore: remove underscores from private properties and methods in connections
  core/connection.ts
  core/connection_db.ts
  core/rendered_connection.ts
  tests/mocha/block_test.js
  tests/mocha/blocks/logic_ternary_test.js
  tests/mocha/connection_db_test.js
Labels: PR: chore

#6969 chore: delete update metadata action
  .github/workflows/update_metadata.yml
Labels: PR: chore

#6973 fix: Fix offset location of connection ripple
  core/insertion_marker_manager.ts
Labels: PR: fix

#6975 chore: remove underscores from private properties and methods in keyboard nav and rendering
  core/keyboard_nav/ast_node.ts
  core/keyboard_nav/basic_cursor.ts
  core/keyboard_nav/marker.ts
  core/renderers/common/constants.ts
  core/renderers/common/marker_svg.ts
  core/renderers/geras/highlighter.ts
  core/renderers/geras/renderer.ts
  core/renderers/zelos/constants.ts
  core/renderers/zelos/info.ts
  core/renderers/zelos/marker_svg.ts
  core/renderers/zelos/path_object.ts
  tests/mocha/astnode_test.js
  tests/mocha/cursor_test.js
Labels: type: cleanup, PR: chore

#6977 chore: remove underscores from private properties and methods in some fields
  core/field_checkbox.ts
  core/field_dropdown.ts
  core/field_image.ts
  core/field_label.ts
  core/field_number.ts
  tests/mocha/field_image_test.js
Labels: PR: chore

#6979 fix: Don't truncate text label fields.
  core/field_label.ts
Labels: PR: fix

#6916 fix: do not hide chaff when resizing
  core/bump_objects.ts
  core/field.ts
  core/field_input.ts
  core/inject.ts
  core/widgetdiv.ts
  core/workspace_svg.ts
Labels: PR: fix

#6982 chore: 'compareDocumentPosition' to 'contains'
  core/inject.ts
  core/utils/dom.ts
  core/workspace_svg.ts
Labels: PR: chore

#6952 fix: non-printable characters in XML
  core/utils/xml.ts
  tests/mocha/serializer_test.js
  tests/mocha/xml_test.js
Labels: PR: fix

#6902 refactor(blocks): Migrate `blocks/lists.js` to TypeScript
  blocks/lists.ts
Labels: component: library blocks, PR: refactor

#6957 refactor(blocks): Migrate `blocks/loops.js` to TypeScript
  blocks/loops.ts
Labels: PR: refactor

#6981 feat: add after queued renders promises to render management
  core/block_svg.ts
  core/blockly.ts
  core/insertion_marker_manager.ts
  core/render_management.ts
  tests/mocha/index.html
  tests/mocha/render_management_test.js
Labels: PR: feature

#6989 fix: block_svg disable/enable ops lead to unsync state and render
  core/block_svg.ts
Labels: PR: fix

#6995 chore(tests): Update configuration to test on node.js v20
  .eslintrc.js
  .github/workflows/build.yml
  package-lock.json
  package.json
Labels: PR: chore

#6991 fix: rtl field alignment
  core/field_input.ts
Labels: PR: fix

#7005 fix: insertion markers firing move events
  core/insertion_marker_manager.ts
Labels: PR: fix

#6990 feat: add support for appending custom inputs
  core/block.ts
  core/input.ts
  core/input_types.ts
  core/registry.ts
  tests/mocha/block_json_test.js
Labels: PR: feature

#6998 fix: update applyColour documentation
  core/field.ts
  core/field_colour.ts
  core/field_dropdown.ts
  core/field_input.ts
Labels: PR: fix

#6994 chore: clean up some drawer code lint
  core/renderers/zelos/drawer.ts
Labels: type: cleanup, PR: chore

#7001 refactor(blocks): Migrate `blocks/variables.js` and `blocks/variables_dynamic.js` to TypeScript
  blocks/loops.ts
  blocks/variables.ts
  blocks/variables_dynamic.ts
  core/contextmenu.ts
Labels: PR: refactor

#7011 chore(build): Delete chunks cache file `chunks.json`
  scripts/gulpfiles/chunks.json
Labels: component: build process, PR: chore

#7012 fix: icons not having their locations updated
  core/render_management.ts
Labels: PR: fix

#6996 feat: Add 'reason' field to move event
  core/block.ts
  core/block_dragger.ts
  core/block_svg.ts
  core/bump_objects.ts
  core/connection.ts
  core/events/events_block_move.ts
  core/events/utils.ts
  core/flyout_base.ts
  core/interfaces/i_bounded_element.ts
  core/rendered_connection.ts
  core/workspace_svg.ts
  core/xml.ts
Labels: PR: feature

#7022 chore: remove private underscores in field_variable.ts
  core/field_variable.ts
  tests/mocha/field_variable_test.js
Labels: type: cleanup, PR: chore

#6958 refactor(blocks): Migrate `blocks/text.js` to TypeScript
  blocks/text.ts
Labels: PR: refactor

#7018 chore: Merge master back into develop following v9.3.3 release
  package-lock.json
  package.json
Labels: PR: chore
