Repository google/blockly, pull requests merged in 2023-11, with the labels that each got.

#7620 chore: drop node16
  .github/workflows/browser_test.yml
  .github/workflows/build.yml
Labels: PR: chore

#7618 fix: flyout id is different than first placed block
  core/flyout_base.ts
  core/serialization/blocks.ts
  tests/mocha/jso_serialization_test.js
Labels: PR: fix

#7621 fix: prevent crash when clicking on a field to delete a block
  core/block_svg.ts
Labels: PR: fix

#7626 feat: add css classes to icons
  core/icons/comment_icon.ts
  core/icons/mutator_icon.ts
  core/icons/warning_icon.ts
Labels: PR: feature

#7628 fix: Shadow block dropdown gets color of parent category
  core/field_dropdown.ts
Labels: PR: fix

#7609 fix: shadows in insertion markers being displayed as shadows
  core/insertion_marker_manager.ts
  tests/mocha/insertion_marker_manager_test.js
Labels: PR: fix

#7634 fix: make autoclose toggleable for flyouts
  core/flyout_base.ts
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
  core/metrics_manager.ts
  tests/mocha/metrics_test.js
  tests/mocha/trashcan_test.js
Labels: PR: fix

#7619 fix: blocks being dragged behind toolbox
  core/block_dragger.ts
  core/block_svg.ts
  core/bubble_dragger.ts
  core/css.ts
  core/inject.ts
  core/interfaces/i_rendered_element.ts
  core/layer_manager.ts
  core/layers.ts
  core/workspace_comment_svg.ts
  core/workspace_svg.ts
  tests/mocha/index.html
  tests/mocha/layering_test.js
  tests/mocha/theme_test.js
  tests/mocha/workspace_comment_test.js
Labels: PR: fix

#7639 fix: update setShadow TSDoc for Block and BlockSvg
  core/block.ts
  core/block_svg.ts
Labels: PR: fix

#7617 refactor(generators): Migrate Python generators to TypeScript #7602
  generators/python.ts
  generators/python/colour.ts
  generators/python/lists.ts
  generators/python/logic.ts
  generators/python/loops.ts
  generators/python/math.ts
  generators/python/procedures.ts
  generators/python/python_generator.ts
  generators/python/text.ts
  generators/python/variables.js
  generators/python/variables.ts
  generators/python/variables_dynamic.ts
Labels: component: generators, PR: refactor

#7637 feat: add connection previewer interface
  core/blockly.ts
  core/interfaces/i_connection_previewer.ts
  core/registry.ts
Labels: PR: feature

#7651 chore: run build before and during interactive mocha
  package.json
Labels: PR: chore

#7650 fix: disabled render status after serialization
  core/block_svg.ts
  core/serialization/blocks.ts
  core/xml.ts
  tests/mocha/block_test.js
Labels: PR: fix

#7654 refactor(generators): Migrate Lua generators to TypeScript
  generators/lua.ts
  generators/lua/colour.ts
  generators/lua/lists.ts
  generators/lua/logic.ts
  generators/lua/loops.ts
  generators/lua/lua_generator.ts
  generators/lua/math.ts
  generators/lua/procedures.ts
  generators/lua/text.ts
  generators/lua/variables.js
  generators/lua/variables.ts
  generators/lua/variables_dynamic.ts
Labels: PR: refactor

#7640 chore: Renable macos-latest build
  .github/workflows/browser_test.yml
  .github/workflows/build.yml
Labels: PR: chore
