Repository google/blockly, pull requests merged in 2023-09, with the labels that each got.

#7454 fix: connection highlight not disposed when block deleted
  core/rendered_connection.ts
Labels: PR: fix

#7465 chore: remove unused sections from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: chore

#7382 chore: Use JSON objects for context menu callbackFactory
  blocks/loops.ts
  blocks/procedures.ts
  blocks/variables.ts
  blocks/variables_dynamic.ts
  core/contextmenu.ts
  tests/mocha/contextmenu_test.js
  tests/mocha/index.html
Labels: PR: chore

#7467 fix: doFullSerialization for insertion markers
  core/insertion_marker_manager.ts
Labels: PR: fix

#7473 refactor(build): Remove `closure-make-deps` and `closure-calculate-chunks`
  package-lock.json
  package.json
  scripts/gulpfiles/build_tasks.js
Labels: component: build process, PR: refactor

#7479 chore: Remove 'cgi' import from Python
  appengine/storage.py
Labels: PR: chore

#7482 fix: insertion marker position when connection is resized (#7426)
  core/block_svg.ts
  core/insertion_marker_manager.ts
Labels: PR: fix

#7485 fix(tests): contextMenuSelect sometimes clicks the wrong block
  tests/browser/test/basic_playground_test.js
  tests/browser/test/delete_blocks_test.js
  tests/browser/test/test_setup.js
Labels: PR: fix

#7490 fix: zelos full block fields rendering badly
  core/block.ts
  core/field.ts
  core/field_colour.ts
  core/field_input.ts
Labels: PR: fix

#7502 fix: immediately render for JavaFX
  core/render_management.ts
Labels: PR: fix

#7501 fix: bad JSON state leaving events disabled
  core/serialization/blocks.ts
  tests/mocha/jso_deserialization_test.js
Labels: PR: fix

#7500 chore(deps): update webdriverio to 8.16 and remove selenium-standalone
  .github/workflows/browser_test.yml
  .github/workflows/build.yml
  package-lock.json
  package.json
  tests/browser/test/test_setup.js
  tests/compile/webdriver.js
  tests/generators/webdriver.js
  tests/mocha/webdriver.js
  tests/scripts/selenium-config.js
  tests/scripts/setup_osx_env.sh
Labels: PR: chore

#7483 fix: Call onFinishEditing_ for fields on mobile.
  core/field_input.ts
  msg/messages.js
Labels: PR: fix

#7492 fix: incorrect blockchange firing
  core/block.ts
Labels: PR: fix

#7520 revert: "chore(deps): update webdriverio to 8.16 and stop using seleni…
  package-lock.json
  package.json
  tests/browser/test/test_setup.js
  tests/compile/webdriver.js
  tests/generators/webdriver.js
  tests/mocha/webdriver.js
Labels: PR: revert

#7519 feat: Add a getTargetWorkspace method to flyout_base.ts
  core/flyout_base.ts
Labels: PR: feature

#7528 fix: move delete keyboard shortcut in-progress gesture check to precondition #6274
  core/shortcut_items.ts
Labels: PR: fix

#7529 feat: made the method isDragTowardWorkspace non private
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
Labels: PR: feature

#7521 feat: Paste block in viewport / near cursor
  core/interfaces/i_movable.ts
  core/shortcut_items.ts
Labels: PR: feature

#7533 fix: removed underscore from isLabel_ in flyout_button.ts
  core/flyout_button.ts
Labels: PR: fix

#7517 fix: Addition of the .gitattributes file to standardize line endings #7191
  .gitattributes
Labels: PR: fix

#7537 fix: non-nullable check for block variable and removed ! in layout_ #7522
  core/flyout_horizontal.ts
Labels: PR: fix

#7540 chore: Rollup of 2023 Q3 updates from TranslateWiki
  msg/json/ba.json
  msg/json/bcc.json
  msg/json/bg.json
  msg/json/constants.json
  msg/json/el.json
  msg/json/en.json
  msg/json/es.json
  msg/json/fr.json
  msg/json/gl.json
  msg/json/gn.json
  msg/json/he.json
  msg/json/ia.json
  msg/json/id.json
  msg/json/ky.json
  msg/json/lt.json
  msg/json/nb.json
  msg/json/nl.json
  msg/json/pl.json
  msg/json/pms.json
  msg/json/pt-br.json
  msg/json/qqq.json
  msg/json/ru.json
  msg/json/sl.json
  msg/json/sv.json
  msg/json/synonyms.json
  msg/json/tcy.json
  msg/json/tr.json
  msg/json/vi.json
  msg/json/zh-hans.json
  msg/json/zh-hant.json
Labels: PR: chore

#7541 chore: Update metadata for 2023 Q3 release
  tests/scripts/check_metadata.sh
Labels: PR: chore

#7536 fix: non-nullable check for block variable and removed ! in layout_
  core/flyout_vertical.ts
Labels: PR: fix

#7545 chore: fix formatting for welcome action
  .github/workflows/welcome_new_contributors.yml
Labels: PR: chore

#7547 fix(build): Fix broken npm install of Closure Compiler
  package-lock.json
Labels: component: build process, PR: fix

#7550 fix(build): Fix sourcemaps, re-update metadata
  scripts/gulpfiles/build_tasks.js
  tests/scripts/check_metadata.sh
Labels: component: build process, PR: fix

#7553 chore(tests): Fix whitespace inconsistency
  tests/scripts/check_metadata.sh
Labels: component: tests, PR: chore

#7554 fix: style attribute for xml in ws factory
  demos/blockfactory/workspacefactory/wfactory_generator.js
Labels: PR: fix

#7559 fix: include loaders in gh-pages commits
  scripts/gulpfiles/git_tasks.js
Labels: PR: fix

#7560 fix: missing loaders for appengine deployment
  scripts/gulpfiles/appengine_tasks.js
Labels: PR: fix

#7561 fix: pasting with nothing selected
  core/shortcut_items.ts
Labels: PR: fix

#7548 chore: remove bump script from package.json
  package.json
Labels: PR: chore
