Repository google/blockly, pull requests merged in 2023-08, with the labels that each got.

#7344 fix: refactor CopyData interface to have the correct structure
  core/block_svg.ts
  core/clipboard.ts
  core/clipboard/block_paster.ts
  core/clipboard/registry.ts
  core/clipboard/workspace_comment_paster.ts
  core/interfaces/i_copyable.ts
  core/interfaces/i_paster.ts
  core/registry.ts
  core/workspace_comment_svg.ts
Labels: PR: fix

#7281 fix(build): support running Blocky locally on Windows machines
  package.json
  scripts/gulpfiles/build_tasks.js
Labels: PR: fix

#7351 chore(tests): fix delete tests
  tests/browser/test/delete_blocks_test.js
Labels: PR: chore

#7350 chore(tests): cleanup and toolbox drag tests
  tests/browser/test/basic_playground_test.js
  tests/browser/test/block_undo_test.js
  tests/browser/test/extensive_test.js
  tests/browser/test/field_edits_test.js
  tests/browser/test/test_setup.js
  tests/browser/test/toolbox_drag_test.js
Labels: PR: chore

#7348 feat: make ICopyable generic and update clipboard APIs
  core/block_svg.ts
  core/blockly.ts
  core/clipboard.ts
  core/clipboard/registry.ts
  core/common.ts
  core/interfaces/i_copyable.ts
  core/interfaces/i_paster.ts
  core/registry.ts
  core/shortcut_items.ts
  core/workspace_comment_svg.ts
  core/workspace_svg.ts
  tests/mocha/clipboard_test.js
  tests/mocha/index.html
Labels: PR: feature, deprecation

#7333 fix: removed X & Y from toolbox.ts and replaced movBy to moveTo
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
  core/utils/toolbox.ts
Labels: PR: fix

#7357 feat: have the trashcan hide scrollbars when the flyout opens
  core/trashcan.ts
Labels: PR: feature

#7230 chore: change the way we look for upstream remote
  scripts/gulpfiles/git_tasks.js
Labels: PR: chore

#7361 fix: Preemptively fix API change in NDB.
  appengine/storage.py
Labels: PR: fix

#7359 fix: dedeprecate render functions
  core/block_svg.ts
  core/workspace_svg.ts
Labels: PR: fix

#7364 feat: Insertion marker json deserialization 7316
  core/insertion_marker_manager.ts
Labels: PR: feature

#7349 fix: bumping copied objects
  core/clipboard/block_paster.ts
  core/clipboard/workspace_comment_paster.ts
  core/serialization/blocks.ts
  core/workspace_svg.ts
  tests/mocha/clipboard_test.js
  tests/mocha/test_helpers/events.js
Labels: PR: fix

#7376 fix: remove specific warning text
  core/block_svg.ts
  tests/mocha/block_test.js
Labels: PR: fix

#7352 chore: upgrade keyboard shortcuts and context menus to use non-deprecated APIs
  core/contextmenu.ts
  core/contextmenu_items.ts
  core/shortcut_items.ts
  core/shortcut_registry.ts
  tests/mocha/contextmenu_items_test.js
  tests/mocha/keydown_test.js
Labels: PR: chore

#7373 feat: Export shape interfaces from ConstantProvider
  core/renderers/common/block_rendering.ts
Labels: PR: feature

#7379 feat: merge copy paste work into develop
  core/block_svg.ts
  core/blockly.ts
  core/clipboard.ts
  core/clipboard/block_paster.ts
  core/clipboard/registry.ts
  core/clipboard/workspace_comment_paster.ts
  core/common.ts
  core/contextmenu.ts
  core/contextmenu_items.ts
  core/interfaces/i_copyable.ts
  core/interfaces/i_paster.ts
  core/registry.ts
  core/serialization/blocks.ts
  core/shortcut_items.ts
  core/shortcut_registry.ts
  core/workspace_comment_svg.ts
  core/workspace_svg.ts
  tests/mocha/clipboard_test.js
  tests/mocha/contextmenu_items_test.js
  tests/mocha/index.html
  tests/mocha/keydown_test.js
  tests/mocha/test_helpers/events.js
Labels: PR: feature

#6944 feat: Parse newlines in JSON message as row separators.
  core/block.ts
  core/inputs.ts
  core/inputs/end_row_input.ts
  core/inputs/input_types.ts
  core/renderers/common/info.ts
  core/renderers/geras/info.ts
  core/renderers/measurables/row.ts
  core/renderers/zelos/info.ts
  core/utils/parsing.ts
  core/xml.ts
  demos/blockfactory/block_definition_extractor.js
  demos/blockfactory/blocks.js
  demos/blockfactory/factory_utils.js
  demos/blockfactory/index.html
  tests/mocha/block_json_test.js
  tests/mocha/block_test.js
  tests/mocha/utils_test.js
Labels: PR: feature

#7384 fix: insertion marker's next blocks are real blocks
  core/insertion_marker_manager.ts
Labels: PR: fix

#7380 refactor(tests): Introduce loading shims, use in playgrounds
  closure/goog/goog.js
  scripts/gulpfiles/build_tasks.js
  scripts/helpers.js
  tests/multi_playground.html
  tests/playground.html
  tests/playgrounds/advanced_playground.html
  tests/playgrounds/shared_procedures.html
  tests/scripts/load.mjs
Labels: component: tests, PR: refactor

#7356 deprecate: workspace paste
  core/workspace_svg.ts
Labels: deprecation

#7398 fix(build): Fix import of parent chunk's shim
  scripts/gulpfiles/build_tasks.js
Labels: PR: fix

#7363 feat: add doFullSerialization support to blocks
  core/block.ts
  core/events/events_block_change.ts
  core/field.ts
  core/serialization/blocks.ts
Labels: PR: feature

#7399 fix(tests): wait for the workspace to render before starting test actions
  tests/browser/test/test_setup.js
Labels: PR: fix

#7400 fix: block change serialization
  core/events/events_block_change.ts
Labels: PR: fix

#7403 chore: fix docs in FieldImage
  core/field.ts
Labels: PR: chore

#7394 feat: add accessor for the workspace svg group
  core/workspace_svg.ts
Labels: PR: feature

#7404 chore: Update README.md
  README.md
Labels: PR: chore

#7405 chore: update PR template and add info for new contribs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/welcome_new_contributors.yml
Labels: PR: chore

#7407 fix: saveConnections listener not being disposed
  core/icons/mutator_icon.ts
Labels: PR: fix

#7408 chore: clean up measurement code in mini workspace bubble
  core/bubbles/mini_workspace_bubble.ts
Labels: PR: chore

#7409 feat: add custom context menu rendering
  core/contextmenu_registry.ts
Labels: PR: feature

#7402 chore(tests): set browser pause time in one place and enable toolbox tests
  tests/browser/test/basic_playground_test.js
  tests/browser/test/delete_blocks_test.js
  tests/browser/test/extensive_test.js
  tests/browser/test/field_edits_test.js
  tests/browser/test/mutator_test.js
  tests/browser/test/procedure_test.js
  tests/browser/test/test_setup.js
  tests/browser/test/toolbox_drag_test.js
Labels: PR: chore

#7392 feat: make generator quoting methods public
  core/generator.ts
  generators/dart/dart_generator.js
  generators/javascript/javascript_generator.js
  generators/lua/lua_generator.js
  generators/php/php_generator.js
  generators/python/python_generator.js
Labels: PR: feature

#6874 fix: Always draw dragged blocks atop others in the workspace.
  core/block_dragger.ts
  core/block_svg.ts
Labels: PR: fix

#7424 feat: make ordered argument optional for workspace functions
  core/workspace.ts
Labels: PR: feature

#7425 chore: make ordered argument optional for workspace_svg functions
  core/workspace_svg.ts
Labels: PR: chore

#7427 fix: do not create extra shadow blocks when mirroring events
  core/events/events_block_create.ts
  tests/mocha/event_block_create_test.js
Labels: PR: fix

#7423 fix: dragging blocks within a zoomed mutator
  core/bubbles/mini_workspace_bubble.ts
Labels: PR: fix

#7443 fix: Prevent raw content being served from storage.
  appengine/storage.js
  appengine/storage.py
Labels: PR: fix

#7434 chore: clean up mutator tests
  core/flyout_base.ts
  tests/browser/test/mutator_test.js
  tests/browser/test/test_setup.js
Labels: PR: chore

#7414 refactor(tests): Migrate generator tests to `import` shims; delete `bootstrap.js`
  core/main.js
  package.json
  scripts/gulpfiles/build_tasks.js
  scripts/gulpfiles/config.js
  scripts/migration/js2ts
  tests/bootstrap.js
  tests/bootstrap_done.mjs
  tests/bootstrap_helper.js
  tests/generators/index.html
  tests/generators/webdriver.js
  tests/mocha/index.html
Labels: component: tests, PR: refactor

#7445 feat: add getVariableName and getProcedureName to CodeGenerator
  core/generator.ts
  generators/dart/loops.js
  generators/dart/math.js
  generators/dart/procedures.js
  generators/dart/text.js
  generators/dart/variables.js
  generators/javascript/loops.js
  generators/javascript/math.js
  generators/javascript/procedures.js
  generators/javascript/text.js
  generators/javascript/variables.js
  generators/lua/loops.js
  generators/lua/math.js
  generators/lua/procedures.js
  generators/lua/text.js
  generators/lua/variables.js
  generators/php/loops.js
  generators/php/math.js
  generators/php/procedures.js
  generators/php/text.js
  generators/php/variables.js
  generators/python/loops.js
  generators/python/math.js
  generators/python/procedures.js
  generators/python/python_generator.js
  generators/python/text.js
  generators/python/variables.js
  tests/mocha/generator_test.js
Labels: PR: feature
