Repository google/blockly, pull requests merged in 2023-05, with the labels that each got.

#7021 chore: remove private underscores in `gesture.ts`
  core/gesture.ts
  tests/mocha/gesture_test.js
Labels: type: cleanup, PR: chore

#7033 fix: Update category.ts to produce valid "aria-level" attributes
  core/toolbox/category.ts
Labels: PR: fix

#7049 chore(tests): Stop testing on node.js v14
  .github/workflows/build.yml
Labels: component: tests, PR: chore

#7050 chore: test icon management
  tests/mocha/block_test.js
Labels: PR: chore

#7054 feat: add IIcon interface, and related interfaces
  core/field.ts
  core/interfaces/i_has_bubble.ts
  core/interfaces/i_icon.ts
  core/interfaces/i_serializable.ts
Labels: PR: feature

#7060 feat: add abstract icon class
  core/block_dragger.ts
  core/block_svg.ts
  core/blockly.ts
  core/comment.ts
  core/icon_old.ts
  core/icons/icon.ts
  core/mutator.ts
  core/renderers/measurables/icon.ts
  core/warning.ts
Labels: PR: feature

#7024 fix: switch most remaining render calls to queueRender
  blocks/procedures.js
  core/block_svg.ts
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
  core/mutator.ts
  core/rendered_connection.ts
  core/workspace_svg.ts
Labels: PR: fix

#7074 chore: remove sortrequires task
  gulpfile.js
  package-lock.json
  package.json
  scripts/gulpfiles/build_tasks.js
  scripts/gulpfiles/cleanup_tasks.js
Labels: type: cleanup, PR: chore

#7076 feat: Creating structure and providing simple test for Blockly automated functional test
  .github/workflows/browser_test.yml
  package.json
  tests/browser/.eslintrc.json
  tests/browser/test/.mocharc.js
  tests/browser/test/basic_block_factory_test.js
  tests/browser/test/basic_playground_test.js
Labels: PR: feature

#7069 fix: filter undone event groups before moving them to the redo stack
  core/events/utils.ts
Labels: PR: fix

#7077 chore: remove deprecated functionality for v10
  blocks/text.ts
  core/blockly.ts
  core/browser_events.ts
  core/events/events.ts
  core/events/events_abstract.ts
  core/events/events_block_base.ts
  core/events/events_block_change.ts
  core/events/events_block_create.ts
  core/events/events_block_delete.ts
  core/events/events_block_drag.ts
  core/events/events_block_move.ts
  core/events/events_bubble_open.ts
  core/events/events_click.ts
  core/events/events_comment_base.ts
  core/events/events_comment_change.ts
  core/events/events_comment_create.ts
  core/events/events_comment_move.ts
  core/events/events_marker_move.ts
  core/events/events_selected.ts
  core/events/events_theme_change.ts
  core/events/events_toolbox_item_select.ts
  core/events/events_trashcan_open.ts
  core/events/events_ui.ts
  core/events/events_var_base.ts
  core/events/events_var_create.ts
  core/events/events_var_delete.ts
  core/events/events_var_rename.ts
  core/events/events_viewport.ts
  core/events/utils.ts
  core/events/workspace_events.ts
  core/generator.ts
  core/icon_old.ts
  core/main.js
  core/mutator.ts
  core/renderers/common/block_rendering.ts
  core/renderers/common/debug.ts
  core/renderers/common/drawer.ts
  core/renderers/common/renderer.ts
  core/renderers/geras/drawer.ts
  core/renderers/zelos/drawer.ts
  core/touch.ts
  core/utils.ts
  core/utils/object.ts
  core/utils/style.ts
  core/utils/svg_math.ts
  core/utils/xml.ts
  core/xml.ts
  tests/generators/unittest_dart.js
  tests/generators/unittest_javascript.js
  tests/generators/unittest_lua.js
  tests/generators/unittest_php.js
  tests/generators/unittest_python.js
  tests/mocha/event_test.js
  tests/mocha/utils_test.js
Labels: type: cleanup, PR: chore

#7075 chore: update api-documenter and apply new patch
  package-lock.json
  package.json
  patches/@microsoft+api-documenter+7.22.4.patch
Labels: PR: chore

#7059 feat: add implementations for adding, removing, and getting icons
  core/block.ts
  core/block_svg.ts
  core/blockly.ts
  core/icons.ts
  core/icons/exceptions.ts
  tests/mocha/block_test.js
Labels: PR: feature

#7078 refactor!: delete debug renderer
  core/block_svg.ts
  core/renderers/common/block_rendering.ts
  core/renderers/common/debugger.ts
Labels: type: cleanup, breaking change, PR: refactor

#7070 fix!: re-remove block and workspace drag surfaces
  core/block_dragger.ts
  core/block_svg.ts
  core/blockly.ts
  core/bubble.ts
  core/bubble_dragger.ts
  core/css.ts
  core/inject.ts
  core/interfaces/i_block_dragger.ts
  core/interfaces/i_bubble.ts
  core/scrollbar.ts
  core/workspace_comment_svg.ts
  core/workspace_dragger.ts
  core/workspace_svg.ts
Labels: breaking change, PR: fix

#7071 feat: bubble ownership
  .eslintrc.js
  core/blockly.ts
  core/bubble_dragger.ts
  core/bubble_old.ts
  core/bubbles/bubble.ts
  core/comment.ts
  core/icon_old.ts
  core/interfaces/i_bubble.ts
  core/mutator.ts
  core/utils/rect.ts
  core/warning.ts
Labels: PR: feature

#7087 chore: add ability to test block factory and playground locally
  .github/workflows/browser_test.yml
  tests/browser/test/basic_block_factory_test.js
  tests/browser/test/basic_playground_test.js
Labels: PR: chore

#7080 feat: text bubble
  core/bubbles/text_bubble.ts
Labels: PR: feature

#7063 feat: add registering and serializing icons
  core/blockly.ts
  core/icons.ts
  core/icons/registry.ts
  core/registry.ts
  core/serialization/blocks.ts
  core/serialization/exceptions.ts
  core/serialization/registry.ts
  tests/mocha/icon_test.js
Labels: PR: feature

#7093 fix: Make props of ConnectionState optional
  core/serialization/blocks.ts
Labels: PR: fix

#7088 fix: bubbles not being dragged
  core/bubbles/bubble.ts
Labels: PR: fix

#7095 chore: test for procedures
  tests/browser/test/procedure_test.js
Labels: PR: chore

#7103 chore(generators): Migrate generators to ES Modules
  generators/dart.js
  generators/dart/all.js
  generators/dart/colour.js
  generators/dart/lists.js
  generators/dart/logic.js
  generators/dart/loops.js
  generators/dart/math.js
  generators/dart/procedures.js
  generators/dart/text.js
  generators/dart/variables.js
  generators/dart/variables_dynamic.js
  generators/javascript.js
  generators/javascript/all.js
  generators/javascript/colour.js
  generators/javascript/lists.js
  generators/javascript/logic.js
  generators/javascript/loops.js
  generators/javascript/math.js
  generators/javascript/procedures.js
  generators/javascript/text.js
  generators/javascript/variables.js
  generators/javascript/variables_dynamic.js
  generators/lua.js
  generators/lua/all.js
  generators/lua/colour.js
  generators/lua/lists.js
  generators/lua/logic.js
  generators/lua/loops.js
  generators/lua/math.js
  generators/lua/procedures.js
  generators/lua/text.js
  generators/lua/variables.js
  generators/lua/variables_dynamic.js
  generators/php.js
  generators/php/all.js
  generators/php/colour.js
  generators/php/lists.js
  generators/php/logic.js
  generators/php/loops.js
  generators/php/math.js
  generators/php/procedures.js
  generators/php/text.js
  generators/php/variables.js
  generators/php/variables_dynamic.js
  generators/python.js
  generators/python/all.js
  generators/python/colour.js
  generators/python/lists.js
  generators/python/logic.js
  generators/python/loops.js
  generators/python/math.js
  generators/python/procedures.js
  generators/python/text.js
  generators/python/variables.js
  generators/python/variables_dynamic.js
  scripts/gulpfiles/build_tasks.js
  scripts/migration/js2ts
Labels: component: generators, PR: chore

#7096 feat: mini workspace bubble
  core/blockly.ts
  core/bubbles/bubble.ts
  core/bubbles/mini_workspace_bubble.ts
  core/flyout_base.ts
  core/mutator.ts
  core/workspace.ts
Labels: PR: feature

#7100 fix: work on calling icon hooks
  core/block_svg.ts
  core/icons/icon.ts
  core/interfaces/i_icon.ts
  core/render_management.ts
  core/renderers/common/drawer.ts
  core/renderers/measurables/icon.ts
  tests/mocha/block_test.js
  tests/mocha/icon_test.js
Labels: PR: fix

#7101 fix: gestures handling icons
  core/block_svg.ts
  core/gesture.ts
  tests/mocha/icon_test.js
Labels: PR: fix

#7111 fix: collapsing blocks with children with icons
  core/interfaces/i_has_bubble.ts
  core/rendered_connection.ts
  core/renderers/measurables/icon.ts
  tests/mocha/block_test.js
  tests/mocha/icon_test.js
  tests/mocha/test_helpers/icon_mocks.js
Labels: PR: fix

#7116 fix: have inputs construct connections
  core/block.ts
  core/block_svg.ts
  core/inputs/dummy_input.ts
  core/inputs/input.ts
  core/inputs/statement_input.ts
  core/inputs/value_input.ts
Labels: PR: fix
