Repository google/blockly, pull requests merged in 2023-12, with the labels that each got.

#7661 chore: modify readme about how we want people to acquire Blockly
  scripts/package/README.md
Labels: PR: chore

#7691 fix: trashcan flyout opening on drag
  core/trashcan.ts
Labels: PR: fix

#7692 revert: "chore: Renable macos-latest build (#7640)"
  .github/workflows/browser_test.yml
  .github/workflows/build.yml
Labels: PR: revert

#7671 feat: added intermediate event change
  core/events/events_block_field_intermediate_change.ts
  tests/mocha/event_block_field_intermediate_change_test.js
Labels: PR: feature

#7690 fix: mutator coordinates not respecting flyout
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
Labels: PR: fix

#7695 fix: reenable showing empty flyouts
  core/flyout_base.ts
Labels: PR: fix

#7694 revert: "chore(deps): Bump jsdom from 22.1.0 to 23.0.0"
  package-lock.json
  package.json
Labels: PR: revert

#7672 feat: make fields and icons optionally clickable in flyouts
  core/field.ts
  core/gesture.ts
  core/icons/comment_icon.ts
  core/icons/icon.ts
  core/icons/mutator_icon.ts
  core/icons/warning_icon.ts
  core/interfaces/i_icon.ts
Labels: PR: feature

#7700 chore: Update metadata for 2023 Q4 release
  tests/scripts/check_metadata.sh
Labels: PR: chore

#7699 chore: Rollup of 2023 Q4 updates from TranslateWiki
  msg/json/ast.json
  msg/json/bcc.json
  msg/json/diq.json
  msg/json/mnw.json
  msg/json/yue.json
Labels: PR: chore

#7703 chore: Merge master back into develop following v10.3.0 release
  package-lock.json
  package.json
Labels: PR: chore

#7705 chore: Recompile messages
  msg/json/constants.json
  msg/json/en.json
  msg/json/qqq.json
  msg/json/synonyms.json
  msg/messages.js
  scripts/i18n/js_to_json.py
Labels: PR: chore

#7706 fix: updated mocha tests to display error messages
  tests/mocha/webdriver.js
Labels: PR: fix

#7698 feat: connection highlighting in geras and thrasos
  core/interfaces/i_connection_highlighter.ts
  core/rendered_connection.ts
  core/renderers/common/constants.ts
  core/renderers/common/drawer.ts
  core/renderers/common/i_path_object.ts
  core/renderers/common/info.ts
  core/renderers/common/path_object.ts
  core/renderers/common/renderer.ts
  scripts/migration/js2ts
Labels: PR: feature

#7720 fix: prevent flyout block highlighting during workspace drag
  core/flyout_base.ts
Labels: PR: fix

#7727 fix(generators): Fix generator typings
  scripts/gulpfiles/package_tasks.js
  typings/dart.d.ts
  typings/javascript.d.ts
  typings/lua.d.ts
  typings/php.d.ts
  typings/python.d.ts
Labels: component: generators, PR: fix
