Repository google/blockly, pull requests merged in 2023-02, with the labels that each got.

#6810 feat: Add support for centering on a block itself vs its stack.
  core/workspace_svg.ts
  tests/mocha/workspace_svg_test.js
Labels: PR: feature

#6813 chore(deps): Remove `calcdeps.py`
  closure/bin/calcdeps.py
Labels: PR: dependencies, PR: chore

#6799 chore: update the other issue templates to forms
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: PR: chore

#6785 chore: Remove some more uses of AnyDuringMigration
  core/events/events_comment_move.ts
  core/field_colour.ts
  core/field_image.ts
  core/interfaces/i_copyable.ts
  core/interfaces/i_selectable_toolbox_item.ts
  core/toolbox/collapsible_category.ts
  core/toolbox/toolbox.ts
  core/utils/toolbox.ts
  core/workspace.ts
  core/workspace_comment.ts
  core/workspace_comment_svg.ts
  tests/mocha/workspace_comment_test.js
Labels: PR: chore

#6800 fix: don't splice into unmovable stacks
  core/connection_checker.ts
  tests/mocha/connection_checker_test.js
Labels: PR: fix

#6825 fix(tests): Use `build/msg/en.js` instead of `msg/messages.js`
  tests/bootstrap_helper.js
  tests/playgrounds/shared_procedures.html
Labels: component: tests, PR: fix

#6818 refactor: Remove last remaining circular `import` in `core/`
  appengine/storage.js
  blocks/lists.js
  closure/goog/base.js
  core/events/events_block_change.ts
  core/events/events_block_create.ts
  core/events/events_block_delete.ts
  core/events/events_comment_create.ts
  core/events/events_comment_delete.ts
  core/field.ts
  core/flyout_base.ts
  core/procedures.ts
  core/serialization/blocks.ts
  core/utils/toolbox.ts
  core/utils/xml.ts
  core/variables.ts
  core/xml.ts
  demos/blockfactory/app_controller.js
  demos/blockfactory/block_library_storage.js
  demos/blockfactory/factory.js
  demos/blockfactory/standard_categories.js
  demos/blockfactory/workspacefactory/wfactory_controller.js
  demos/blockfactory_old/factory.js
  demos/code/code.js
  scripts/migration/renamings.json5
  tests/generators/index.html
  tests/mocha/block_test.js
  tests/mocha/blocks/procedures_test.js
  tests/mocha/comment_deserialization_test.js
  tests/mocha/comment_test.js
  tests/mocha/connection_checker_test.js
  tests/mocha/connection_test.js
  tests/mocha/event_block_change_test.js
  tests/mocha/event_test.js
  tests/mocha/field_test.js
  tests/mocha/flyout_test.js
  tests/mocha/input_test.js
  tests/mocha/insertion_marker_test.js
  tests/mocha/jso_serialization_test.js
  tests/mocha/serializer_test.js
  tests/mocha/test_helpers/procedures.js
  tests/mocha/test_helpers/serialization.js
  tests/mocha/test_helpers/toolbox_definitions.js
  tests/mocha/test_helpers/workspace.js
  tests/mocha/trashcan_test.js
  tests/mocha/workspace_svg_test.js
  tests/mocha/xml_test.js
  tests/node/run_node_test.js
  tests/playground.html
Labels: PR: chore, PR: refactor

#6811 refactor: Use the field registry to instantiate fields in block definitions.
  blocks/lists.js
  blocks/procedures.js
  blocks/text.js
Labels: PR: refactor

#6827 fix: Fire deletion events when clearing variables.
  core/variable_map.ts
  scripts/gulpfiles/release_tasks.js
Labels: PR: fix

#6826 chore: Make dropdownDispose available for plugins.
  core/field_dropdown.ts
Labels: PR: chore

#6831 fix: move deprecation warning to correct fromJson
  core/events/events_abstract.ts
Labels: PR: fix

#6835 chore(build,tests): Remove obsolete kludges / config options
  tests/bootstrap_helper.js
  tsconfig.json
Labels: component: tests, component: build process, PR: chore

#6833 chore: fix isNameUsed not fully respecting the procedure map
  core/procedures.ts
  tests/mocha/blocks/procedures_test.js
Labels: PR: chore

#6837 chore: Create script to help with `.js` -> `.ts` migration
  scripts/migration/js2ts
Labels: PR: chore

#6838 feat: updated flyout button to set border radius via static variable
  core/flyout_button.ts
Labels: PR: feature

#6844 chore: fixup dialog deprecation warnings
  core/main.js
Labels: PR: chore

#6845 refactor: Use input type=number for field_number.ts
  core/css.ts
  core/field_number.ts
Labels: PR: refactor

#6836 feat(build): Run `tsc` on `blocks/` and `generators/`
  scripts/gulpfiles/build_tasks.js
  tsconfig.json
Labels: component: build process, PR: feature

#6847 fix: serializing disabled interactions
  core/block.ts
  core/serialization/blocks.ts
  tests/mocha/serializer_test.js
Labels: PR: fix

#6832 fix: variable events not deserializing properly
  core/events/events_var_create.ts
  core/events/events_var_delete.ts
  tests/mocha/event_var_create_test.js
  tests/mocha/event_var_delete_test.js
Labels: PR: fix

#6863 refactor: Remove more uses of AnyDuringMigration
  core/block.ts
  core/block_svg.ts
  core/connection.ts
  core/events/events_block_move.ts
  core/field_angle.ts
  core/inject.ts
  core/keyboard_nav/ast_node.ts
  core/names.ts
  core/theme_manager.ts
  core/xml.ts
  tests/mocha/workspace_svg_test.js
Labels: PR: refactor
