Repository google/blockly, pull requests merged in 2023-06, with the labels that each got.

#7127 fix(build): Fix path issue on Windows
  scripts/gulpfiles/build_tasks.js
Labels: component: build process, PR: fix

#7128 fix!: refactor comment icon
  .eslintrc.js
  core/block.ts
  core/block_svg.ts
  core/blockly.ts
  core/bubbles/textinput_bubble.ts
  core/comment.ts
  core/icons.ts
  core/icons/comment_icon.ts
  core/icons/icon.ts
  core/icons/icon_types.ts
  core/interfaces/i_serializable.ts
  core/serialization/blocks.ts
  core/xml.ts
  scripts/migration/renamings.json5
  tests/mocha/block_test.js
  tests/mocha/comment_deserialization_test.js
  tests/mocha/comment_test.js
  tests/mocha/jso_serialization_test.js
  tests/mocha/xml_test.js
Labels: breaking change, PR: fix

#7115 fix!: refactor mutator icon
  blocks/lists.ts
  blocks/logic.js
  blocks/procedures.js
  blocks/text.ts
  core/block.ts
  core/block_svg.ts
  core/blockly.ts
  core/bubbles/mini_workspace_bubble.ts
  core/connection.ts
  core/events/events_block_change.ts
  core/extensions.ts
  core/icons.ts
  core/icons/icon_types.ts
  core/icons/mutator_icon.ts
  core/mutator.ts
  core/procedures.ts
  core/workspace.ts
  core/workspace_svg.ts
  demos/blockfactory/blocks.js
  demos/blockfactory_old/blocks.js
  scripts/migration/renamings.json5
  tests/mocha/blocks/procedures_test.js
  tests/mocha/mutator_test.js
Labels: breaking change, PR: fix

#7149 fix: Allow for unattached elements during inject call
  core/inject.ts
Labels: PR: fix

#7150 refactor(generators)!: `CodeGenerator` per-block-type generator function dictionary
  core/generator.ts
  generators/dart/colour.js
  generators/dart/lists.js
  generators/dart/logic.js
  generators/dart/loops.js
  generators/dart/math.js
  generators/dart/procedures.js
  generators/dart/text.js
  generators/dart/variables.js
  generators/dart/variables_dynamic.js
  generators/javascript/colour.js
  generators/javascript/lists.js
  generators/javascript/logic.js
  generators/javascript/loops.js
  generators/javascript/math.js
  generators/javascript/procedures.js
  generators/javascript/text.js
  generators/javascript/variables.js
  generators/javascript/variables_dynamic.js
  generators/lua/colour.js
  generators/lua/lists.js
  generators/lua/logic.js
  generators/lua/loops.js
  generators/lua/math.js
  generators/lua/procedures.js
  generators/lua/text.js
  generators/lua/variables.js
  generators/lua/variables_dynamic.js
  generators/php/colour.js
  generators/php/lists.js
  generators/php/logic.js
  generators/php/loops.js
  generators/php/math.js
  generators/php/procedures.js
  generators/php/text.js
  generators/php/variables.js
  generators/php/variables_dynamic.js
  generators/python/colour.js
  generators/python/lists.js
  generators/python/logic.js
  generators/python/loops.js
  generators/python/math.js
  generators/python/procedures.js
  generators/python/text.js
  generators/python/variables.js
  generators/python/variables_dynamic.js
  tests/mocha/generator_test.js
  tests/mocha/insertion_marker_test.js
Labels: component: generators, breaking change, PR: refactor

#7142 chore: fix hiding bubbles on collapse
  core/icons/icon.ts
Labels: PR: chore

#7153 refactor(generators): Introduce `JavascriptGenerator` class, `Order` enum
  generators/javascript.js
  generators/javascript/colour.js
  generators/javascript/lists.js
  generators/javascript/logic.js
  generators/javascript/loops.js
  generators/javascript/math.js
  generators/javascript/procedures.js
  generators/javascript/text.js
  generators/javascript/variables.js
  generators/javascript/variables_dynamic.js
Labels: component: generators, PR: refactor

#7156 chore(generators): Comment tweak for PR #7153
  generators/javascript.js
Labels: component: generators, PR: chore

#7132 feat: add types for accessing icons.
  core/block.ts
  core/block_svg.ts
  core/events/events_block_change.ts
  core/icons.ts
  core/icons/comment_icon.ts
  core/icons/icon.ts
  core/icons/icon_types.ts
  core/icons/mutator_icon.ts
  core/icons/registry.ts
  core/icons/warning_icon.ts
  core/interfaces/i_icon.ts
  core/serialization/blocks.ts
  core/xml.ts
  tests/mocha/block_test.js
  tests/mocha/test_helpers/icon_mocks.js
Labels: PR: feature

#7155 chore!: remove angle field from core
  core/blockly.ts
  core/field_angle.ts
  tests/mocha/field_angle_test.js
  tests/mocha/index.html
  tests/mocha/serializer_test.js
  tests/mocha/xml_test.js
Labels: breaking change, PR: chore

#7141 fix: remove old icon handling code
  core/block_dragger.ts
  core/block_svg.ts
  core/contextmenu_items.ts
  core/icon_old.ts
  core/icons/icon.ts
  core/render_management.ts
  core/rendered_connection.ts
  core/renderers/common/drawer.ts
  core/renderers/common/info.ts
  core/renderers/geras/drawer.ts
  core/renderers/measurables/icon.ts
  core/renderers/zelos/drawer.ts
  core/serialization/blocks.ts
Labels: PR: fix

#7160 refactor(generators): Introduce `DartGenerator` class, `Order` enum
  generators/dart.js
  generators/dart/colour.js
  generators/dart/lists.js
  generators/dart/logic.js
  generators/dart/loops.js
  generators/dart/math.js
  generators/dart/procedures.js
  generators/dart/text.js
  generators/dart/variables.js
  generators/dart/variables_dynamic.js
Labels: component: generators, PR: refactor

#7163 refactor(generators): Introduce `PythonGenerator` class, `Order` enum
  generators/python.js
  generators/python/colour.js
  generators/python/lists.js
  generators/python/logic.js
  generators/python/loops.js
  generators/python/math.js
  generators/python/procedures.js
  generators/python/text.js
  generators/python/variables.js
  generators/python/variables_dynamic.js
Labels: component: generators, PR: refactor

#7161 refactor(generators): Introduce `LuaGenerator` class, `Order` enum
  generators/lua.js
  generators/lua/colour.js
  generators/lua/lists.js
  generators/lua/logic.js
  generators/lua/loops.js
  generators/lua/math.js
  generators/lua/procedures.js
  generators/lua/text.js
  generators/lua/variables.js
  generators/lua/variables_dynamic.js
Labels: component: generators, PR: refactor

#7025 fix: remove input type from number field
  core/field_number.ts
Labels: PR: fix

#7166 chore(generators): Fix nits
  core/generator.ts
  generators/dart.js
  generators/javascript.js
  generators/python.js
Labels: PR: chore

#7168 refactor(generators)!: Pass `this` `CodeGenerator` to individual generator functions
  core/generator.ts
  generators/dart/colour.js
  generators/dart/lists.js
  generators/dart/logic.js
  generators/dart/loops.js
  generators/dart/math.js
  generators/dart/procedures.js
  generators/dart/text.js
  generators/dart/variables.js
  generators/dart/variables_dynamic.js
  generators/javascript/colour.js
  generators/javascript/lists.js
  generators/javascript/logic.js
  generators/javascript/loops.js
  generators/javascript/math.js
  generators/javascript/procedures.js
  generators/javascript/text.js
  generators/javascript/variables.js
  generators/lua/colour.js
  generators/lua/lists.js
  generators/lua/logic.js
  generators/lua/loops.js
  generators/lua/math.js
  generators/lua/procedures.js
  generators/lua/text.js
  generators/lua/variables.js
  generators/php/colour.js
  generators/php/lists.js
  generators/php/logic.js
  generators/php/loops.js
  generators/php/math.js
  generators/php/procedures.js
  generators/php/text.js
  generators/php/variables.js
  generators/php/variables_dynamic.js
  generators/python/colour.js
  generators/python/lists.js
  generators/python/logic.js
  generators/python/loops.js
  generators/python/math.js
  generators/python/procedures.js
  generators/python/text.js
  generators/python/variables.js
  generators/python/variables_dynamic.js
Labels: component: generators, breaking change, PR: refactor

#7169 refactor(build)!: Provide all generator exports when loaded as script
  scripts/gulpfiles/build_tasks.js
Labels: component: generators, breaking change, PR: refactor

#7171 refactor(tests): Update `bootstrap.js` to better support generator chunks
  scripts/gulpfiles/build_tasks.js
  tests/bootstrap.js
  tests/bootstrap_helper.js
  tests/generators/index.html
  tests/mocha/index.html
  tests/playground.html
  tests/playgrounds/advanced_playground.html
  tests/playgrounds/shared_procedures.html
Labels: component: tests, PR: refactor

#7172 fix: update disabled status after rendering
  core/block_svg.ts
  tests/mocha/block_test.js
Labels: PR: fix

#7151 feat: use new intermediate block change event for field edits, normal block change event for closing editor. #7105
  core/events/events.ts
  core/events/events_block_field_intermediate_change.ts
  core/events/utils.ts
  core/field.ts
  core/field_angle.ts
  core/field_input.ts
  core/procedures.ts
  tests/mocha/event_block_field_intermediate_change_test.js
  tests/mocha/event_test.js
  tests/mocha/index.html
Labels: PR: feature

#7159 fix: icon exports
  core/blockly.ts
  core/icons.ts
  scripts/migration/renamings.json5
Labels: PR: fix

#7165 fix: input exports
  .eslintrc.js
  blocks/lists.ts
  blocks/text.ts
  core/block.ts
  core/blockly.ts
  core/inputs.ts
  core/inputs/align.ts
  core/inputs/input.ts
  core/renderers/common/info.ts
  core/renderers/zelos/info.ts
  scripts/gulpfiles/build_tasks.js
  scripts/migration/renamings.json5
  tests/mocha/block_json_test.js
  tsdoc.json
Labels: PR: fix, deprecation

#7003 refactor(blocks): Migrate `blocks/logic.js` to TypeScript
  blocks/logic.ts
Labels: PR: refactor

#7178 fix(tests): Fix compressed mode loading
  scripts/gulpfiles/build_tasks.js
  tests/bootstrap.js
Labels: component: tests, PR: fix

#7186 fix(build): Fix GitHub pages & deployment task
  _config.yml
  scripts/gulpfiles/git_tasks.js
Labels: component: build process, PR: fix

#7188 chore: allow themes to override eachother
  core/theme.ts
Labels: PR: chore

#7190 chore: add top-level inline docs to bubbles icons and inputs
  core/bubbles/bubble.ts
  core/bubbles/mini_workspace_bubble.ts
  core/bubbles/text_bubble.ts
  core/bubbles/textinput_bubble.ts
  core/icons/comment_icon.ts
  core/icons/exceptions.ts
  core/icons/icon.ts
  core/icons/icon_types.ts
  core/icons/mutator_icon.ts
  core/icons/warning_icon.ts
  core/inputs/input.ts
Labels: PR: chore

#7189 fix: bubble exports
  core/blockly.ts
  core/bubble_old.ts
  core/bubbles.ts
  scripts/migration/renamings.json5
Labels: PR: fix

#7194 fix(blocks): Mark previously-`@private` methods `@internal`
  blocks/logic.ts
  blocks/text.ts
Labels: component: library blocks, PR: fix

#7192 refactor(blocks): Migrate `blocks/procedures.js` to TypeScript
  blocks/procedures.ts
Labels: component: library blocks, PR: refactor

#7193 refactor(blocks): Migrate `blocks/blocks.js` to TypeScript
  blocks/blocks.js
  blocks/blocks.ts
  scripts/gulpfiles/build_tasks.js
Labels: component: library blocks, PR: refactor

#7195 chore: make MutatorIcon.prototype.getWorkspace public
  core/icons/mutator_icon.ts
Labels: PR: chore

#7196 refactor(tests): Migrate mocha tests from `goog.require` to `import`
  tests/mocha/field_multilineinput_test.js
  tests/mocha/generator_test.js
Labels: component: tests, PR: refactor

#7197 fix(build): Correct typos in PR #7169
  scripts/gulpfiles/build_tasks.js
Labels: component: build process, PR: fix

#7202 fix: properly pass the block to the icon constructor in blockfactory blocks
  demos/blockfactory/blocks.js
Labels: PR: fix

#7200 fix: Utilize getIcon instead of getCommentIcon in tests
  tests/mocha/comment_deserialization_test.js
  tests/mocha/contextmenu_items_test.js
  tests/mocha/xml_test.js
Labels: PR: fix

#7203 fix: export the IIcon and related interfaces
  core/blockly.ts
Labels: PR: fix

#7211 fix(demos): Update BlockFactory generator stub generator
  demos/blockfactory/factory_utils.js
Labels: component: demos, PR: fix

#7213 fix(demos): Update code demo to use new script import names for generators
  demos/code/code.js
Labels: component: demos, PR: fix

#7214 chore: add setVisible
  core/icons/icon.ts
Labels: PR: chore

#7201 chore: remove js-green-licenses
  gulpfile.js
  package-lock.json
  package.json
  scripts/gulpfiles/license_tasks.js
Labels: PR: chore

#7217 chore: Rollup of 2023 Q2 updates from TranslateWiki
  msg/json/be.json
  msg/json/bg.json
  msg/json/br.json
  msg/json/fr.json
  msg/json/hi.json
  msg/json/inh.json
  msg/json/ja.json
  msg/json/kn.json
  msg/json/ky.json
  msg/json/lb.json
  msg/json/lt.json
  msg/json/nb.json
  msg/json/skr-arab.json
  msg/json/xmf.json
  msg/json/zh-hans.json
Labels: PR: chore

#7220 chore(messages): Update messages
  msg/json/constants.json
  msg/json/en.json
  msg/json/qqq.json
  msg/json/synonyms.json
  msg/messages.js
Labels: PR: chore

#7219 chore: update renamings file for new release
  scripts/migration/renamings.json5
Labels: PR: chore

#7223 chore: Merge master back into develop following v10.0.0 release
  package-lock.json
  package.json
Labels: PR: chore

#7228 chore: delete unused function getFirstStatementConnection
  core/block.ts
  core/block_svg.ts
Labels: type: cleanup, PR: chore

#7229 chore: delete unused fuction clearTransformAttributes_
  core/block_svg.ts
Labels: type: cleanup, PR: chore

#7216 chore: delete drag surface files
  core/block_drag_surface.ts
  core/workspace_drag_surface_svg.ts
Labels: PR: chore

#7231 chore: update app engine version names
  scripts/gulpfiles/appengine_tasks.js
Labels: PR: chore
