Repository google/blockly, pull requests merged in 2023-01, with the labels that each got.

#6671 feat: refactor procedure blocks
  blocks/procedures.js
Labels: PR: feature

#6672 feat: procedure blocks update models
  blocks/procedures.js
  core/interfaces/i_procedure_block.ts
  core/procedures.ts
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_model.ts
  tests/mocha/blocks/procedures_test.js
Labels: PR: feature

#6673 feat: procedure def blocks respond to models
  blocks/procedures.js
  tests/mocha/blocks/procedures_test.js
Labels: PR: feature

#6706 feat: procedure defs deserialize models
  blocks/procedures.js
  core/procedures/observable_parameter_model.ts
  tests/mocha/blocks/procedures_test.js
Labels: PR: feature

#6718 feat: procedure callers respond to models
  blocks/procedures.js
  core/procedures/update_procedures.ts
  tests/mocha/blocks/procedures_test.js
  tests/mocha/test_helpers/procedures.js
  tests/mocha/test_helpers/serialization.js
Labels: PR: feature

#6721 fix: undoing and redoing parameter events
  blocks/procedures.js
  core/procedures/observable_parameter_model.ts
  core/serialization/procedures.ts
  tests/mocha/blocks/procedures_test.js
  tests/mocha/jso_serialization_test.js
  tests/mocha/webdriver.js
Labels: PR: fix

#6722 fix: undoing and redoing deleting procedures
  blocks/procedures.js
  core/procedures.ts
  tests/mocha/blocks/procedures_test.js
Labels: PR: fix

#6619 chore(tests): Enable testing on node.js v18.x on GitHub CI
  .github/workflows/build.yml
  package.json
  tests/scripts/setup_linux_env.sh
  tests/scripts/setup_osx_env.sh
Labels: component: tests, PR: chore

#6739 fix: change assertFieldValue in test helpers to use deepEqual
  tests/mocha/field_angle_test.js
  tests/mocha/field_number_test.js
  tests/mocha/test_helpers/fields.js
Labels: PR: fix

#6736 chore: delete old proc data code
  blocks/procedures.js
  core/procedures/observable_procedure_model.ts
  core/procedures/update_procedures.ts
  tests/mocha/blocks/procedures_test.js
  tests/mocha/test_helpers/serialization.js
Labels: PR: chore

#6751 fix: correct docs for flyout metrics
  blocks/procedures.js
  core/interfaces/i_metrics_manager.ts
  core/metrics_manager.ts
Labels: PR: fix

#6639 fix: replace 'AnyDuringMigration' for `core/field.ts` value functions
  core/block.ts
  core/field.ts
  core/field_angle.ts
  core/field_checkbox.ts
  core/field_colour.ts
  core/field_dropdown.ts
  core/field_image.ts
  core/field_input.ts
  core/field_label.ts
  core/field_multilineinput.ts
  core/field_number.ts
  core/field_textinput.ts
  core/field_variable.ts
  core/gesture.ts
  core/utils/sentinel.ts
Labels: PR: fix

#6752 fix: export Abstract event class directly
  core/events/events.ts
Labels: PR: fix

#6745 chore: refactor procedures namespace
  blocks/procedures.js
  core/interfaces/i_procedure_block.ts
  core/procedures.ts
  tests/mocha/procedure_map_test.js
Labels: PR: chore

#6750 fix: undoing pasting procedure callers that create defs
  blocks/procedures.js
Labels: PR: fix

#6746 fix: proc json serialization
  blocks/procedures.js
  tests/mocha/blocks/procedures_test.js
  tests/mocha/test_helpers/serialization.js
Labels: PR: fix

#6763 fix: CI exits properly after failure
  scripts/gulpfiles/test_tasks.js
Labels: PR: fix

#6766 chore: fix closure type errors
  blocks/procedures.js
Labels: PR: chore

#6765 chore: add docs link to generator error
  core/generator.ts
Labels: PR: chore

#6747 fix: copying and pasting procedure definitions
  blocks/procedures.js
  core/interfaces/i_procedure_block.ts
  tests/mocha/blocks/procedures_test.js
Labels: PR: fix

#6764 fix(deps): Don't use global variables for jsdom injection in `scripts/package/node/core.js` and `core/utils/xml.ts`
  core/utils/xml.ts
  scripts/package/node/core.js
Labels: PR: fix

#6770 fix(tests): Have `npm start` run a full build
  package.json
Labels: component: build process, PR: fix

#6755 chore: make inline docs for events informative
  core/events/events_abstract.ts
  core/events/events_block_base.ts
  core/events/events_block_change.ts
  core/events/events_block_create.ts
  core/events/events_block_delete.ts
  core/events/events_block_drag.ts
  core/events/events_block_move.ts
  core/events/events_bubble_open.ts
  core/events/events_click.ts
  core/events/events_comment_base.ts
  core/events/events_comment_change.ts
  core/events/events_comment_create.ts
  core/events/events_comment_delete.ts
  core/events/events_comment_move.ts
  core/events/events_marker_move.ts
  core/events/events_procedure_base.ts
  core/events/events_procedure_change_return.ts
  core/events/events_procedure_create.ts
  core/events/events_procedure_delete.ts
  core/events/events_procedure_enable.ts
  core/events/events_procedure_parameter_base.ts
  core/events/events_procedure_parameter_create.ts
  core/events/events_procedure_parameter_delete.ts
  core/events/events_procedure_parameter_rename.ts
  core/events/events_procedure_rename.ts
  core/events/events_selected.ts
  core/events/events_theme_change.ts
  core/events/events_toolbox_item_select.ts
  core/events/events_trashcan_open.ts
  core/events/events_var_base.ts
  core/events/events_var_create.ts
  core/events/events_var_delete.ts
  core/events/events_var_rename.ts
  core/events/events_viewport.ts
  core/events/workspace_events.ts
Labels: PR: chore

#6776 fix: Increase generator test timeout
  scripts/gulpfiles/test_tasks.js
  tests/generators/webdriver.js
Labels: PR: fix

#6771 fix: Make metadata tests more resilient.
  scripts/gulpfiles/test_tasks.js
  tests/scripts/check_metadata.sh
  tests/scripts/update_metadata.sh
Labels: PR: fix

#6779 chore: reorganize CI tests and add timeout
  .github/workflows/build.yml
  .github/workflows/check_clang_format.yml
Labels: PR: chore

#6780 chore: add a pretty summary to CI
  scripts/gulpfiles/test_tasks.js
Labels: PR: chore

#6782 refactor: Don't use skew_ and translate_ attributes on SVGs to animate blocks.
  core/block_animations.ts
  core/block_svg.ts
  core/workspace_comment_svg.ts
Labels: PR: refactor

#6769 chore: reexport procedure related symbols
  blocks/procedures.js
  core/interfaces/i_procedure_block.ts
  core/procedures.ts
Labels: PR: chore

#6758 refactor: Remove block and workspace drag surfaces
  core/block_drag_surface.ts
  core/block_dragger.ts
  core/block_svg.ts
  core/blockly.ts
  core/bubble.ts
  core/bubble_dragger.ts
  core/css.ts
  core/inject.ts
  core/interfaces/i_block_dragger.ts
  core/interfaces/i_bubble.ts
  core/scrollbar.ts
  core/workspace_comment_svg.ts
  core/workspace_drag_surface_svg.ts
  core/workspace_dragger.ts
  core/workspace_svg.ts
Labels: breaking change, PR: refactor

#6794 chore: revert changes to procedure blocks
  blocks/procedures.js
  tests/mocha/blocks/procedures_test.js
Labels: PR: chore

#6795 chore: revert procedure events
  core/events/events.ts
  core/events/events_procedure_base.ts
  core/events/events_procedure_change_return.ts
  core/events/events_procedure_create.ts
  core/events/events_procedure_delete.ts
  core/events/events_procedure_enable.ts
  core/events/events_procedure_parameter_base.ts
  core/events/events_procedure_parameter_create.ts
  core/events/events_procedure_parameter_delete.ts
  core/events/events_procedure_parameter_rename.ts
  core/events/events_procedure_rename.ts
  core/events/utils.ts
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_map.ts
  core/procedures/observable_procedure_model.ts
  tests/mocha/event_procedure_change_return_test.js
  tests/mocha/event_procedure_create_test.js
  tests/mocha/event_procedure_delete_test.js
  tests/mocha/event_procedure_enable_test.js
  tests/mocha/event_procedure_parameter_create_test.js
  tests/mocha/event_procedure_parameter_delete_test.js
  tests/mocha/event_procedure_parameter_rename_test.js
  tests/mocha/event_procedure_rename_test.js
  tests/mocha/index.html
  tests/mocha/procedure_map_test.js
Labels: PR: chore

#6796 chore: delete procedure data models
  core/procedures.ts
  core/procedures/observable_parameter_model.ts
  core/procedures/observable_procedure_model.ts
  core/serialization/procedures.ts
  tests/mocha/jso_serialization_test.js
  tests/mocha/procedure_map_test.js
  tests/mocha/test_helpers/procedures.js
Labels: PR: chore

#6797 chore: clean up leftover procedure-related things in core
  core/blockly.ts
  core/observable_procedure_map.ts
  core/procedures.ts
  core/procedures/update_procedures.ts
  core/workspace.ts
  tests/mocha/procedure_map_test.js
  tests/mocha/test_helpers/procedures.js
Labels: PR: chore

#6773 fix(build): Fix event tests, improve `buildDeps`
  scripts/gulpfiles/build_tasks.js
  tests/mocha/event_marker_move_test.js
  tests/mocha/event_selected_test.js
Labels: component: tests, component: build process, PR: fix

#6798 chore: convert bug issue template to form
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: PR: chore
