Repository google/blockly, pull requests merged in 2023-10, with the labels that each got.

#7505 fix: comment change event fires block change event
  core/block.ts
  core/icons/comment_icon.ts
Labels: PR: fix

#7584 fix: colour from colour picker not being updated
  core/field_colour.ts
Labels: PR: fix

#7572 fix: recreate dropdown div
  core/dropdowndiv.ts
  core/tooltip.ts
  core/widgetdiv.ts
Labels: PR: fix

#7590 fix: bring block to front when icon clicked
  core/gesture.ts
Labels: PR: fix

#7558 chore: fix shouldStartNewRow docs and param names
  core/renderers/common/info.ts
  core/renderers/zelos/info.ts
Labels: PR: chore

#7555 fix(generators): Modify type signature of `forBlock`
  core/generator.ts
Labels: component: generators, PR: fix

#7598 fix: text join block warning when using block-plus-minus plugin
  blocks/text.ts
Labels: PR: fix

#7507 fix: widget positioning
  core/block_dragger.ts
  core/block_svg.ts
  core/field.ts
  core/field_input.ts
  core/render_management.ts
  core/rendered_connection.ts
  tests/mocha/render_management_test.js
Labels: PR: fix

#7602 refactor(generators): Migrate JavaScript generators to TypeScript
  .prettierignore
  blocks/lists.ts
  blocks/loops.ts
  blocks/procedures.ts
  blocks/text.ts
  generators/javascript.ts
  generators/javascript/colour.ts
  generators/javascript/javascript_generator.ts
  generators/javascript/lists.ts
  generators/javascript/logic.js
  generators/javascript/logic.ts
  generators/javascript/loops.ts
  generators/javascript/math.ts
  generators/javascript/procedures.ts
  generators/javascript/text.ts
  generators/javascript/variables.ts
  generators/javascript/variables_dynamic.ts
Labels: component: generators, PR: refactor

#7608 feat: add tooltip support for icons
  core/icons/icon.ts
Labels: PR: feature

#7622 fix: Can mutate blocks in readOnly workspace
  core/icons/mutator_icon.ts
Labels: PR: fix
