Repository google/blockly, pull requests merged in 2023-07, with the labels that each got.

#7199 fix: set flyout visbility on calling setExpanded
  core/toolbox/collapsible_category.ts
Labels: PR: fix

#7249 fix: Restore `HSV_SATURATION` and `HSV_VALUE` accessors and deprecate
  core/main.js
Labels: PR: fix, deprecation

#7254 feat(test): add helper functions for getting selected block and block…
  tests/browser/test/procedure_test.js
  tests/browser/test/test_setup.js
Labels: PR: feature

#7255 chore: add test helpers for getting blocks from the toolbox
  tests/browser/test/procedure_test.js
  tests/browser/test/test_setup.js
Labels: PR: chore

#7257 chore: fixup flyout test helpers
  tests/browser/test/procedure_test.js
  tests/browser/test/test_setup.js
Labels: PR: chore

#7258 chore: add test helpers for connecting blocks
  core/rendered_connection.ts
  core/utils/svg_math.ts
  tests/browser/test/procedure_test.js
  tests/browser/test/test_setup.js
Labels: PR: chore

#7260 fix(tests): Make test `import`s correct and more consistent
  tests/mocha/comment_deserialization_test.js
  tests/mocha/contextmenu_items_test.js
  tests/mocha/field_multilineinput_test.js
  tests/mocha/generator_test.js
  tests/mocha/xml_test.js
Labels: component: tests, PR: fix

#7261 chore: add css classes to individual zoom controls
  core/zoom_controls.ts
Labels: PR: chore

#7264 fix: disposing workspace comments.
  core/workspace_comment_svg.ts
  tests/mocha/workspace_comment_test.js
Labels: PR: fix

#7262 feat(tests): add right click tests and helpers
  tests/browser/test/basic_playground_test.js
  tests/browser/test/procedure_test.js
  tests/browser/test/test_setup.js
Labels: PR: feature

#7280 chore(tests): Add documentation to browser test helper functions
  tests/browser/.eslintrc.json
  tests/browser/test/test_setup.js
Labels: PR: chore

#7282 chore: Added test for loading json and interblock deletion
  tests/browser/test/extensive_test.js
  tests/browser/test/test_setup.js
Labels: PR: chore

#7284 chore(tests): Add tests for adding and removing comments
  tests/browser/test/basic_playground_test.js
Labels: PR: chore

#7289 fix: add compose and decompose errors to mutator icon
  core/icons/mutator_icon.ts
Labels: PR: fix

#7291 test: Basic Blocks: verify drag blocks works properly
  tests/browser/test/basic_block_factory_test.js
  tests/browser/test/basic_block_test.js
  tests/browser/test/basic_playground_test.js
  tests/browser/test/block_undo_test.js
  tests/browser/test/extensive_test.js
  tests/browser/test/field_edits_test.js
  tests/browser/test/procedure_test.js
  tests/browser/test/test_setup.js
Labels: component: tests

#7295 fix(generators): Changes to exports and access controls for TypeScript compatibility
  core/generator.ts
  generators/python/python_generator.js
  typings/dart.d.ts
  typings/javascript.d.ts
  typings/lua.d.ts
  typings/php.d.ts
  typings/python.d.ts
Labels: component: generators, PR: fix

#7279 chore: add tests for disabling blocks
  tests/browser/test/basic_playground_test.js
  tests/browser/test/test_setup.js
Labels: PR: chore

#7301 feat: Allow dragging from simple toolbox
  tests/browser/test/test_setup.js
Labels: PR: feature

#7312 fix: renamings for v10
  scripts/migration/renamings.json5
Labels: PR: fix

#7313 chore: update block test dependency
  package-lock.json
  package.json
Labels: PR: chore

#7296 fix: have icons use the new render management system
  core/block_svg.ts
  core/render_management.ts
  tests/mocha/block_test.js
Labels: PR: fix

#7324 fix(tests): fix broken browser tests
  tests/browser/test/.mocharc.js
  tests/browser/test/basic_block_test.js
  tests/browser/test/basic_playground_test.js
  tests/browser/test/test_setup.js
Labels: component: tests, PR: fix

#7306 fix: make deserialization use the new render management system
  core/connection.ts
  core/contextmenu.ts
  core/flyout_base.ts
  core/serialization/blocks.ts
  core/workspace_svg.ts
  core/xml.ts
  tests/mocha/flyout_test.js
Labels: PR: fix

#7307 fix: make insertion markers use new render management system
  core/insertion_marker_manager.ts
  core/workspace_svg.ts
Labels: PR: fix

#7293 chore(tests): Update RTL tests and misc improvements to helpers
  core/flyout_base.ts
  core/xml.ts
  tests/browser/test/basic_playground_test.js
  tests/browser/test/field_edits_test.js
  tests/browser/test/test_setup.js
Labels: PR: chore

#7278 chore: create test for mutator
  tests/browser/test/mutator_test.js
  tests/browser/test/test_setup.js
Labels: PR: chore

#7314 feat: add the ability to toggle scrollbar visibility
  core/scrollbar.ts
  core/scrollbar_pair.ts
Labels: PR: feature

#7311 chore(tests): update generator test blocks to use forBlock
  tests/generators/unittest_dart.js
  tests/generators/unittest_javascript.js
  tests/generators/unittest_lua.js
  tests/generators/unittest_php.js
  tests/generators/unittest_python.js
Labels: type: cleanup

#7330 chore(tests): fix disable block tests
  tests/browser/test/basic_playground_test.js
  tests/browser/test/test_setup.js
Labels: PR: chore

#7329 fix(tests): Make `.mocharc.js` independent of current working directory
  package.json
  tests/browser/.mocharc.js
Labels: component: tests, PR: fix

#7331 feat: add basic pasters
  core/clipboard/block_paster.ts
  core/clipboard/workspace_comment_paster.ts
  core/interfaces/i_paster.ts
Labels: PR: feature

#7335 fix(blocks): boolean variable block wrong shape for zelos
  core/rendered_connection.ts
Labels: PR: fix

#7343 chore: fix paster exports and registration
  core/blockly.ts
  core/clipboard.ts
  core/clipboard/block_paster.ts
  core/clipboard/registry.ts
  core/clipboard/workspace_comment_paster.ts
  core/registry.ts
Labels: PR: chore
