Repository google/blockly, pull requests merged in 2023-03, with the labels that each got.

#6851 feat: add basic render queueing
  core/block_dragger.ts
  core/block_svg.ts
  core/insertion_marker_manager.ts
  core/render_management.ts
  core/rendered_connection.ts
Labels: PR: feature

#6859 fix: updating connections in the db multiple times
  core/block_svg.ts
  core/render_management.ts
  core/rendered_connection.ts
Labels: PR: fix

#6875 fix: Don't repeatedly recreate the last marker block during a drag.
  core/insertion_marker_manager.ts
Labels: PR: fix

#6877 fix: export Field-related types from Blockly
  core/blockly.ts
  core/field.ts
  core/field_angle.ts
  core/field_checkbox.ts
  core/field_colour.ts
  core/field_dropdown.ts
  core/field_input.ts
  core/field_multilineinput.ts
  core/field_number.ts
  core/field_textinput.ts
  core/field_variable.ts
Labels: PR: fix

#6860 fix: improve collapse / uncollapse performance
  core/block_svg.ts
  core/field.ts
  core/input.ts
  tests/mocha/block_test.js
  tests/mocha/blocks/procedures_test.js
  tests/mocha/field_checkbox_test.js
  tests/mocha/input_test.js
Labels: PR: fix

#6885 fix: creating duplicate params via renaming vars
  .eslintrc.js
  core/blockly.ts
  core/interfaces/i_legacy_procedure_blocks.ts
  core/interfaces/i_variable_backed_parameter_model.ts
  core/procedures.ts
  core/variables.ts
  msg/messages.js
  tests/mocha/blocks/variables_test.js
  tests/mocha/test_helpers/procedures.js
Labels: PR: fix

#6888 revert: "refactor: Remove block and workspace drag surfaces (#6758)"
  core/block_drag_surface.ts
  core/block_dragger.ts
  core/block_svg.ts
  core/blockly.ts
  core/bubble.ts
  core/bubble_dragger.ts
  core/css.ts
  core/inject.ts
  core/interfaces/i_block_dragger.ts
  core/interfaces/i_bubble.ts
  core/scrollbar.ts
  core/workspace_comment_svg.ts
  core/workspace_drag_surface_svg.ts
  core/workspace_dragger.ts
  core/workspace_svg.ts
Labels: PR: revert

#6884 fix: improve performance of modifying block shape
  core/block_svg.ts
  core/input.ts
  tests/mocha/block_test.js
Labels: PR: fix

#6872 fix: empty procedure arrays in serialization
  core/serialization/procedures.ts
Labels: PR: fix

#6883 chore: cleanup render management
  core/insertion_marker_manager.ts
  core/render_management.ts
  core/rendered_connection.ts
Labels: PR: chore

#6781 chore: Remove various IE hacks and workarounds
  README.md
  core/css.ts
  core/flyout_base.ts
  core/grid.ts
  core/workspace_svg.ts
  core/xml.ts
  tests/bootstrap.js
Labels: PR: chore

#6896 fix: toString performance
  core/block.ts
Labels: PR: fix

#6886 chore: Reduce delta on ports to blockly-samples
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  core/block_animations.ts
  core/browser_events.ts
  core/bubble.ts
  core/comment.ts
  core/component_manager.ts
  core/contextmenu_items.ts
  core/field.ts
  core/field_angle.ts
  core/field_checkbox.ts
  core/field_colour.ts
  core/field_dropdown.ts
  core/field_image.ts
  core/field_input.ts
  core/field_label.ts
  core/field_label_serializable.ts
  core/field_multilineinput.ts
  core/field_number.ts
  core/field_textinput.ts
  core/field_variable.ts
  core/flyout_base.ts
  core/flyout_button.ts
  core/generator.ts
  core/gesture.ts
  core/grid.ts
  core/keyboard_nav/ast_node.ts
  core/menu.ts
  core/registry.ts
  core/renderers/zelos/marker_svg.ts
  core/scrollbar.ts
  core/shortcut_registry.ts
  core/theme.ts
  core/toolbox/category.ts
  core/toolbox/toolbox.ts
  core/trashcan.ts
  core/utils/colour.ts
  core/utils/dom.ts
  core/utils/parsing.ts
  core/workspace_comment.ts
  core/workspace_comment_svg.ts
  core/workspace_svg.ts
  core/xml.ts
  core/zoom_controls.ts
  demos/blockfactory/analytics.js
  generators/javascript/lists.js
  scripts/gulpfiles/test_tasks.js
  tests/generators/golden/generated.js
  tests/mocha/block_test.js
  tests/mocha/blocks/procedures_test.js
  tests/mocha/field_angle_test.js
  tests/mocha/field_colour_test.js
  tests/mocha/toolbox_test.js
  tests/mocha/variable_map_test.js
  tests/mocha/webdriver.js
  tests/typescript/src/field/different_user_input.ts
Labels: PR: chore

#6899 chore: Add required @license tag to any_aliases.ts
  core/any_aliases.ts
Labels: PR: chore

#6876 fix: improve performance of connecting blocks
  core/block_svg.ts
  core/connection.ts
  core/contextmenu.ts
  core/insertion_marker_manager.ts
  core/rendered_connection.ts
  tests/mocha/block_test.js
Labels: PR: fix

#6894 fix: dispose performance
  core/block.ts
  core/block_animations.ts
  core/block_svg.ts
  core/connection.ts
  core/field.ts
  core/icon.ts
  core/tooltip.ts
  tests/mocha/connection_checker_test.js
  tests/mocha/event_block_delete_test.js
  tests/mocha/serializer_test.js
Labels: PR: fix

#6901 refactor(blocks): Migrate `blocks/colour.js` to TypeScript
  blocks/colour.ts
Labels: component: library blocks, PR: refactor

#6829 fix: Don't clober event group when renaming vars
  core/block.ts
  core/bump_objects.ts
  core/connection.ts
  core/contextmenu_items.ts
  core/rendered_connection.ts
  core/variable_map.ts
  core/workspace.ts
  core/workspace_comment.ts
  core/workspace_svg.ts
  core/xml.ts
Labels: PR: fix

#6904 chore: force add the build files when updating gh-pages
  scripts/gulpfiles/git_tasks.js
Labels: PR: chore

#6900 refactor(blocks): Migrate `blocks/math.js` to TypeScript
  blocks/math.ts
Labels: component: library blocks, PR: refactor

#6911 fix: Fix scrolling of menus on mobile.
  core/menu.ts
Labels: PR: fix

#6912 fix: scrolling dropdown items into view
  core/field_dropdown.ts
Labels: PR: fix

#6914 fix: flyouts resizing for blocks
  core/events/utils.ts
Labels: type: regression, PR: fix

#6913 fix: overwriting flyout def with dynamic categories
  core/flyout_base.ts
Labels: PR: fix

#6919 fix(fields): Make `Field.SKIP_SETUP` a `Symbol`; remove `class Sentinel`
  core/field.ts
  core/field_angle.ts
  core/field_checkbox.ts
  core/field_colour.ts
  core/field_dropdown.ts
  core/field_image.ts
  core/field_input.ts
  core/field_label.ts
  core/field_multilineinput.ts
  core/field_number.ts
  core/field_textinput.ts
  core/field_variable.ts
  core/utils/sentinel.ts
Labels: component: fields, PR: fix

#6921 fix: connection locations not updating
  core/rendered_connection.ts
Labels: type: regression, PR: fix

#6923 fix: Make Escape cancel changes in text fields.
  core/field_input.ts
Labels: PR: fix

#6917 fix: mutator not resizing for flyout
  core/mutator.ts
Labels: PR: fix

#6930 chore(build): Temporarily exclude blocks and generators .d.ts files
  scripts/gulpfiles/package_tasks.js
Labels: component: build process, PR: chore

#6931 chore: Rollup of 2023 Q1 updates from TranslateWiki
  msg/json/bn.json
  msg/json/bs.json
  msg/json/de.json
  msg/json/fi.json
  msg/json/fr.json
  msg/json/ia.json
  msg/json/kn.json
  msg/json/ko.json
  msg/json/lb.json
  msg/json/sd.json
  msg/json/skr-arab.json
  msg/json/sl.json
  msg/json/sr.json
  msg/json/sw.json
  msg/json/zh-hans.json
  msg/json/zh-hant.json
Labels: PR: chore

#6932 chore: update renamings file for 2023 Q1 release
  scripts/migration/renamings.json5
Labels: PR: chore

#6933 chore: Update metadata for 2023 Q1 release
  tests/scripts/check_metadata.sh
Labels: PR: chore

#6939 fix: allow splicing into shadow block stacks
  core/connection_checker.ts
  tests/mocha/connection_checker_test.js
Labels: PR: fix
