Repository google/blockly, pull requests merged in 2024-07, with the labels that each got.

#8240 fix: correctly report the pre-resize-drag size to workspace comment size change listeners
  core/comments/comment_view.ts
Labels: PR: fix

#8241 chore: make getEventWorkspace_() public
  core/events/events_abstract.ts
Labels: PR: chore

#8246 fix(deps): Revert "chore(deps): bump the npm_and_yarn group across 1 directory with 7 updates"
  package-lock.json
  package.json
Labels: PR: dependencies, PR: chore

#8247 test(CI): Add node.js v22.x to build matrix
  .github/workflows/build.yml
Labels: component: tests, PR: chore

#8252 chore: merge develop into v12
  .github/workflows/appengine_deploy.yml
  .github/workflows/build.yml
  core/comments/comment_view.ts
  core/events/events_abstract.ts
  demos/blockfactory/app_controller.js
  demos/blockfactory/factory.css
  demos/blockfactory/index.html
  package-lock.json
  package.json
Labels: PR: chore

#8245 test(CI): Have GitHub use `npm ci` instead of `npm install`
  .github/workflows/build.yml
Labels: component: tests, PR: chore

#8256 fix: export the layer constants.
  core/blockly.ts
  core/layers.ts
Labels: PR: fix

#8284 feat: allow fetching block bounds not including children.
  core/block_svg.ts
  core/renderers/common/drawer.ts
Labels: PR: feature

#8292 chore: merge develop into rc/v12
  .github/workflows/build.yml
  core/block_svg.ts
  core/blockly.ts
  core/layers.ts
  core/renderers/common/drawer.ts
  package-lock.json
  package.json
Labels: PR: chore

#8298 fix: use the correct with in getBoundingRectangleWithoutChildren().
  core/block_svg.ts
Labels: PR: fix

#8335 fix!: rename the blockly icon CSS classes to use camelCase (#8329)
  core/icons/comment_icon.ts
  core/icons/mutator_icon.ts
  core/icons/warning_icon.ts
Labels: breaking change, PR: fix

#8334 feat: Add blocklyField to field's SVG Group
  core/field.ts
Labels: PR: feature

#8332 fix!: Make `IPathObject` styling methods optional
  core/block_svg.ts
  core/renderers/common/i_path_object.ts
Labels: breaking change, PR: fix

#8337 refactor: Add `addClass` and `removeClass` methods to blockSvg
  core/block_svg.ts
Labels: PR: refactor

#8369 feat: add the IVariableMap and IVariableModel interfaces.
  core/blockly.ts
  core/interfaces/i_variable_map.ts
  core/interfaces/i_variable_model.ts
Labels: PR: feature

#8358 fix: added id to rendered ws comments; made getCommentById public; ad…
  core/comments/comment_view.ts
  core/comments/rendered_workspace_comment.ts
  core/workspace.ts
Labels: PR: fix

#8357 fix!: Rename `blocklyTreeRow` and `blocklyToolboxCategory` CSS classes
  core/toolbox/category.ts
  tests/mocha/comment_deserialization_test.js
  tests/mocha/toolbox_test.js
Labels: breaking change, PR: fix

#8333 feat: Add a blocklyTextBubble CSS class to the text bubble #8331
  core/bubbles/text_bubble.ts
Labels: PR: feature

#8381 refactor: make VariableModel implement IVariableModel.
  core/variable_model.ts
Labels: PR: refactor

#8366 chore(deps): Enable `legacy-peer-deps`, update `@blockly/` plugins
  .npmrc
  package-lock.json
  package.json
Labels: PR: dependencies, PR: chore

#8336 feat: Add a blocklyShadow class
  core/renderers/common/path_object.ts
Labels: PR: feature

#8367 fix!: renamed blocklyTreeIcon Css class to blocklyToolboxCategoryIcon #8347
  core/toolbox/category.ts
Labels: breaking change, PR: fix

#8339 fix!: Replace Closure UI CSS classes with Blockly CSS classes
  core/menu.ts
  core/menuitem.ts
Labels: breaking change, PR: fix

#8372 feat: Added blocklyTrashcanFlyout CSS class
  core/trashcan.ts
  package-lock.json
Labels: PR: feature

#8377 feat: Add css classes from json block definitions
  core/block_svg.ts
Labels: PR: feature

#8384 fix!: rename `blocklyToolboxContents` to `blocklyToolboxCategoryGroup`
  core/toolbox/category.ts
  core/toolbox/collapsible_category.ts
  core/toolbox/toolbox.ts
Labels: breaking change, PR: fix

#8386 feat: Add blocklyToolboxFlyout CSS class to the flyout
  core/toolbox/toolbox.ts
Labels: PR: feature

#8393 chore: Pin node.js v22 to v22.4.1 in CI
  .github/workflows/build.yml
Labels: component: tests, PR: chore

#8388 refactor: update the variable interfaces.
  core/interfaces/i_variable_map.ts
  core/interfaces/i_variable_model.ts
  core/registry.ts
  core/serialization/variables.ts
  core/variable_model.ts
Labels: PR: refactor

#8394 chore: develop into V12 to pin node version
  .github/workflows/build.yml
  .npmrc
  core/block_svg.ts
  core/comments/comment_view.ts
  core/comments/rendered_workspace_comment.ts
  core/workspace.ts
  package-lock.json
  package.json
Labels: PR: chore

#8395 refactor: make VariableMap implement IVariableMap.
  core/variable_map.ts
  core/variables.ts
  core/workspace.ts
  tests/mocha/variable_map_test.js
Labels: PR: refactor

#8400 refactor: Use IVariableModel instead of VariableModel.
  blocks/loops.ts
  blocks/procedures.ts
  blocks/variables_dynamic.ts
  core/block.ts
  core/events/events_var_base.ts
  core/events/events_var_create.ts
  core/events/events_var_delete.ts
  core/events/events_var_rename.ts
  core/field_variable.ts
  core/interfaces/i_variable_backed_parameter_model.ts
  core/names.ts
  core/serialization/blocks.ts
  core/variable_map.ts
  core/variable_model.ts
  core/variables.ts
  core/variables_dynamic.ts
  core/workspace.ts
  core/workspace_svg.ts
  core/xml.ts
  generators/php/procedures.ts
  generators/python/procedures.ts
  tests/mocha/xml_test.js
Labels: PR: refactor

#8401 refactor!: Use IVariableMap instead of VariableMap
  core/names.ts
  core/variable_map.ts
  core/variables.ts
  core/workspace.ts
  tests/mocha/variable_map_test.js
Labels: breaking change, PR: refactor

#8354 fix: Enable blocks if user can't manually enable them.
  core/block.ts
  tests/mocha/blocks/procedures_test.js
Labels: PR: fix

#8416 refactor: clean up VariableModel.
  core/variable_model.ts
  tests/mocha/variable_model_test.js
Labels: PR: refactor

#8307 fix: Remove references to getFastTextWidth (#8277)
  core/field.ts
  core/field_dropdown.ts
Labels: PR: fix

#8308 feat: Add a blocklyCollapsed CSS class to collapsed blocks' root SVG (#8264)
  core/block_svg.ts
Labels: PR: feature

#8301 fix!: Rename editing CSS class to blocklyEditing (#8287)
  core/field_input.ts
  core/renderers/common/constants.ts
  core/renderers/zelos/constants.ts
Labels: breaking change, PR: fix

#8397 feat: Add a blocklyBlock CSS class to the block's root SVG
  core/renderers/common/path_object.ts
Labels: PR: feature

#8390 feat: add `blocklyMiniWorkspaceBubble` css class
  core/bubbles/mini_workspace_bubble.ts
Labels: PR: feature

#8415 refactor: deprecate and clean up variable-related methods.
  core/field_variable.ts
  core/variable_map.ts
  core/variable_model.ts
  core/workspace.ts
  tests/mocha/field_variable_test.js
  tests/mocha/variable_map_test.js
Labels: PR: refactor

#8391 feat: Add a blocklyNotEditable CSS class to the block's root SVG
  core/block_svg.ts
Labels: PR: feature

#8431 docs(blocks): `block.ts` and `blocks/*` JSDoc / formatting / etc. cleanup
  blocks/procedures.ts
  blocks/text.ts
  core/block.ts
  core/block_svg.ts
Labels: component: library blocks, PR: docs

#8426 chore: Removed @internal annotation from public Field methods.
  core/field.ts
Labels: PR: chore

#8355 fix: drag strategy only clear group id set by us
  core/dragging/block_drag_strategy.ts
  core/dragging/bubble_drag_strategy.ts
  core/dragging/comment_drag_strategy.ts
Labels: PR: fix

#8360 fix: use `:focus` pseudo class instead of `blocklyFocused`
  core/css.ts
  core/dropdowndiv.ts
  core/menu.ts
Labels: PR: fix

#8432 fix: Codify component weights with toolbox in front of flyouts.
  core/component_manager.ts
  core/flyout_base.ts
  core/toolbox/toolbox.ts
  core/trashcan.ts
  core/zoom_controls.ts
Labels: PR: fix

#8402 feat: Add a VarTypeChange event.
  core/events/events.ts
  core/events/events_var_type_change.ts
  core/events/utils.ts
  tests/mocha/event_var_type_change_test.js
  tests/mocha/index.html
Labels: PR: feature

#8406 feat: added `blocklyNotDetetable` class to block_svg
  core/block_svg.ts
Labels: PR: feature

#8428 feat: add the block's type as a CSS class to the block's root SVG
  core/block_svg.ts
Labels: PR: feature

#8423 feat: add `blocklyLabelField` css class to label field
  core/field_label.ts
Labels: PR: feature

#8440 fix!: Rename blocklyTreeIconOpen to `blocklyToolboxCategoryIconOpen`
  core/toolbox/category.ts
Labels: breaking change, PR: fix

#8414 feat: Add a blocklyNumberField CSS class to number fields
  core/field_number.ts
Labels: PR: feature
