Repository google/blockly, pull requests merged in 2024-10, with the labels that each got.

#8605 fix: Let old block factory overwrite user defined blocks.
  demos/blockfactory/block_library_controller.js
  demos/blockfactory/block_library_view.js
  demos/blockfactory/blocks.js
  demos/blockfactory/factory.js
Labels: PR: fix

#8598 refactor(shortcuts): Improve shortcut registry documentation & style
  core/shortcut_registry.ts
Labels: component: keyboard_nav, PR: refactor

#8600 fix: Fix bug that prevented dismissing the widgetdiv in a mutator workspace.
  core/widgetdiv.ts
Labels: PR: fix

#8607 fix: Fix bug that caused fields in the flyout to use the main workspace's scale.
  core/field_input.ts
  core/workspace_svg.ts
  tests/mocha/field_textinput_test.js
Labels: PR: fix

#8601 refactor!: Update flyouts to use inflaters.
  core/blockly.ts
  core/flyout_base.ts
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
  core/keyboard_nav/ast_node.ts
  tests/mocha/flyout_test.js
Labels: breaking change, PR: refactor

#8606 chore: Remove obsolete comment.
  core/generator.ts
Labels: PR: chore

#8608 feat: Allow specifying the placeholder text of workspace comments.
  core/comments/comment_view.ts
  core/comments/rendered_workspace_comment.ts
  core/contextmenu_items.ts
Labels: PR: feature

#8616 fix: Correctly calculate the bounds of hat blocks.
  core/renderers/common/constants.ts
  core/renderers/common/info.ts
  core/renderers/zelos/constants.ts
Labels: PR: fix

#8617 fix: Take the flyout into account when positioning the workspace after a toolbox change.
  core/toolbox/toolbox.ts
Labels: PR: fix

#8618 feat: Allow specifying the default size of comments.
  core/comments/comment_view.ts
  core/comments/workspace_comment.ts
Labels: PR: feature

#8619 fix: Fix exception when disposing of a workspace with a variable block obscuring a shadow block.
  core/workspace.ts
Labels: PR: fix

#8627 fix: clear touch identifier on comment icon down
  core/comments/comment_view.ts
Labels: PR: fix

#8631 fix: improve typings and export additional types
  core/blockly.ts
  core/clipboard.ts
  core/dropdowndiv.ts
Labels: PR: fix

#8633 chore: Remove unneeded handling for @suppress and @alias.
  tsdoc.json
Labels: PR: chore
