Repository google/blockly, pull requests merged in 2024-12, with the labels that each got.

#8682 chore: Remove underscores from private fields.
  core/block.ts
  core/block_svg.ts
  core/component_manager.ts
  core/contextmenu_registry.ts
  core/events/events_block_move.ts
  core/field.ts
  core/field_checkbox.ts
  core/field_input.ts
  core/flyout_base.ts
  core/flyout_metrics_manager.ts
  core/gesture.ts
  core/marker_manager.ts
  core/options.ts
  core/scrollbar_pair.ts
  core/shortcut_registry.ts
  core/theme_manager.ts
  core/toolbox/category.ts
  core/toolbox/collapsible_category.ts
  core/toolbox/separator.ts
  core/toolbox/toolbox.ts
  core/variable_map.ts
  core/variable_model.ts
  core/workspace.ts
  core/workspace_audio.ts
  core/workspace_dragger.ts
  core/workspace_svg.ts
  tests/mocha/block_json_test.js
  tests/mocha/block_test.js
  tests/mocha/blocks/logic_ternary_test.js
  tests/mocha/blocks/procedures_test.js
  tests/mocha/event_test.js
  tests/mocha/field_number_test.js
  tests/mocha/field_test.js
  tests/mocha/field_textinput_test.js
  tests/mocha/keydown_test.js
  tests/mocha/shortcut_registry_test.js
  tests/mocha/test_helpers/toolbox_definitions.js
  tests/mocha/toolbox_test.js
  tests/mocha/variable_model_test.js
  tests/mocha/workspace_svg_test.js
Labels: PR: chore

#8671 fix: Create CSS vars for SVG patterns.
  core/bubbles/bubble.ts
  core/css.ts
  core/grid.ts
  core/inject.ts
  core/renderers/common/constants.ts
  core/renderers/common/path_object.ts
  core/renderers/common/renderer.ts
  core/renderers/geras/renderer.ts
  core/renderers/zelos/constants.ts
  core/renderers/zelos/path_object.ts
  core/workspace_svg.ts
Labels: PR: fix

#8675 chore: Migrate ESLint configuration file to new flat format.
  .eslintignore
  .eslintrc.js
  core/interfaces/i_serializer.ts
  core/renderers/geras/constants.ts
  core/renderers/zelos/constants.ts
  core/serialization/blocks.ts
  core/serialization/variables.ts
  core/variables.ts
  core/workspace_svg.ts
  eslint.config.mjs
  package-lock.json
  package.json
  scripts/helpers.js
  tests/.eslintrc.json
  tests/browser/.eslintrc.json
  tests/migration/validate-renamings.mjs
  tests/mocha/.eslintrc.json
  tests/mocha/serializer_test.js
  tests/mocha/test_helpers/code_generation.js
  tests/mocha/workspace_test.js
  tests/node/.eslintrc.json
  tests/playgrounds/screenshot.js
Labels: PR: chore

#8665 fix: Disable newly created function call blocks when the corresponding definition is disabled.
  blocks/procedures.ts
Labels: PR: fix

#8670 fix: Fix bug that caused text to be selected when long-pressing in the workspace on a touch device.
  core/css.ts
  core/toolbox/toolbox.ts
  tests/mocha/toolbox_test.js
Labels: PR: fix

#8684 chore: Remove CSS targeting multiline input field.
  core/css.ts
Labels: PR: chore

#8669 chore: Remove obsolete workaround for resize events on iPads.
  core/inject.ts
Labels: PR: chore

#8666 fix: workspace shifts when deleting a block
  core/dragging/block_drag_strategy.ts
Labels: PR: fix

#8677 test: Disable failing tests
  tests/mocha/workspace_svg_test.js
Labels: component: tests, PR: chore
