Repository google/blockly, pull requests merged in 2024-09, with the labels that each got.

#8532 fix(comments): added workspace comments and comment drag strategy isDeadOrDying() checks
  core/comments/workspace_comment.ts
  core/dragging/comment_drag_strategy.ts
Labels: component: comments, PR: fix

#8558 feat: mark some marker_svg properties protected instead of private
  core/renderers/common/marker_svg.ts
Labels: PR: feature

#8564 refactor: use getters for flyout width and height.
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
Labels: PR: refactor

#8550 fix: Ensure immovable blocks are considered during workspace tidying
  core/utils/rect.ts
  core/workspace_svg.ts
  tests/mocha/contextmenu_items_test.js
  tests/mocha/index.html
  tests/mocha/rect_test.js
  tests/mocha/workspace_svg_test.js
Labels: PR: fix

#8571 fix: improve flyout performance
  core/flyout_base.ts
Labels: PR: fix

#8572 fix: size text with computed styles even when hidden
  core/utils/dom.ts
Labels: PR: fix

#8566 fix: Factor out workspace drag methods into utils.
  core/bubbles/textinput_bubble.ts
  core/comments/comment_view.ts
  core/utils/drag.ts
  core/workspace_svg.ts
Labels: PR: fix

#8574 fix: include potential variables in variable dropdowns in the flyout
  core/field_variable.ts
Labels: PR: fix

#8573 refactor: remove redundant flyout positioning.
  core/workspace_svg.ts
Labels: PR: refactor

#8575 fix: Simplify list and text WHERE validation
  blocks/lists.ts
  blocks/text.ts
Labels: PR: fix

#8589 fix: Group field validator changes with field value changes.
  core/field.ts
  tests/mocha/jso_serialization_test.js
Labels: PR: fix

#8581 feat: Add the IFlyoutInflater interface.
  core/interfaces/i_flyout_inflater.ts
  core/registry.ts
Labels: PR: feature

#8593 feat: Add inflaters for flyout labels and buttons.
  core/button_flyout_inflater.ts
  core/flyout_button.ts
  core/label_flyout_inflater.ts
Labels: PR: feature

#8592 feat: Add support for inflating flyout separators.
  core/flyout_separator.ts
  core/separator_flyout_inflater.ts
Labels: PR: feature

#8591 feat: Add a BlockFlyoutInflater class.
  core/block_flyout_inflater.ts
Labels: PR: feature
