Repository google/blockly, pull requests merged in 2024-08, with the labels that each got.

#8453 feat: add a method for subclasses of FieldVariable to get the default type.
  core/field_variable.ts
Labels: PR: feature

#8451 fix: comments and bubbles on click
  core/bubbles/bubble.ts
  core/comments/rendered_workspace_comment.ts
Labels: PR: fix

#8457 fix: Update dev-tools, remove toolbox category tests Colour and Angles
  package-lock.json
  package.json
  tests/browser/test/toolbox_drag_test.mjs
Labels: PR: fix

#8459 fix!: Renamed the blocklyTreeSelected CSS class to blocklyToolboxSelected
  core/toolbox/category.ts
Labels: breaking change, PR: fix

#8436 feat: added block's style as a CSS class to block's root SVG
  core/block_svg.ts
Labels: PR: feature

#8465 fix!: deleted styles without associated classes from css.ts, issue #8285
  core/css.ts
Labels: breaking change, PR: fix

#8472 feat: expose `bringToFront()` method
  core/block_svg.ts
Labels: PR: feature

#8470 fix(touch): prevent infinite loop on multi-touch drag
  core/gesture.ts
  package-lock.json
  package.json
Labels: PR: fix

#8475 feat!: change blocklyEditableText to blocklyEditableField and blocklyNonEditableText to blocklyNonEditableField
  core/css.ts
  core/field.ts
  core/renderers/common/constants.ts
  core/renderers/zelos/constants.ts
Labels: breaking change, PR: feature

#8473 feat: implement `WorkspaceSvg` class manipulation
  core/workspace_svg.ts
Labels: PR: feature

#8407 feat: added `blocklyHighlighted` CSS class to highlighted block's root…
  core/renderers/common/path_object.ts
  core/renderers/geras/path_object.ts
Labels: PR: feature

#8478 chore: removed the whole Drag category from the browser test
  tests/browser/test/toolbox_drag_test.mjs
Labels: PR: chore

#8477 fix: Let workspace comment have delete cursor over trash.
  core/comments/comment_view.ts
Labels: PR: fix

#8529 fix: improve prompting when deleting variables
  blocks/variables.ts
  blocks/variables_dynamic.ts
  core/field_variable.ts
  core/flyout_button.ts
  core/variables.ts
Labels: PR: fix

#8537 refactor(events): Don't filter events before undo
  core/events/utils.ts
  core/workspace.ts
Labels: component: events, PR: refactor

#8538 refactor(events): Introduce and use event type predicates
  core/bump_objects.ts
  core/events/predicates.ts
  core/events/type.ts
  core/events/utils.ts
  core/icons/mutator_icon.ts
  core/procedures.ts
  core/trashcan.ts
Labels: component: events, PR: refactor

#8536 fix!: Remove the blocklyMenuItemHighlight CSS class and use the hover
  core/css.ts
  core/menu.ts
  core/menuitem.ts
Labels: breaking change, PR: fix

#8549 fix: display the correct variable reference count when deleting a variable.
  core/variables.ts
Labels: PR: fix

#8533 fix: Detect if deleting shadow block affects selection highlight
  core/block_svg.ts
  tests/mocha/block_test.js
Labels: PR: fix

#8539 fix(events): Simplify `filter` function, add new `enqueueEvent` function
  core/events/utils.ts
  tests/mocha/event_test.js
Labels: component: events, PR: fix

#8557 refactor: Use arrow functions when calling `Array.prototype.filter`
  core/events/utils.ts
  core/utils/toolbox.ts
  core/workspace.ts
  core/workspace_svg.ts
  tests/mocha/event_test.js
Labels: PR: refactor
