Repository google/blockly, pull requests merged in 2024-03, with the labels that each got.

#7886 fix: libraryBlocks exports
  blocks/blocks.ts
Labels: PR: fix

#7894 fix: shouldPreventMove not being respected
  core/block_dragger.ts
Labels: PR: fix

#7899 fix: connection dancing
  core/insertion_marker_previewer.ts
Labels: PR: fix

#7865 chore: make getters for grid attributes public and update inline docs
  core/grid.ts
Labels: PR: chore

#7893 chore: merge develop into v11
  core/block_dragger.ts
  core/blockly.ts
  core/events/events_click.ts
  core/grid.ts
  core/insertion_marker_previewer.ts
  core/rendered_connection.ts
  core/workspace_svg.ts
  msg/json/ar.json
  msg/json/be-tarask.json
  msg/json/bn.json
  msg/json/da.json
  msg/json/el.json
  msg/json/he.json
  msg/json/id.json
  msg/json/inh.json
  msg/json/ja.json
  msg/json/nl.json
  msg/json/pt.json
  msg/json/qqq.json
  msg/json/ta.json
  msg/json/tl.json
  msg/json/ur.json
  msg/json/yue.json
  msg/json/zh-hant.json
  package-lock.json
  package.json
  scripts/gulpfiles/docs_tasks.js
  tests/scripts/check_metadata.sh
Labels: PR: chore

#7903 chore: fix spelling in common.ts
  core/common.ts
Labels: PR: chore

#7914 feat: add comment view (for workspace comments, and block comments for partners)
  core/blockly.ts
  core/comments.ts
  core/comments/comment_view.ts
  core/inject.ts
  media/arrow-dropdown.svg
  media/resize-handle.svg
  tests/mocha/index.html
  tests/mocha/old_workspace_comment_test.js
  tests/mocha/workspace_comment_test.js
Labels: PR: feature

#7915 fix: comment min size
  core/comments/comment_view.ts
  core/utils/size.ts
Labels: PR: fix

#7929 chore: merge develop into v11.0.0
  blocks/blocks.ts
  core/block_dragger.ts
  core/common.ts
  core/grid.ts
  core/insertion_marker_previewer.ts
  package-lock.json
Labels: PR: chore

#7930 chore: merge master into develop following V10.4.3 release
  package-lock.json
  package.json
Labels: PR: chore

#7891 fix!: have disposing be true from start of dispose
  core/block.ts
  core/block_svg.ts
  core/connection.ts
  core/xml.ts
  tests/mocha/block_test.js
Labels: breaking change, PR: fix

#7932 feat!: delete angle, colour, and multiline input fields and blocks
  blocks/blocks.ts
  blocks/colour.ts
  blocks/text.ts
  core/blockly.ts
  core/field_angle.ts
  core/field_colour.ts
  core/field_image.ts
  core/field_multilineinput.ts
  generators/dart.ts
  generators/dart/colour.ts
  generators/dart/text.ts
  generators/javascript.ts
  generators/javascript/colour.ts
  generators/javascript/text.ts
  generators/lua.ts
  generators/lua/colour.ts
  generators/lua/text.ts
  generators/php.ts
  generators/php/colour.ts
  generators/php/text.ts
  generators/python.ts
  generators/python/colour.ts
  generators/python/text.ts
  tests/generators/colour.xml
  tests/generators/golden/generated.dart
  tests/generators/golden/generated.js
  tests/generators/golden/generated.lua
  tests/generators/golden/generated.php
  tests/generators/golden/generated.py
  tests/generators/index.html
  tests/generators/text.xml
  tests/mocha/field_angle_test.js
  tests/mocha/field_multilineinput_test.js
  tests/mocha/index.html
  tests/mocha/serializer_test.js
  tests/mocha/xml_test.js
  tests/multi_playground.html
  tests/playground.html
Labels: breaking change, PR: feature

#7935 fix!: classes on text input bubble to match comment view
  core/bubbles/bubble.ts
  core/bubbles/textinput_bubble.ts
Labels: breaking change, PR: fix

#7936 chore: Use .includes and .startsWith, not .indexOf
  blocks/lists.ts
  blocks/procedures.ts
  blocks/text.ts
  core/block.ts
  core/bump_objects.ts
  core/component_manager.ts
  core/connection_checker.ts
  core/extensions.ts
  core/field_number.ts
  core/flyout_base.ts
  core/names.ts
  core/renderers/common/constants.ts
  core/renderers/zelos/constants.ts
  core/shortcut_registry.ts
  core/trashcan.ts
  core/utils/string.ts
  core/utils/svg_math.ts
  core/utils/toolbox.ts
  core/utils/useragent.ts
  core/variables.ts
  core/workspace_svg.ts
  demos/blockfactory/block_exporter_controller.js
  demos/blockfactory/blocks.js
  demos/blockfactory/factory.js
  demos/blockfactory/factory_utils.js
  demos/blockfactory/index.html
  demos/blockfactory/workspacefactory/wfactory_model.js
  demos/blockfactory_old/blocks.js
  demos/blockfactory_old/factory.js
  demos/code/code.js
  generators/dart/text.ts
  generators/javascript/text.ts
  generators/lua/loops.ts
  generators/lua/text.ts
  generators/php/procedures.ts
  generators/php/text.ts
  generators/python/procedures.ts
  generators/python/python_generator.ts
  generators/python/text.ts
  scripts/gulpfiles/release_tasks.js
  tests/mocha/test_helpers/user_input.js
  tests/playgrounds/screenshot.js
Labels: PR: chore

#7937 feat: allow overriding comment icons
  core/block.ts
  core/icons/icon_types.ts
  core/interfaces/i_comment_icon.ts
  tests/mocha/block_test.js
Labels: PR: feature

#7916 feat: add headless workspace comment class
  core/comments.ts
  core/comments/workspace_comment.ts
Labels: PR: feature

#7939 fix: updated field_dropdown to properly infer its Field type with TS 5.3.3
  core/field_dropdown.ts
  package-lock.json
  package.json
Labels: PR: fix

#7940 fix(generators): Make `scrub_` `public`
  core/generator.ts
  generators/javascript/javascript_generator.ts
  generators/python/python_generator.ts
Labels: component: generators, PR: fix

#7822 feat(build)!: Introduce `exports` section in `package.json`
  package.json
  scripts/gulpfiles/build_tasks.js
  scripts/gulpfiles/config.js
  scripts/gulpfiles/package_tasks.js
  scripts/package/blockly.js
  scripts/package/blocks.js
  scripts/package/browser/core.js
  scripts/package/browser/index.js
  scripts/package/core-node.js
  scripts/package/dart.js
  scripts/package/index.js
  scripts/package/javascript.js
  scripts/package/lua.js
  scripts/package/node/core.js
  scripts/package/node/index.js
  scripts/package/php.js
  scripts/package/python.js
  tests/node/node_modules/blockly-test
  tests/node/run_node_test.js
  typings/msg/ce.d.ts
  typings/msg/constants.d.ts
  typings/msg/dtp.d.ts
  typings/msg/hsb.d.ts
  typings/msg/msg.d.ts
  typings/msg/qqq.d.ts
  typings/msg/synonyms.d.ts
  typings/msg/tdd.d.ts
Labels: component: build process, breaking change, PR: feature

#7918 feat: rendered workspace comment
  core/comments.ts
  core/comments/rendered_workspace_comment.ts
  core/comments/workspace_comment.ts
Labels: PR: feature

#7948 fix: Fix block disposal animations
  core/block_animations.ts
Labels: PR: fix

#7919 feat: have RenderedWorkspaceComment implement IBoundedElement and IRenderedElement
  core/comments/rendered_workspace_comment.ts
Labels: PR: feature

#7927 feat: add JSON serialization for workspace comments
  core/comments/workspace_comment.ts
  core/serialization.ts
  core/serialization/priorities.ts
  core/serialization/workspace_comments.ts
  tests/mocha/jso_serialization_test.js
Labels: PR: feature

#7931 fix: comment have XML save and load new workspace comments classes
  core/comments/comment_view.ts
  core/xml.ts
  tests/mocha/clipboard_test.js
  tests/mocha/serializer_test.js
Labels: PR: fix

#7955 fix(typings): Restore inadvertently-deleted `typings/msg/msg.d.ts`; add TS import test
  tests/typescript/src/msg.ts
  typings/msg/msg.d.ts
Labels: PR: fix

#7953 feat(dragging): Create (new) `IDragger` and `IDraggable` interfaces
  core/block_svg.ts
  core/blockly.ts
  core/delete_area.ts
  core/drag_target.ts
  core/interfaces/i_bubble.ts
  core/interfaces/i_delete_area.ts
  core/interfaces/i_drag_target.ts
  core/interfaces/i_draggable.old.ts
  core/interfaces/i_draggable.ts
  core/interfaces/i_dragger.ts
  core/toolbox/toolbox.ts
  core/trashcan.ts
Labels: PR: feature

#7934 fix: comment position in RTL
  core/comments/comment_view.ts
  core/comments/workspace_comment.ts
  core/serialization/workspace_comments.ts
  core/xml.ts
Labels: PR: fix

#7956 feat(dragging): Introduce `Dragger`, implementing `IDragger`
  core/dragging/dragger.ts
Labels: PR: feature

#7963 chore: remove repetitive words in comments
  core/connection.ts
  core/render_management.ts
  core/xml.ts
  demos/blockfactory/block_definition_extractor.js
  scripts/migration/renamings.json5
  tests/scripts/load.mjs
Labels: PR: chore

#7962 chore: Clean up variable assignment.
  appengine/add_timestamps.py
  core/field_variable.ts
  core/serialization/workspaces.ts
  core/shortcut_registry.ts
  core/utils/svg_math.ts
  generators/javascript/math.ts
  scripts/i18n/js_to_json.py
  tests/generators/golden/generated.js
  tests/generators/unittest_dart.js
  tests/generators/unittest_javascript.js
  tests/generators/unittest_php.js
  tests/generators/unittest_python.js
Labels: PR: chore

#7965 fix: comment view styling
  core/comments/comment_view.ts
  media/delete-icon.svg
  media/foldout-icon.svg
Labels: PR: fix

#7967 fix: draggable interface and concrete dragger
  core/dragging/dragger.ts
  core/interfaces/i_deletable.ts
  core/interfaces/i_draggable.ts
Labels: PR: fix

#7968 fix!: remove couldConnect parameter from wouldDelete
  core/block_dragger.ts
  core/bubble_dragger.ts
  core/config.ts
  core/delete_area.ts
  core/dragging/dragger.ts
  core/insertion_marker_manager.ts
  core/interfaces/i_delete_area.ts
  core/toolbox/toolbox.ts
Labels: breaking change, PR: fix

#7973 chore: Remove colour blocks from code demo.
  demos/code/index.html
Labels: PR: chore

#7969 feat!: Throw errors on missing inputs
  core/generator.ts
  generators/dart/procedures.ts
  generators/dart/text.ts
  generators/javascript/procedures.ts
  generators/lua/procedures.ts
  generators/lua/text.ts
  generators/php/procedures.ts
  generators/python/procedures.ts
Labels: breaking change, PR: feature

#7970 feat: add block drag strategy
  core/dragging/block_drag_strategy.ts
Labels: PR: feature

#7971 feat: have blocks use drag strategy
  core/block_svg.ts
  core/dragging/block_drag_strategy.ts
Labels: PR: feature

#7974 feat!: migrate bubble dragging to use new dragging API
  core/blockly.ts
  core/bubble_dragger.ts
  core/bubbles/bubble.ts
  core/dragging/bubble_drag_strategy.ts
  core/gesture.ts
  core/interfaces/i_bubble.ts
  core/workspace_comment_svg.ts
Labels: breaking change, PR: feature

#7975 fix!: various drag-adjacent interfaces
  core/block.ts
  core/block_svg.ts
  core/blockly.ts
  core/delete_area.ts
  core/drag_target.ts
  core/dragging/dragger.ts
  core/interfaces/i_deletable.ts
  core/interfaces/i_delete_area.ts
  core/interfaces/i_drag_target.ts
  core/interfaces/i_draggable.ts
  core/interfaces/i_selectable.ts
  core/shortcut_items.ts
  core/toolbox/toolbox.ts
  core/trashcan.ts
Labels: breaking change, PR: fix
