Repository google/blockly, pull requests merged in 2024-02, with the labels that each got.

#7824 fix: manually add typings for generator classes
  scripts/gulpfiles/package_tasks.js
  tests/typescript/src/generators.ts
  typings/dart.d.ts
  typings/javascript.d.ts
  typings/lua.d.ts
  typings/php.d.ts
  typings/python.d.ts
Labels: PR: fix

#7830 fix: destroy connection highlight when the connection is disposed
  core/rendered_connection.ts
Labels: PR: fix

#7832 fix: fix reference docs toc generation
  scripts/gulpfiles/docs_tasks.js
Labels: PR: fix

#7833 fix: insertion marker previewer finding wrong connection for different conn counts
  core/connection_previewers/insertion_marker_previewer.ts
Labels: PR: fix

#7836 chore: fix v11 branch build
  core/render_management.ts
  scripts/gulpfiles/build_tasks.js
  tests/mocha/render_management_test.js
  tests/typescript/src/generators.ts
Labels: PR: chore

#7837 fix!: have Lua generators use 'nil' instead of 'None'
  generators/lua/lists.ts
Labels: breaking change, PR: fix

#7828 feat: make grid options togglable
  core/grid.ts
  core/workspace_svg.ts
Labels: PR: feature

#7834 fix: disposing of connection previewer
  core/block_dragger.ts
Labels: PR: fix

#7856 chore: rollup of updates from translatewiki for 10.4.0
  msg/json/ar.json
  msg/json/be-tarask.json
  msg/json/bn.json
  msg/json/da.json
  msg/json/el.json
  msg/json/he.json
  msg/json/id.json
  msg/json/inh.json
  msg/json/ja.json
  msg/json/nl.json
  msg/json/pt.json
  msg/json/qqq.json
  msg/json/ta.json
  msg/json/tl.json
  msg/json/ur.json
  msg/json/yue.json
  msg/json/zh-hant.json
Labels: PR: chore

#7857 chore: update metadata for v10.4.0
  tests/scripts/check_metadata.sh
Labels: PR: chore

#7859 fix: connection previewer disposing too early
  core/block_dragger.ts
Labels: PR: fix

#7854 fix: typo in Click event class docs
  core/events/events_click.ts
Labels: PR: fix

#7835 chore: move connection previewer out of subfolder
  core/blockly.ts
  core/insertion_marker_previewer.ts
Labels: PR: chore

#7875 chore: update webdriverio to fix chrome endpoint issue
  package-lock.json
  package.json
Labels: PR: chore

#7874 fix: insertion marker drag scaling
  core/block_dragger.ts
Labels: PR: fix

#7873 fix: restore respecting snap radius
  core/block_dragger.ts
Labels: PR: fix
