Repository google/blockly, pull requests merged in 2024-06, with the labels that each got.

#8203 fix: statement input blocks disappearing
  core/dragging/block_drag_strategy.ts
Labels: PR: fix

#8215 fix(dev-tools): only initSvg on rendered blocks
  demos/blockfactory/blocks.js
Labels: PR: fix

#8214 chore: tsdoc for generator exceptions
  core/generator.ts
Labels: PR: chore

#8226 chore(build): Cleanup npm scripts, tsc includes
  package.json
  tsconfig.json
Labels: component: build process, PR: chore

#8217 fix: Drag and Resize events for workspace comments
  core/bump_objects.ts
  core/comments/comment_view.ts
  core/comments/workspace_comment.ts
  core/dragging/comment_drag_strategy.ts
  core/events/events.ts
  core/events/events_comment_drag.ts
  core/events/events_comment_resize.ts
  core/events/utils.ts
  core/utils/size.ts
  tests/mocha/event_comment_drag_test.js
  tests/mocha/event_comment_resize_test.js
  tests/mocha/event_test.js
  tests/mocha/index.html
  tests/mocha/workspace_comment_test.js
Labels: PR: fix

#8232 chore: Merge develop into v12
  core/bump_objects.ts
  core/comments/comment_view.ts
  core/comments/workspace_comment.ts
  core/dragging/comment_drag_strategy.ts
  core/events/events.ts
  core/events/events_comment_drag.ts
  core/events/events_comment_resize.ts
  core/events/utils.ts
  core/utils/size.ts
  tests/mocha/event_comment_drag_test.js
  tests/mocha/event_comment_resize_test.js
  tests/mocha/event_test.js
  tests/mocha/index.html
  tests/mocha/workspace_comment_test.js
Labels: PR: chore

#8231 feat!: Add support for preserving block comment locations.
  core/bubbles/textinput_bubble.ts
  core/icons/comment_icon.ts
  core/interfaces/i_comment_icon.ts
  core/xml.ts
  tests/mocha/block_test.js
  tests/mocha/comment_test.js
Labels: component: comments, breaking change, PR: feature

#8234 feat: add legacy warning to block factory
  demos/blockfactory/app_controller.js
  demos/blockfactory/factory.css
  demos/blockfactory/index.html
Labels: PR: feature
