Repository google/blockly, pull requests merged in 2024-01, with the labels that each got.

#7729 chore(dependency)!: Bump JSDOM to v23, dropping node 16.
  package-lock.json
  package.json
Labels: breaking change, PR: chore

#7740 feat!: add serialization hooks to procedure models
  core/interfaces/i_parameter_model.ts
  core/interfaces/i_procedure_model.ts
  core/serialization/procedures.ts
  tests/mocha/jso_deserialization_test.js
  tests/mocha/jso_serialization_test.js
  tests/mocha/test_helpers/procedures.js
Labels: breaking change, PR: feature

#7743 feat!: modify icons to use the rendering queue
  core/block_svg.ts
  core/icons/comment_icon.ts
  core/icons/mutator_icon.ts
  core/icons/warning_icon.ts
  core/interfaces/i_has_bubble.ts
  tests/mocha/blocks/procedures_test.js
  tests/mocha/comment_test.js
  tests/mocha/mutator_test.js
Labels: breaking change, PR: feature

#7733 fix: prevent console logging duplicate deprecation warnings
  core/utils/deprecation.ts
Labels: PR: fix

#7745 fix: snap immediately
  core/block_svg.ts
Labels: PR: fix

#7732 chore!: delete deprecations for v11.
  blocks/procedures.ts
  core/block_dragger.ts
  core/block_svg.ts
  core/blockly.ts
  core/clipboard.ts
  core/generator.ts
  core/icons/icon.ts
  core/icons/mutator_icon.ts
  core/inputs/input.ts
  core/main.ts
  core/options.ts
  core/renderers/common/drawer.ts
  core/renderers/measurables/icon.ts
  core/renderers/minimalist/constants.ts
  core/renderers/minimalist/drawer.ts
  core/renderers/minimalist/info.ts
  core/renderers/minimalist/minimalist.ts
  core/renderers/minimalist/renderer.ts
  core/utils/dom.ts
  core/utils/string.ts
  core/workspace_svg.ts
  scripts/gulpfiles/build_tasks.js
Labels: breaking change, PR: chore

#7730 fix!: have insertion markers use json deserialization
  core/insertion_marker_manager.ts
Labels: breaking change, PR: fix

#7747 fix!: `rendered` meaning
  core/block.ts
  core/block_svg.ts
  core/inputs/input.ts
  core/insertion_marker_manager.ts
  core/rendered_connection.ts
  tests/mocha/icon_test.js
  tests/mocha/test_helpers/workspace.js
  tests/mocha/workspace_svg_test.js
Labels: breaking change, PR: fix

#7781 feat: connection highlight zelos
  core/renderers/zelos/constants.ts
  core/renderers/zelos/drawer.ts
Labels: PR: feature

#7784 fix: triggering flyout show from field render causing infinite loop
  core/flyout_base.ts
  core/render_management.ts
  tests/mocha/render_management_test.js
Labels: PR: fix

#7787 fix: cancelling all renders on triggering queued renders
  core/render_management.ts
Labels: PR: fix

#7748 fix: bump neighbours performance regression
  core/block.ts
  core/block_dragger.ts
  core/block_svg.ts
  core/field.ts
  core/gesture.ts
  core/inputs/input.ts
  core/render_management.ts
  core/rendered_connection.ts
  tests/mocha/input_test.js
  tests/mocha/render_management_test.js
Labels: PR: fix

#7788 fix: first block dragged from flyout will have same id
  core/flyout_base.ts
Labels: PR: fix

#7777 fix: block initialization
  blocks/procedures.ts
  core/block.ts
  core/block_svg.ts
  core/field.ts
  core/inputs/input.ts
  core/render_management.ts
  tests/mocha/render_management_test.js
Labels: PR: fix

#7791 chore: Bump Python from 3.7 to 3.12
  appengine/app.yaml
Labels: PR: chore

#7794 fix: prevent block change event firing if editing is cancelled by using keypress
  core/field_input.ts
Labels: PR: fix

#7796 fix: delete highlight path from rendered connection
  core/rendered_connection.ts
Labels: PR: fix

#7792 feat: insertion marker previewer
  core/connection_previewers/insertion_marker_previewer.ts
Labels: PR: feature

#7802 fix: shadow blocks with variable fields are allowed to be deserialized from XML
  core/xml.ts
Labels: PR: fix

#7793 feat: update block dragger to use connection previewer
  core/block_dragger.ts
  core/config.ts
Labels: PR: feature

#7806 fix: export save and load procedure
  core/serialization/procedures.ts
Labels: PR: fix

#7795 fix: highlighting connections in zelos, also highlight connections moving
  core/rendered_connection.ts
  core/renderers/common/drawer.ts
  core/renderers/common/path_object.ts
  core/renderers/common/renderer.ts
  core/renderers/geras/drawer.ts
  core/renderers/measurables/connection.ts
  core/renderers/zelos/drawer.ts
  core/renderers/zelos/renderer.ts
Labels: PR: fix

#7797 fix: deprecate insertion marker and related methods
  core/insertion_marker_manager.ts
  core/renderers/common/renderer.ts
  core/renderers/zelos/renderer.ts
Labels: PR: fix

#7800 fix: have connection previewer use the registry
  core/block_dragger.ts
  core/blockly.ts
  core/connection_previewers/insertion_marker_previewer.ts
Labels: PR: fix
