Repository google/blockly, pull requests merged in 2024-04, with the labels that each got.

#7976 feat: make comment a draggable
  core/comments/rendered_workspace_comment.ts
  core/comments/workspace_comment.ts
  core/dragging/comment_drag_strategy.ts
Labels: PR: feature

#7988 feat: allow duplicate registry values
  core/registry.ts
  tests/mocha/registry_test.js
Labels: PR: feature

#7945 fix: comment create and delete events
  core/comments/workspace_comment.ts
  core/events/events_comment_base.ts
  core/events/events_comment_change.ts
  core/events/events_comment_create.ts
  core/events/events_comment_delete.ts
  core/events/events_comment_move.ts
  core/xml.ts
  tests/mocha/comment_view_test.js
  tests/mocha/event_comment_change_test.js
  tests/mocha/event_comment_create_test.js
  tests/mocha/event_comment_delete_test.js
  tests/mocha/event_comment_move_test.js
  tests/mocha/event_test.js
  tests/mocha/index.html
  tests/mocha/old_workspace_comment_test.js
  tests/mocha/workspace_comment_test.js
Labels: PR: fix

#7964 fix: comment icon interface re serialization
  core/icons/comment_icon.ts
  core/interfaces/i_comment_icon.ts
  tests/mocha/block_test.js
Labels: PR: fix

#7980 fix: Assign to containerDiv blockyWidgetDiv if it already exists
  core/widgetdiv.ts
Labels: PR: fix

#7946 fix: prevent default undo
  core/shortcut_items.ts
Labels: PR: fix

#7977 feat: support dragging comments in the gesture
  core/comments/rendered_workspace_comment.ts
  core/gesture.ts
Labels: PR: feature

#7852 feat: support keyboard navigation of flyout buttons
  core/flyout_base.ts
  core/flyout_button.ts
  core/keyboard_nav/ast_node.ts
  core/renderers/common/marker_svg.ts
Labels: PR: feature

#7978 fix: comment colours when dragging
  core/comments/comment_view.ts
Labels: PR: fix

#7947 fix: comment move and change events
  core/comments/rendered_workspace_comment.ts
  core/comments/workspace_comment.ts
  core/events/events_comment_change.ts
  core/events/events_comment_move.ts
  tests/mocha/workspace_comment_test.js
Labels: PR: fix

#7991 feat!: change gestures to look at selected when dragging
  blocks/procedures.ts
  core/block_svg.ts
  core/bubbles/bubble.ts
  core/bubbles/mini_workspace_bubble.ts
  core/bubbles/text_bubble.ts
  core/bubbles/textinput_bubble.ts
  core/clipboard/block_paster.ts
  core/comments/rendered_workspace_comment.ts
  core/common.ts
  core/contextmenu.ts
  core/dragging/block_drag_strategy.ts
  core/gesture.ts
  core/interfaces/i_selectable.ts
  tests/mocha/comment_deserialization_test.js
Labels: breaking change, PR: feature

#7992 fix: dragging shadow blocks
  core/block_svg.ts
  core/dragging/block_drag_strategy.ts
Labels: PR: fix

#7949 feat: comment collapse event
  core/comments/workspace_comment.ts
  core/events/events.ts
  core/events/events_comment_collapse.ts
  core/events/utils.ts
  tests/mocha/event_comment_collapse_test.js
  tests/mocha/index.html
  tests/mocha/workspace_comment_test.js
Labels: PR: feature

#7994 chore!: delete drag stack
  core/blockly.ts
  core/gesture.ts
  core/internal_constants.ts
Labels: breaking change, PR: chore

#7954 chore: add webdriver tests for workspace comments
  tests/browser/test/workspace_comment_test.js
Labels: PR: chore

#8002 feat: add toFlyoutData method for compatibility with backpack
  core/block_svg.ts
Labels: PR: feature

#7996 feat: visual comment selection
  core/comments/comment_view.ts
  core/comments/rendered_workspace_comment.ts
  core/gesture.ts
Labels: PR: feature

#7997 fix: bubbles not being returned to the correct layer after drag
  core/dragging/bubble_drag_strategy.ts
Labels: PR: fix

#8000 fix: insertion marker firing move event
  core/insertion_marker_previewer.ts
Labels: PR: fix

#7999 fix: drag cursor
  core/css.ts
Labels: PR: fix

#7998 fix: blocks not being returned to the correct layer if their drag is reverted with no parent
  core/dragging/block_drag_strategy.ts
Labels: PR: fix

#8016 fix: compatibility with scroll plugin
  core/blockly.ts
  core/dragging/dragger.ts
  core/gesture.ts
Labels: PR: fix

#8017 fix: correct dropdown arrow placement for Thrasos on Safari
  core/field_dropdown.ts
Labels: PR: fix

#8015 fix: backpack compatibility (rename `toFlyoutData` to `toFlyoutInfo`)
  core/block_svg.ts
Labels: PR: fix

#8021 fix: dragging related exports for v11
  core/blockly.ts
  core/workspace_svg.ts
Labels: PR: fix

#8020 fix: revert dragger name
  core/dragging/dragger.ts
  core/gesture.ts
  core/registry.ts
Labels: PR: fix

#8023 feat: add ability to delete workspace comments
  core/comments/rendered_workspace_comment.ts
  core/shortcut_items.ts
Labels: PR: feature

#8025 fix: more drag exports
  core/blockly.ts
  core/dragging.ts
Labels: PR: fix

#8024 feat!: add ability to copy and paste workspace comments
  core/blockly.ts
  core/clipboard/workspace_comment_paster.ts
  core/comments/rendered_workspace_comment.ts
  core/serialization/workspace_comments.ts
  core/workspace.ts
  core/workspace_svg.ts
Labels: breaking change, PR: feature

#8040 fix: text input bubble css
  core/bubbles/textinput_bubble.ts
Labels: PR: fix

#8035 feat!: Add context menu options for workspace comments
  core/block_svg.ts
  core/blockly.ts
  core/comments/rendered_workspace_comment.ts
  core/contextmenu.ts
  core/contextmenu_items.ts
  core/contextmenu_registry.ts
  core/gesture.ts
  core/workspace_svg.ts
  tests/playground.html
Labels: breaking change, PR: feature

#8036 fix: comment keyboard shortcuts
  core/shortcut_items.ts
Labels: PR: fix

#8037 fix: bumping comments into bounds
  core/bump_objects.ts
  core/dragging/comment_drag_strategy.ts
Labels: PR: fix

#8038 chore: delete old comments
  core/blockly.ts
  core/bump_objects.ts
  core/comments/workspace_comment.ts
  core/workspace.ts
  core/workspace_comment.ts
  core/workspace_comment_svg.ts
  core/workspace_svg.ts
  tests/mocha/event_test.js
Labels: PR: chore

#7958 feat!: Invalid Blocks
  blocks/loops.ts
  blocks/procedures.ts
  core/block.ts
  core/block_svg.ts
  core/constants.ts
  core/contextmenu_items.ts
  core/events/events_block_change.ts
  core/events/utils.ts
  core/flyout_base.ts
  core/serialization/blocks.ts
  core/trashcan.ts
  core/utils/toolbox.ts
  core/xml.ts
  demos/blockfactory/blocks.js
  demos/blockfactory/factory_utils.js
  msg/json/en.json
  msg/json/qqq.json
  msg/messages.js
  tests/mocha/block_test.js
  tests/mocha/blocks/loops_test.js
  tests/mocha/blocks/procedures_test.js
  tests/mocha/generator_test.js
  tests/mocha/icon_test.js
  tests/mocha/index.html
  tests/mocha/jso_serialization_test.js
  tests/mocha/serializer_test.js
Labels: breaking change, PR: feature

#8042 fix: comment text area size in samples
  core/comments/comment_view.ts
Labels: PR: fix

#8043 chore: fix comments being resizable when readonly
  core/comments/comment_view.ts
  tests/playground.html
Labels: PR: chore

#8044 fix: comment highlight being positioned incorrectly in RTL
  core/comments/comment_view.ts
Labels: PR: fix

#8050 fix(build): Reintroduce shims for subpackage entrypoints
  scripts/gulpfiles/package_tasks.js
  scripts/package/templates/node.template
Labels: component: build process, PR: fix

#8041 fix: Correct list's "find" and "get" blocks help.
  msg/json/constants.json
  msg/json/en.json
  msg/json/qqq.json
  msg/json/synonyms.json
  msg/messages.js
  scripts/i18n/create_messages.py
  scripts/i18n/js_to_json.py
Labels: PR: fix

#8051 feat: add block factory export in json
  demos/blockfactory/app_controller.js
  demos/blockfactory/block_library_controller.js
  demos/blockfactory/index.html
Labels: PR: feature

#8049 fix: Don't record undo events for enable/disable
  blocks/loops.ts
  blocks/procedures.ts
Labels: PR: fix
