Repository google/blockly, pull requests merged in 2024-05, with the labels that each got.

#8053 fix: prevent duplication of comment icon bubbles
  core/icons/comment_icon.ts
Labels: PR: fix

#8054 fix!: Only fire intermediate events when editing input with invalid text.
  core/field.ts
  core/field_angle.ts
  core/field_input.ts
  tests/mocha/field_angle_test.js
  tests/mocha/field_number_test.js
  tests/mocha/field_textinput_test.js
Labels: breaking change, PR: fix

#8065 refactor: split out block serialization for creating new blocks from the flyout
  core/flyout_base.ts
Labels: PR: refactor

#8058 fix: Don't record undo events for enable/disable
  blocks/loops.ts
  blocks/procedures.ts
Labels: PR: fix

#8084 feat: allow the dialog methods to take in extra parameters
  core/dialog.ts
  tests/mocha/contextmenu_items_test.js
  tests/mocha/dialog_test.js
  tests/mocha/index.html
  tests/mocha/test_helpers/workspace.js
Labels: PR: feature

#8064 fix!: add getContents to IFlyout
  core/flyout_base.ts
  core/interfaces/i_flyout.ts
  core/keyboard_nav/ast_node.ts
Labels: breaking change, PR: fix

#8085 revert: "feat: allow the dialog methods to take in extra parameters"
  core/dialog.ts
  tests/mocha/contextmenu_items_test.js
  tests/mocha/dialog_test.js
  tests/mocha/index.html
  tests/mocha/test_helpers/workspace.js
Labels: PR: revert

#8062 fix: improve types in FieldRegistry
  core/field.ts
  core/field_angle.ts
  core/field_checkbox.ts
  core/field_colour.ts
  core/field_dropdown.ts
  core/field_image.ts
  core/field_label.ts
  core/field_number.ts
  core/field_registry.ts
  core/field_textinput.ts
  tests/mocha/field_registry_test.js
Labels: PR: fix

#8091 feat(build)!: Introduce ESM entrypoints
  package.json
  scripts/gulpfiles/build_tasks.js
  typings/msg/yue.d.ts
Labels: component: build process, breaking change, PR: feature

#8070 feat: Add snapping to workspace comments.
  core/block_svg.ts
  core/comments/rendered_workspace_comment.ts
  core/grid.ts
Labels: PR: feature

#8097 chore(build): Set `"type": "commonjs"` in `dist/package.json`
  scripts/gulpfiles/package_tasks.js
Labels: component: build process, PR: chore

#8100 release: Merge branch 'develop' into rc/v11.0.0
  core/field.ts
  core/field_checkbox.ts
  core/field_dropdown.ts
  core/field_image.ts
  core/field_input.ts
  core/field_label.ts
  core/field_number.ts
  core/field_registry.ts
  core/field_textinput.ts
  core/flyout_base.ts
  core/interfaces/i_flyout.ts
  core/keyboard_nav/ast_node.ts
  demos/blockfactory/app_controller.js
  demos/blockfactory/block_library_controller.js
  demos/blockfactory/index.html
  msg/json/constants.json
  msg/json/en.json
  msg/json/qqq.json
  msg/json/synonyms.json
  msg/messages.js
  scripts/i18n/create_messages.py
  scripts/i18n/js_to_json.py
  tests/mocha/field_number_test.js
  tests/mocha/field_registry_test.js
  tests/mocha/field_textinput_test.js
Labels: PR: chore

#8104 fix: Remove deprecation warnings for 'disabled'.
  core/serialization/blocks.ts
  core/xml.ts
Labels: PR: fix

#8107 fix: drag cursor being incorrect for flyout blocks
  core/block_svg.ts
Labels: PR: fix

#8109 fix: connection db error for insertion markers
  core/insertion_marker_previewer.ts
Labels: PR: fix

#8120 fix: extra insertion markers being created
  core/insertion_marker_previewer.ts
Labels: PR: fix

#8122 fix: JSON deserialization not firing variable create events for blocks
  core/serialization/blocks.ts
Labels: PR: fix

#8125 fix: workspace comment bounding box affecting RTL zoom
  core/comments/rendered_workspace_comment.ts
Labels: PR: fix

#8130 chore: rename airstrike -> scatter
  tests/playground.html
Labels: PR: chore

#8127 fix: comment move events and snapping
  core/comments/rendered_workspace_comment.ts
  core/dragging/comment_drag_strategy.ts
Labels: PR: fix

#8140 fix: change cursor to grab on ws comment bar
  core/comments/comment_view.ts
Labels: PR: fix

#8139 chore: fix playground context menu
  tests/playgrounds/advanced_playground.html
Labels: PR: chore

#8126 fix: undoing block delete over trashcan creates block in wrong place
  core/dragging/dragger.ts
Labels: PR: fix

#8151 fix: comment handle position in RTL
  core/bubbles/textinput_bubble.ts
Labels: PR: fix

#8141 fix: Zelos comments shouldn't be bold
  core/renderers/zelos/constants.ts
  media/resize-handle.svg
Labels: PR: fix

#8138 fix: dragging blocks by shadows to delete
  core/block.ts
  core/dragging/block_drag_strategy.ts
  core/gesture.ts
Labels: PR: fix

#8136 fix: comment size not respecting collapsed-ness
  core/comments/comment_view.ts
  core/comments/rendered_workspace_comment.ts
  tests/mocha/workspace_comment_test.js
Labels: PR: fix

#8154 chore: load block factory from unpkg
  demos/blockfactory/index.html
Labels: PR: chore

#8152 fix: comment text area bottom border hidden
  core/comments/comment_view.ts
Labels: PR: fix

#8158 fix: Properly size comments.
  core/bubbles/textinput_bubble.ts
  core/comments/comment_view.ts
  core/comments/rendered_workspace_comment.ts
Labels: PR: fix

#8153 fix: creating comments in RTL
  core/comments/rendered_workspace_comment.ts
Labels: PR: fix

#8149 fix: delete area animation
  core/block_animations.ts
  core/css.ts
  core/dragging/dragger.ts
  core/layer_manager.ts
Labels: PR: fix

#8161 fix: Normalize CSS between comment types
  core/bubbles/textinput_bubble.ts
  core/comments/comment_view.ts
Labels: PR: fix

#8123 fix: paste in a better spot
  core/clipboard/block_paster.ts
Labels: PR: fix

#8162 chore: rollup of updates from TranslateWiki
  msg/json/de.json
  msg/json/el.json
  msg/json/es.json
  msg/json/fa.json
  msg/json/fr.json
  msg/json/gl.json
  msg/json/ia.json
  msg/json/ko.json
  msg/json/ms.json
  msg/json/ne.json
  msg/json/nl.json
  msg/json/pt-br.json
  msg/json/ru.json
  msg/json/ta.json
  msg/json/tdd.json
  msg/json/tr.json
  msg/json/vi.json
  msg/json/zh-hans.json
  msg/json/zh-hant.json
Labels: PR: chore

#8163 chore: update metadata for v11 release
  tests/scripts/check_metadata.sh
Labels: PR: chore

#8150 fix: Only hide WidgetDiv if it is associated with the affected workspace.
  core/block_svg.ts
  core/comments/rendered_workspace_comment.ts
  core/contextmenu.ts
  core/field_input.ts
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
  core/widgetdiv.ts
  core/workspace_svg.ts
Labels: PR: fix

#8165 chore: merge master into develop following v11.0.0
  package-lock.json
  package.json
Labels: PR: chore

#8166 feat(tests): Browser test helper to get workspace svg root
  tests/browser/test/field_edits_test.js
  tests/browser/test/test_setup.js
Labels: PR: feature

#8173 feat: merge branch `osd` into `develop`
  .gitattributes
  core/field_input.ts
  core/flyout_base.ts
  core/flyout_button.ts
  core/flyout_horizontal.ts
  core/flyout_vertical.ts
  core/shortcut_items.ts
  core/workspace_svg.ts
Labels: PR: feature

#8179 fix: lang file imports
  scripts/gulpfiles/build_tasks.js
Labels: PR: fix

#8172 fix: dragging and disposing of shadows
  core/block.ts
  core/dragging/block_drag_strategy.ts
  core/dragging/dragger.ts
  core/gesture.ts
Labels: PR: fix

#8186 chore: Merge master back into develop following v11.1.0 release
  package-lock.json
  package.json
Labels: PR: chore

#8188 fix: change which element keydown is bound to from document to injection div
  core/inject.ts
  tests/mocha/keydown_test.js
Labels: PR: fix
