Repository google/blockly, pull requests merged in 2025-03, with the labels that each got.

#8810 chore: Try adding additional permissions.
  .github/workflows/assign_reviewers.yml
  .github/workflows/conventional-label.yml
Labels: PR: chore

#8817 fix: fix bug that modalInputs option is not working in toolbox area
  core/toolbox/toolbox.ts
  core/trashcan.ts
  core/workspace_svg.ts
Labels: PR: fix

#8813 chore: Merge `master` back into `develop` following 11.2.2 release
  package-lock.json
  package.json
Labels: PR: chore

#8803 refactor!: Remove old cursor and tab support.
  core/block_svg.ts
  core/blockly.ts
  core/field.ts
  core/field_input.ts
  core/keyboard_nav/basic_cursor.ts
  core/keyboard_nav/tab_navigate_cursor.ts
Labels: breaking change, PR: refactor

#8829 feat: Add a method for creating flyout options
  core/toolbox/toolbox.ts
  core/trashcan.ts
  core/workspace_svg.ts
Labels: PR: feature
