Repository google/blockly, pull requests merged in 2025-06, with the labels that each got.

#9137 fix: Dispatch keyboard events with the workspace they occurred on.
  core/common.ts
Labels: PR: fix

#9151 feat: Add support for keyboard navigation into mutator workspaces.
  core/bubbles/mini_workspace_bubble.ts
  core/icons/mutator_icon.ts
  core/keyboard_nav/icon_navigation_policy.ts
  core/keyboard_nav/workspace_navigation_policy.ts
  core/navigator.ts
  core/workspace_svg.ts
Labels: PR: feature

#9154 feat: make comment editor separately focusable from comment itself
  core/comments.ts
  core/comments/comment_editor.ts
  core/comments/comment_view.ts
  core/comments/rendered_workspace_comment.ts
  core/workspace_svg.ts
Labels: PR: feature

#9150 refactor(interfaces): Make type predicates more robust
  core/interfaces/i_autohideable.ts
  core/interfaces/i_comment_icon.ts
  core/interfaces/i_copyable.ts
  core/interfaces/i_deletable.ts
  core/interfaces/i_draggable.ts
  core/interfaces/i_focusable_node.ts
  core/interfaces/i_focusable_tree.ts
  core/interfaces/i_has_bubble.ts
  core/interfaces/i_icon.ts
  core/interfaces/i_legacy_procedure_blocks.ts
  core/interfaces/i_observable.ts
  core/interfaces/i_paster.ts
  core/interfaces/i_procedure_block.ts
  core/interfaces/i_rendered_element.ts
  core/interfaces/i_selectable.ts
  core/interfaces/i_serializable.ts
  tests/mocha/block_test.js
  tests/mocha/test_helpers/icon_mocks.js
Labels: PR: refactor

#9172 fix: clear touch identifier on comment text area pointerdown
  core/bubbles/textinput_bubble.ts
  core/comments/comment_editor.ts
Labels: PR: fix

#9149 build: Refactor gulpfiles from CJS to ESM
  eslint.config.mjs
  gulpfile.js
  gulpfile.mjs
  package.json
  scripts/gulpfiles/appengine_tasks.mjs
  scripts/gulpfiles/build_tasks.mjs
  scripts/gulpfiles/config.mjs
  scripts/gulpfiles/docs_tasks.mjs
  scripts/gulpfiles/git_tasks.mjs
  scripts/gulpfiles/helper_tasks.js
  scripts/gulpfiles/helper_tasks.mjs
  scripts/gulpfiles/package_tasks.mjs
  scripts/gulpfiles/release_tasks.mjs
  scripts/gulpfiles/test_tasks.mjs
Labels: component: build process, PR: chore
