Repository google/blockly, pull requests merged in 2025-05, with the labels that each got.

#8951 fix: remove black outline on focused items
  core/css.ts
Labels: PR: fix

#8941 feat: Update line cursor to use focus manager
  core/blockly.ts
  core/focus_manager.ts
  core/keyboard_nav/line_cursor.ts
  tests/mocha/cursor_test.js
  tests/mocha/focus_manager_test.js
  tests/mocha/test_helpers/setup_teardown.js
Labels: PR: feature

#8956 fix: Fix conventional auto labeling
  .github/workflows/conventional-label.yml
Labels: PR: fix

#8959 feat(WorkspaceSvg): Add support for tracking keyboard moves
  core/workspace_svg.ts
Labels: component: keyboard_nav, PR: feature

#8946 refactor!: Finish refactor of `WorkspaceSvg` `VariableMap` methods
  core/block_svg.ts
  core/events/events_var_create.ts
  core/events/events_var_delete.ts
  core/events/events_var_rename.ts
  core/field_variable.ts
  core/variable_map.ts
  core/variables.ts
  core/variables_dynamic.ts
  core/workspace.ts
  core/workspace_svg.ts
  core/xml.ts
Labels: component: variables, breaking change, PR: refactor

#8948 fix: Address remaining invisible input positions
  core/keyboard_nav/ast_node.ts
Labels: PR: fix

#8917 feat: add scope to keyboard shortcuts and use it
  core/shortcut_items.ts
  core/shortcut_registry.ts
  tests/mocha/keydown_test.js
  tests/mocha/shortcut_registry_test.js
Labels: PR: feature

#8961 fix!: Remove alt+key commands
  core/shortcut_items.ts
  tests/mocha/keydown_test.js
Labels: issue: bug, breaking change

#8963 feat(WorkspaceSvg): Ignore gestures when keyboard move in progress
  core/workspace_svg.ts
Labels: component: touch, component: keyboard_nav, PR: feature

#8982 fix: Ensure flyout remains open after creating a variable with mouse
  core/workspace_svg.ts
Labels: PR: fix

#8981 fix: Synchronize gestures and focus
  core/block_svg.ts
  core/clipboard/block_paster.ts
  core/dragging/dragger.ts
  core/dropdowndiv.ts
  core/focus_manager.ts
  core/gesture.ts
  core/widgetdiv.ts
Labels: PR: fix

#8990 fix: focus for autohideable flyouts
  core/interfaces/i_autohideable.ts
  core/workspace_svg.ts
Labels: PR: fix

#8980 fix: Replace explicit calls to refreshToolboxSelection with a workspace listener
  blocks/variables.ts
  blocks/variables_dynamic.ts
  core/field_variable.ts
  core/variable_map.ts
  core/workspace_svg.ts
Labels: issue: bug, PR: fix

#8995 fix: Add private to variableChangeCallback
  core/workspace_svg.ts
Labels: PR: fix

#8993 fix: use copyable interface for cut action, add tests
  core/shortcut_items.ts
  tests/mocha/index.html
  tests/mocha/shortcut_items_test.js
Labels: PR: fix

#8997 fix: Improve missing node resiliency
  core/focus_manager.ts
  core/interfaces/i_focusable_tree.ts
  tests/mocha/focus_manager_test.js
Labels: PR: fix

#8992 refactor!: Use navigation rulesets instead of ASTNode to control keyboard navigation.
  core/block_flyout_inflater.ts
  core/block_svg.ts
  core/blockly.ts
  core/button_flyout_inflater.ts
  core/field.ts
  core/field_checkbox.ts
  core/field_dropdown.ts
  core/field_image.ts
  core/field_label.ts
  core/field_number.ts
  core/field_textinput.ts
  core/flyout_base.ts
  core/flyout_button.ts
  core/flyout_item.ts
  core/flyout_separator.ts
  core/interfaces/i_navigable.ts
  core/interfaces/i_navigation_policy.ts
  core/keyboard_nav/ast_node.ts
  core/keyboard_nav/block_navigation_policy.ts
  core/keyboard_nav/connection_navigation_policy.ts
  core/keyboard_nav/field_navigation_policy.ts
  core/keyboard_nav/flyout_button_navigation_policy.ts
  core/keyboard_nav/flyout_navigation_policy.ts
  core/keyboard_nav/flyout_separator_navigation_policy.ts
  core/keyboard_nav/line_cursor.ts
  core/keyboard_nav/marker.ts
  core/keyboard_nav/workspace_navigation_policy.ts
  core/label_flyout_inflater.ts
  core/navigator.ts
  core/rendered_connection.ts
  core/separator_flyout_inflater.ts
  core/workspace_svg.ts
  tests/mocha/astnode_test.js
  tests/mocha/cursor_test.js
  tests/mocha/index.html
  tests/mocha/navigation_test.js
  tests/typescript/src/field/different_user_input.ts
Labels: breaking change, PR: refactor

#8991 fix!: remove MarkerSvg and uses
  core/block_svg.ts
  core/field.ts
  core/flyout_button.ts
  core/interfaces/i_ast_node_location_svg.ts
  core/keyboard_nav/line_cursor.ts
  core/keyboard_nav/marker.ts
  core/marker_manager.ts
  core/renderers/common/block_rendering.ts
  core/renderers/common/i_path_object.ts
  core/renderers/common/marker_svg.ts
  core/renderers/common/path_object.ts
  core/renderers/common/renderer.ts
  core/renderers/zelos/marker_svg.ts
  core/renderers/zelos/renderer.ts
  core/renderers/zelos/zelos.ts
  core/workspace_svg.ts
Labels: breaking change, PR: fix

#9012 chore: bump version to 12.0.0-beta.5
  package.json
Labels: PR: chore

#9013 fix!: delete marker move event and tests
  core/events/events.ts
  core/events/events_marker_move.ts
  core/events/predicates.ts
  tests/mocha/event_marker_move_test.js
  tests/mocha/event_test.js
  tests/mocha/index.html
Labels: breaking change, PR: fix

#9014 fix!: delete ASTNode and references
  core/blockly.ts
  core/keyboard_nav/ast_node.ts
  core/keyboard_nav/line_cursor.ts
  core/keyboard_nav/marker.ts
Labels: breaking change, PR: fix

#9015 fix!: delete IASTNodeLocation and friends
  core/block.ts
  core/block_svg.ts
  core/blockly.ts
  core/connection.ts
  core/field.ts
  core/flyout_button.ts
  core/interfaces/i_ast_node_location.ts
  core/interfaces/i_ast_node_location_svg.ts
  core/interfaces/i_ast_node_location_with_block.ts
  core/workspace.ts
  core/workspace_svg.ts
Labels: breaking change, PR: fix

#9004 feat!: Make everything ISelectable focusable
  blocks/procedures.ts
  core/block_svg.ts
  core/bubbles/bubble.ts
  core/bubbles/textinput_bubble.ts
  core/clipboard/workspace_comment_paster.ts
  core/comments/rendered_workspace_comment.ts
  core/common.ts
  core/contextmenu.ts
  core/contextmenu_items.ts
  core/css.ts
  core/field.ts
  core/flyout_base.ts
  core/flyout_button.ts
  core/focus_manager.ts
  core/icons/comment_icon.ts
  core/icons/icon.ts
  core/icons/mutator_icon.ts
  core/icons/warning_icon.ts
  core/interfaces/i_bubble.ts
  core/interfaces/i_focusable_node.ts
  core/interfaces/i_has_bubble.ts
  core/interfaces/i_icon.ts
  core/interfaces/i_selectable.ts
  core/keyboard_nav/line_cursor.ts
  core/layer_manager.ts
  core/rendered_connection.ts
  core/toolbox/toolbox.ts
  core/toolbox/toolbox_item.ts
  core/workspace_dragger.ts
  core/workspace_svg.ts
  tests/mocha/block_test.js
  tests/mocha/focus_manager_test.js
  tests/mocha/focusable_tree_traverser_test.js
  tests/mocha/test_helpers/icon_mocks.js
Labels: breaking change, PR: feature

#9016 chore: remove now-unneeded cast
  core/contextmenu_registry.ts
  core/shortcut_registry.ts
Labels: PR: chore

#9025 fix: Don't fire events for changes to potential variables
  core/variable_map.ts
  core/workspace.ts
Labels: PR: fix

#9033 refactor: Make INavigable extend IFocusableNode.
  core/block_svg.ts
  core/field.ts
  core/flyout_button.ts
  core/flyout_separator.ts
  core/interfaces/i_navigable.ts
  core/interfaces/i_navigation_policy.ts
  core/keyboard_nav/block_navigation_policy.ts
  core/keyboard_nav/connection_navigation_policy.ts
  core/keyboard_nav/field_navigation_policy.ts
  core/keyboard_nav/flyout_button_navigation_policy.ts
  core/keyboard_nav/flyout_navigation_policy.ts
  core/keyboard_nav/flyout_separator_navigation_policy.ts
  core/keyboard_nav/workspace_navigation_policy.ts
  core/navigator.ts
  core/rendered_connection.ts
  core/workspace_svg.ts
Labels: PR: refactor

#9031 fix: Improve robustness of `IFocusableNode` uses
  core/utils/focusable_tree_traverser.ts
  core/workspace_svg.ts
Labels: PR: fix

#9030 fix: don't visit connections with the cursor.
  core/keyboard_nav/block_navigation_policy.ts
  core/keyboard_nav/field_navigation_policy.ts
  core/keyboard_nav/line_cursor.ts
  core/keyboard_nav/workspace_navigation_policy.ts
  tests/mocha/cursor_test.js
  tests/mocha/navigation_test.js
Labels: PR: fix

#9019 chore: add node test for json with a dropdown field
  tests/node/run_node_test.mjs
Labels: PR: chore

#9011 fix: Fix regressions in `Field`.
  core/field.ts
  core/field_image.ts
  core/field_input.ts
  core/field_variable.ts
Labels: PR: fix

#9039 fix!: remove deprecated setEnabled and backwards event filtering
  core/block.ts
  core/block_svg.ts
  core/events/utils.ts
  tests/mocha/event_test.js
Labels: breaking change, PR: fix

#9034 fix: Ensure selection stays when dragging blocks, comments, and bubbles
  core/layer_manager.ts
  core/renderers/zelos/path_object.ts
  tests/mocha/layering_test.js
Labels: PR: fix

#9045 fix: Ensure BlockSvg is uniquely focusable on the page
  core/block_svg.ts
  core/interfaces/i_focusable_node.ts
  core/workspace_svg.ts
Labels: PR: fix

#9032 fix: Ensure cursor syncs with more than just focused blocks
  core/keyboard_nav/line_cursor.ts
Labels: PR: fix

#9049 fix: Reenable support for tabbing between fields.
  core/field_input.ts
Labels: PR: fix

#9047 fix!: deepMerge for arrays, shortcut keycodes returned as array
  core/utils/object.ts
  tests/mocha/shortcut_registry_test.js
  tests/mocha/utils_test.js
Labels: breaking change, PR: fix

#9050 fix: Fix bug when referencing HTMLElement in non-browser environments.
  core/field_dropdown.ts
Labels: PR: fix

#9052 fix: Remove un-typesafe cast.
  core/utils/dom.ts
Labels: PR: fix

#9054 fix: Make clickable but non-editable fields navigable.
  core/keyboard_nav/field_navigation_policy.ts
Labels: PR: fix

#9056 chore: Rollup of 2025 Q2 updates from TranslateWiki
  msg/json/ar.json
  msg/json/az.json
  msg/json/be-tarask.json
  msg/json/be.json
  msg/json/bg.json
  msg/json/ce.json
  msg/json/constants.json
  msg/json/cs.json
  msg/json/de.json
  msg/json/diq.json
  msg/json/es.json
  msg/json/et.json
  msg/json/fa.json
  msg/json/fr.json
  msg/json/he.json
  msg/json/hr.json
  msg/json/ia.json
  msg/json/id.json
  msg/json/ja.json
  msg/json/kn.json
  msg/json/ko.json
  msg/json/lb.json
  msg/json/nb.json
  msg/json/nl.json
  msg/json/pa.json
  msg/json/pl.json
  msg/json/pms.json
  msg/json/pt-br.json
  msg/json/pt.json
  msg/json/qqq.json
  msg/json/sd.json
  msg/json/sk.json
  msg/json/sr.json
  msg/json/sv.json
  msg/json/synonyms.json
  msg/json/tcy.json
  msg/json/tdd.json
  msg/json/tl.json
  msg/json/tr.json
  msg/json/ug-arab.json
  msg/json/uk.json
  msg/json/ur.json
  msg/json/xmf.json
  msg/json/zgh.json
  msg/json/zh-hans.json
Labels: PR: chore

#9058 chore: Update metadata for 2025 Q2 release
  tests/scripts/check_metadata.sh
Labels: PR: chore

#9063 fix: Ensure `FieldImage` is clickable when appropriate
  core/field_image.ts
  tests/mocha/field_image_test.js
Labels: PR: fix

#9071 fix: When moving to a field, scroll the field's block into view
  core/keyboard_nav/line_cursor.ts
Labels: PR: fix

#9062 fix: Limit `LineCursor` & focus syncing
  core/keyboard_nav/line_cursor.ts
Labels: PR: fix

#9064 fix: Fix browser tests PART 1
  tests/browser/test/basic_block_test.mjs
  tests/browser/test/basic_playground_test.mjs
  tests/browser/test/delete_blocks_test.mjs
  tests/browser/test/extensive_test.mjs
  tests/browser/test/mutator_test.mjs
  tests/browser/test/test_setup.mjs
Labels: PR: fix

#9073 fix: focus something after deleting a block
  core/block_svg.ts
Labels: PR: fix

#9074 fix: focus after drag and deleting comments
  core/block_svg.ts
  core/comments/rendered_workspace_comment.ts
Labels: PR: fix

#9080 fix: Visit all nodes in getNextSibling and getPreviousSibling
  core/keyboard_nav/block_navigation_policy.ts
  tests/mocha/navigation_test.js
Labels: PR: fix

#9086 feat: Add more ephemeral overrides for drop-downs.
  core/dropdowndiv.ts
  core/widgetdiv.ts
  tests/mocha/dropdowndiv_test.js
  tests/mocha/widget_div_test.js
Labels: PR: feature

#9090 fix: Don't visit collapsed blocks
  core/keyboard_nav/block_navigation_policy.ts
  tests/mocha/navigation_test.js
Labels: PR: fix

#9104 feat: Allow visiting empty input connections.
  core/keyboard_nav/block_navigation_policy.ts
  core/keyboard_nav/connection_navigation_policy.ts
  core/keyboard_nav/field_navigation_policy.ts
  core/keyboard_nav/icon_navigation_policy.ts
  tests/mocha/cursor_test.js
  tests/mocha/navigation_test.js
Labels: PR: feature

#9109 fix: Copy shortcuts before returning them.
  core/shortcut_registry.ts
Labels: PR: fix

#9079 feat: Automatically manage focus tree tab indexes
  core/bubbles/bubble.ts
  core/comments/rendered_workspace_comment.ts
  core/field.ts
  core/flyout_base.ts
  core/flyout_button.ts
  core/focus_manager.ts
  core/icons/icon.ts
  core/interfaces/i_focusable_node.ts
  core/renderers/common/path_object.ts
  core/toolbox/category.ts
  core/toolbox/separator.ts
  core/toolbox/toolbox.ts
  core/workspace_svg.ts
  tests/mocha/focus_manager_test.js
  tests/mocha/index.html
Labels: PR: feature

#8924 feat: add keyboard navigation controller
  core/blockly.ts
  core/gesture.ts
  core/keyboard_navigation_controller.ts
  tests/mocha/index.html
  tests/mocha/keyboard_navigation_controller_test.js
Labels: PR: feature

#9110 feat: ephemeral focus public getter, use in shortcut precondition
  core/focus_manager.ts
  core/shortcut_items.ts
Labels: PR: feature

#9116 fix: context menus on flyout
  core/workspace_svg.ts
Labels: PR: fix

#9117 fix: Fix bug that caused the focus manager to attempt to focus unfocusable elements.
  core/layer_manager.ts
Labels: PR: fix
