Repository google/blockly, pull requests merged in 2025-08, with the labels that each got.

#9265 fix: Check for existing event group in cleanUp()
  core/workspace_svg.ts
Labels: PR: fix

#9263 fix: dont add comments to full block fields
  core/block.ts
  core/contextmenu_items.ts
Labels: PR: fix

#9282 refactor: Make `InsertionMarkerPreviewer`'s block serialization amenable to subclassing.
  core/insertion_marker_previewer.ts
Labels: PR: refactor

#9278 refactor: Associate comment bar buttons with the comment view.
  core/comments/collapse_comment_bar_button.ts
  core/comments/comment_bar_button.ts
  core/comments/comment_view.ts
  core/comments/delete_comment_bar_button.ts
  core/keyboard_nav/comment_bar_button_navigation_policy.ts
  core/keyboard_nav/line_cursor.ts
Labels: PR: refactor

#9281 fix: Drag immovable and shadow blocks along with their parent.
  core/block.ts
  tests/mocha/block_test.js
Labels: PR: fix

#9280 feat: Add initial support for screen readers (experimental)
  core/block_svg.ts
  core/bubbles/bubble.ts
  core/comments/collapse_comment_bar_button.ts
  core/comments/comment_bar_button.ts
  core/comments/comment_editor.ts
  core/comments/comment_view.ts
  core/comments/delete_comment_bar_button.ts
  core/css.ts
  core/dragging/block_drag_strategy.ts
  core/field.ts
  core/field_checkbox.ts
  core/field_dropdown.ts
  core/field_image.ts
  core/field_input.ts
  core/field_label.ts
  core/flyout_button.ts
  core/icons/comment_icon.ts
  core/icons/icon.ts
  core/icons/mutator_icon.ts
  core/icons/warning_icon.ts
  core/inject.ts
  core/rendered_connection.ts
  core/toolbox/category.ts
  core/toolbox/collapsible_category.ts
  core/toolbox/separator.ts
  core/toolbox/toolbox.ts
  core/utils/aria.ts
  core/utils/dom.ts
  core/workspace_svg.ts
Labels: PR: feature

#9284 fix: Keyboard nav CI workflows by pointing to experimentation branch (experimental)
  .github/workflows/keyboard_plugin_test.yml
Labels: PR: fix

#9302 fix: Fix positioning of pasted blocks and comments in RTL.
  core/clipboard/block_paster.ts
  core/comments/comment_view.ts
  core/xml.ts
  tests/mocha/clipboard_test.js
Labels: PR: fix

#9326 fix: Show the delete cursor when dragging a block by an editable field.
  core/css.ts
Labels: PR: fix

#9327 fix: Correct the alignment of narrow text in input fields.
  core/field.ts
  core/field_dropdown.ts
  core/field_input.ts
Labels: PR: fix

#9291 fix: Fix bug that caused inadvertent scrolling when the `WidgetDiv` was shown.
  core/focus_manager.ts
  core/interfaces/i_focusable_node.ts
  tests/browser/test/basic_playground_test.mjs
Labels: PR: fix

#9290 fix: Allow reregistering fields.
  core/field_registry.ts
Labels: PR: fix

#9332 fix: Prevent mocha tests failures when window does not have focus.
  gulpfile.mjs
  package-lock.json
  package.json
  scripts/gulpfiles/test_tasks.mjs
  tests/mocha/webdriver.js
Labels: PR: fix

#9333 fix: Fix bug that could cause errant line when rendering.
  core/renderers/common/drawer.ts
Labels: PR: fix

#9288 refactor: Make focusable elements responsible for scrolling themselves into bounds.
  core/block_svg.ts
  core/bubbles/bubble.ts
  core/comments/comment_bar_button.ts
  core/comments/comment_editor.ts
  core/comments/rendered_workspace_comment.ts
  core/field.ts
  core/flyout_button.ts
  core/icons/icon.ts
  core/keyboard_nav/line_cursor.ts
  core/rendered_connection.ts
  tests/browser/test/basic_playground_test.mjs
Labels: PR: refactor
