Repository google/blockly, pull requests merged in 2025-01, with the labels that each got.

#8706 fix: treat media files as binary while packaging them
  scripts/gulpfiles/package_tasks.js
Labels: PR: fix

#8695 fix: Fix unsafe cast in Input.setVisible().
  core/inputs/input.ts
Labels: PR: fix

#8660 chore!: Fix warnings when generating docs.
  api-extractor.json
  core/block.ts
  core/connection.ts
  core/events/events_var_delete.ts
  core/events/events_var_rename.ts
  core/interfaces/i_metrics_manager.ts
  core/interfaces/i_rendered_element.ts
  core/menu.ts
  core/metrics_manager.ts
  core/renderers/common/renderer.ts
  core/workspace_svg.ts
Labels: breaking change, PR: chore

#8702 fix: Fix serialization of the lists_split block.
  blocks/lists.ts
  tests/mocha/blocks/lists_test.js
Labels: PR: fix

#8704 feat: Warn if a variable category is loaded without variable blocks.
  core/variables.ts
  core/variables_dynamic.ts
Labels: PR: feature

#8703 chore: Improve code health of generator tests.
  tests/generators/index.html
  tests/generators/webdriver.js
Labels: PR: chore

#8683 refactor: Reenable workspace resizing after reflowing flyouts.
  core/flyout_base.ts
Labels: PR: refactor

#8719 fix: Paste blocks copied from a mutator into the mutator.
  core/clipboard.ts
  core/shortcut_items.ts
  tests/mocha/clipboard_test.js
Labels: PR: fix

#8720 fix: Disallow adding comments to mutator workspaces.
  core/contextmenu_items.ts
Labels: PR: fix

#8667 feat: Add a generator for all fields on a block.
  core/block.ts
  core/block_svg.ts
  core/serialization/blocks.ts
  core/xml.ts
Labels: PR: feature

#8701 chore: Merge `master` back into `develop` following v11.2.0 release
  package-lock.json
  package.json
Labels: PR: chore

#8721 fix: Reposition the trashcan's flyout in response to workspace changes.
  core/trashcan.ts
Labels: PR: fix

#8656 refactor: Convert renderer typecheck methods to typeguards.
  core/renderers/common/drawer.ts
  core/renderers/common/info.ts
  core/renderers/geras/drawer.ts
  core/renderers/geras/info.ts
  core/renderers/measurables/in_row_spacer.ts
  core/renderers/measurables/input_row.ts
  core/renderers/measurables/jagged_edge.ts
  core/renderers/measurables/next_connection.ts
  core/renderers/measurables/previous_connection.ts
  core/renderers/measurables/round_corner.ts
  core/renderers/measurables/row.ts
  core/renderers/measurables/square_corner.ts
  core/renderers/measurables/statement_input.ts
  core/renderers/measurables/top_row.ts
  core/renderers/measurables/types.ts
  core/renderers/thrasos/info.ts
  core/renderers/zelos/drawer.ts
  core/renderers/zelos/info.ts
Labels: PR: refactor

#8722 feat: Add a BlockSvg.getStyle() method.
  core/block_svg.ts
  core/field_dropdown.ts
  core/field_input.ts
  core/icons/comment_icon.ts
  core/icons/mutator_icon.ts
  core/icons/warning_icon.ts
  core/renderers/zelos/path_object.ts
Labels: PR: feature

#8723 fix: Don't create intermediate variables when renaming a procedure argument.
  blocks/procedures.ts
Labels: PR: fix

#8658 refactor!: Use JSON instead of XML for defining dynamic toolbox categories.
  core/procedures.ts
  core/variables.ts
  core/variables_dynamic.ts
  core/workspace_svg.ts
  tests/mocha/contextmenu_test.js
  tests/mocha/xml_test.js
Labels: breaking change, PR: refactor

#8687 fix: Fix bug that prevented keyboard navigation in flyouts.
  core/block_flyout_inflater.ts
  core/blockly.ts
  core/button_flyout_inflater.ts
  core/flyout_base.ts
  core/flyout_horizontal.ts
  core/flyout_item.ts
  core/flyout_vertical.ts
  core/interfaces/i_flyout.ts
  core/interfaces/i_flyout_inflater.ts
  core/keyboard_nav/ast_node.ts
  core/label_flyout_inflater.ts
  core/separator_flyout_inflater.ts
Labels: PR: fix

#8731 fix: Listen for keyboard shortcuts when the widget or dropdown divs have focus.
  core/inject.ts
Labels: PR: fix

#8733 fix: Fix display of multiline RTL strings in bubbles on Webkit.
  core/bubbles/text_bubble.ts
Labels: PR: fix

#8735 fix: Fix the browser tests.
  core/menu.ts
  tests/browser/test/basic_playground_test.mjs
  tests/browser/test/delete_blocks_test.mjs
  tests/browser/test/procedure_test.mjs
  tests/browser/test/test_setup.mjs
  tests/browser/test/workspace_comment_test.mjs
Labels: PR: fix

#8736 fix: Actually fix the browser tests.
  tests/browser/test/test_setup.mjs
Labels: PR: fix

#8689 fix: Improve the robustness of workspace SVG tests.
  tests/mocha/workspace_svg_test.js
Labels: PR: fix

#8738 fix!: Don't add padding around zero-width fields.
  core/field.ts
  core/renderers/common/info.ts
  core/renderers/geras/info.ts
  core/renderers/thrasos/info.ts
  core/renderers/zelos/info.ts
Labels: breaking change, PR: fix

#8750 feat: Add support for toggling readonly mode.
  core/block.ts
  core/block_svg.ts
  core/comments/workspace_comment.ts
  core/dragging/block_drag_strategy.ts
  core/dragging/comment_drag_strategy.ts
  core/flyout_base.ts
  core/gesture.ts
  core/shortcut_items.ts
  core/workspace.ts
  core/workspace_svg.ts
  tests/mocha/keydown_test.js
Labels: PR: feature

#8754 fix: Fix flaky connection checker test.
  tests/mocha/connection_checker_test.js
Labels: PR: fix
