Repository google/blockly, pull requests merged in 2025-04, with the labels that each got.

#8835 fix!: Tighten and correct typings on ASTNode
  core/keyboard_nav/ast_node.ts
  core/renderers/common/marker_svg.ts
Labels: breaking change, PR: fix

#8859 feat: make getNextNode and getPreviousNode public
  core/keyboard_nav/line_cursor.ts
Labels: PR: feature

#8871 feat: add getSearchRadius to BlockDragStrategy
  core/dragging/block_drag_strategy.ts
Labels: PR: feature

#8873 fix: check potential variables for flyout variable fields
  core/field_variable.ts
  core/workspace.ts
  tests/mocha/field_variable_test.js
Labels: PR: fix

#8864 fix!: change css class for disabled block pattern
  core/css.ts
  core/renderers/common/path_object.ts
  core/renderers/zelos/constants.ts
Labels: breaking change, PR: fix

#8876 feat: make block and workspace implement IContextMenu
  core/block_svg.ts
  core/workspace_svg.ts
Labels: PR: feature

#8877 feat: support menuOpenEvent, menuSelectEvent, location for context menu items
  core/block_svg.ts
  core/comments/rendered_workspace_comment.ts
  core/contextmenu.ts
  core/contextmenu_items.ts
  core/contextmenu_registry.ts
  core/menu.ts
  core/menuitem.ts
  core/workspace_svg.ts
Labels: PR: feature

#8883 feat: add loopback in cursor navigation, and add tests
  core/keyboard_nav/line_cursor.ts
  tests/mocha/cursor_test.js
Labels: PR: feature

#8890 fix: update dependencies so adv compilation works
  core/comments/rendered_workspace_comment.ts
  core/contextmenu.ts
  core/contextmenu_registry.ts
Labels: PR: fix

#8891 feat: menuOpenEvent, menuSelectEvent, and location for context menu items
  core/block_svg.ts
  core/comments/rendered_workspace_comment.ts
  core/contextmenu.ts
  core/contextmenu_items.ts
  core/contextmenu_registry.ts
  core/menu.ts
  core/menuitem.ts
  core/workspace_svg.ts
Labels: PR: feature

#8892 fix: Don't visit invisible inputs with the cursor.
  core/keyboard_nav/ast_node.ts
Labels: PR: fix

#8881 fix: Fix keyboard-driven menu scrolling.
  core/css.ts
  core/field_dropdown.ts
  core/menu.ts
Labels: PR: fix

#8882 feat!: deprecate scopeType and include focusedNode in context menu options
  core/block_svg.ts
  core/comments/rendered_workspace_comment.ts
  core/contextmenu_registry.ts
  core/workspace_svg.ts
Labels: breaking change, PR: feature

#8895 feat: show context menu for connections
  core/rendered_connection.ts
Labels: PR: feature

#8833 Feature: Add a dropdown options setter
  core/field_dropdown.ts
  tests/mocha/field_dropdown_test.js
Labels: PR: feature

#8903 fix: Recreate the dropdowndiv when clearing it.
  core/dropdowndiv.ts
Labels: PR: fix

#8904 chore: Add messages from the keyboard experiment.
  msg/json/en.json
  msg/json/qqq.json
  msg/messages.js
Labels: PR: chore

#8908 fix: Add some missing message strings.
  msg/json/en.json
  msg/json/qqq.json
  msg/messages.js
Labels: PR: fix

#8854 Fix: Remove the collapsed block warning when expanding a block
  core/block_svg.ts
  tests/mocha/block_test.js
Labels: PR: fix

#8896 feat: Add support for displaying toast-style notifications.
  core/blockly.ts
  core/dialog.ts
  core/toast.ts
  core/utils/aria.ts
  msg/json/en.json
  msg/json/qqq.json
  msg/messages.js
  tests/mocha/contextmenu_items_test.js
  tests/mocha/dialog_test.js
  tests/mocha/index.html
  tests/mocha/test_helpers/workspace.js
  tests/mocha/toast_test.js
Labels: PR: feature

#8811 chore: Try another workflow permission.
  .github/workflows/assign_reviewers.yml
Labels: PR: chore

#8916 feat: Make WorkspaceSvg and BlockSvg focusable
  core/block_svg.ts
  core/inject.ts
  core/renderers/common/path_object.ts
  core/workspace_svg.ts
Labels: PR: feature

#8926 fix: LineCursor can loop forward, but not back
  core/keyboard_nav/line_cursor.ts
  tests/mocha/cursor_test.js
Labels: PR: fix

#8936 fix: Support RTL in WorkspaceSvg.scrollIntoBounds
  core/workspace_svg.ts
Labels: PR: fix

#8947 chore: update assignment workflow permissions for v12
  .github/workflows/assign_reviewers.yml
Labels: PR: chore

#8938 feat: Make WorkspaceSvg and BlockSvg focusable (roll forward)
  core/block_svg.ts
  core/css.ts
  core/inject.ts
  core/renderers/common/path_object.ts
  core/workspace_svg.ts
Labels: PR: feature

#8939 feat: Make toolbox and flyout focusable (roll forward)
  core/flyout_base.ts
  core/flyout_button.ts
  core/interfaces/i_flyout.ts
  core/interfaces/i_toolbox.ts
  core/interfaces/i_toolbox_item.ts
  core/toolbox/category.ts
  core/toolbox/separator.ts
  core/toolbox/toolbox.ts
  core/toolbox/toolbox_item.ts
  core/workspace_svg.ts
  tests/mocha/toolbox_test.js
Labels: PR: feature

#8923 feat: Make fields focusable
  core/dialog.ts
  core/dropdowndiv.ts
  core/field.ts
  core/widgetdiv.ts
  core/workspace_svg.ts
Labels: PR: feature

#8928 feat: Make connections focusable
  core/connection.ts
  core/rendered_connection.ts
  core/renderers/common/drawer.ts
  core/renderers/common/i_path_object.ts
  core/renderers/common/path_object.ts
  core/renderers/zelos/drawer.ts
  core/workspace_svg.ts
Labels: PR: feature
