Repository google/blockly, pull requests merged in 2025-02, with the labels that each got.

#8753 fix: Fix bug that caused blocks dragged from non-primary flyouts to be misplaced.
  core/block_flyout_inflater.ts
  core/button_flyout_inflater.ts
  core/flyout_base.ts
  core/interfaces/i_flyout_inflater.ts
  core/label_flyout_inflater.ts
  core/separator_flyout_inflater.ts
Labels: PR: fix

#8749 fix: Improve menu mouse/keyboard selection interaction.
  core/menu.ts
Labels: PR: fix

#8765 fix: Fix menu scrolling.
  core/field_dropdown.ts
  core/menu.ts
  core/utils/style.ts
Labels: PR: fix

#8766 fix: Allow dragging blocks from the far lower right corner.
  core/css.ts
Labels: PR: fix

#8774 feat: Add interfaces for focus management
  core/blockly.ts
  core/interfaces/i_focusable_node.ts
  core/interfaces/i_focusable_tree.ts
Labels: PR: feature

#8781 fix: Fixes #8764 by moving the event grouping calls up to dragger.ts
  core/dragging/block_drag_strategy.ts
  core/dragging/bubble_drag_strategy.ts
  core/dragging/comment_drag_strategy.ts
  core/dragging/dragger.ts
Labels: PR: fix

#8779 fix: Fix bug that prevented editing workspace comments on Firefox.
  core/comments/rendered_workspace_comment.ts
Labels: PR: fix

#8780 fix: Fix bug in IF block generators.
  generators/dart/logic.ts
  generators/javascript/logic.ts
  generators/lua/logic.ts
  generators/php/logic.ts
  generators/python/logic.ts
Labels: PR: fix

#8783 refactor: make CommentView more amenable to subclassing.
  core/comments/comment_view.ts
Labels: PR: refactor

#8785 fix: Disallow and ignore x and y attributes for blocks in toolbox definitions.
  core/block_flyout_inflater.ts
  core/utils/toolbox.ts
Labels: PR: fix

#8767 feat!: Added support for separators in menus.
  core/contextmenu.ts
  core/contextmenu_registry.ts
  core/css.ts
  core/extensions.ts
  core/field_dropdown.ts
  core/menu.ts
  core/menu_separator.ts
  core/utils/aria.ts
Labels: breaking change, PR: feature
